### ISSUE TITLE
[Feature Request] Add "Swagger documentation" in Docs tab

### ISSUE THREAD

**Issue by Azef1** [getinsomnia/insomnia#1007]
- Insomnia Version: 5.16.6
- Operating System: Win10 x64

## Details
It will be nice to see documentation swagger in "Docs" tab ;)
For example, try to import this swagger definition: https://petstore.swagger.io/v2/swagger.json 
Go to "GET Finds Pets by status" then go to "Docs" tab.

Currently, there are nothing in docs tab:
![image](https://user-images.githubusercontent.com/15362041/41873246-be4ab6d2-78c4-11e8-87c2-19ad77d84fb4.png)

It will be nice to have something like that: 
To embed "[swagger documentation](http://petstore.swagger.io/#/pet/findPetsByStatus)" inside Insomnia
![image](https://user-images.githubusercontent.com/15362041/41873484-6017e778-78c5-11e8-9bd5-de9cc175554c.png)

What do you think ?

**Comment by gschier** [comment]
I think it would be great! I don't know anything about Swagger, though, but I'd be happy to merge a PR that adds it (should be fairly easy?).

**Comment by Azef1** [comment]
Go to http://editor.swagger.io/ and https://github.com/swagger-api/swagger-ui
With code source, it should be easier to add this feature request in Insomnia

**Comment by gschier** [comment]
Thanks for the links @Azef1! 

Unfortunately I don't have the cycles to look into this right now but, like I mentioned above, am happy to help out someone who want to work on a PR. 

If so, here's a good starting point.: https://github.com/getinsomnia/insomnia/blob/develop/packages/insomnia-importers/src/importers/swagger2.js

**Comment by janz93** [comment]
I would love to take a look at it if that is okay.

**Comment by gschier** [comment]
Sure @janz93 😄 that would be awesome 💯

**Comment by janz93** [comment]
I looked into the issue in more detail and currently face some problems.
Currently the content of the description [is expected to be markdown](https://github.com/getinsomnia/insomnia/blob/develop/packages/insomnia-app/app/ui/components/request-pane.js#L399) so I can't store the HTML into the database and expect it to be rendered properly.
A workaround would be the sore the whole JSON response into the database and render the description in real-time. You need the whole JSON file in order to be able to resolve the model references properly.
Yet this would require a logic switch at the description rendering.
But there are some downsides to it, as storing the whole JSON response feels a little dirty to me and the logic switch bloats the code just for the swagger use case

@gschier What do you think?

**Comment by gschier** [comment]
Uh oh, I don't think I read the issue correctly the first time. What I thought the issue was describing was using the swagger `description` attribute (which is in Markdown) during the Insomnia import.

Sorry for the misunderstanding. Injecting the full Swagger documentation HTML is probably too heavy for a first-party feature.

**Comment by janz93** [comment]
@gschier Okay what does that mean for this issue?

**Comment by gschier** [comment]
Luckily this issue is fairly isolated. All data importers are contained in an internal package that can be developed and tested without ever running Electron.

https://github.com/getinsomnia/insomnia/tree/develop/packages/insomnia-importers
