### ISSUE TITLE
[Bug] Stuck on blank window after opening

### ISSUE THREAD

**Issue by nospoon** [getinsomnia/insomnia#1034]
- Insomnia Version: 5.16.6
- Operating System: OSX 10.13.5 High Sierra

## Details

At some point today Insomnia stopped responding, after shutting it down and restarting, it now only shows completely blank white window. Restarting the application multiple times and restarting the system didn't help either.

**Comment by gschier** [comment]
It sounds like you maybe sent a request that returned a large response?

Check to see if there are any response bodies larger than a few megabytes in `~/Library/Application Support/insomnia/responses`. FYI, it's safe to delete them. They just won't show up in the UI anymore.

**Comment by drejc** [comment]
I had the same issue with very large responses. Every time I select a previously invoked REST that returned a large response, it can take up to a minute before insomnia shows anything. I assume it has something to do with the JSON parsing engine. I would suggest to trim large responses and provide an option to see the raw response in a separate window.

**Comment by kerobero** [comment]
I have the same issue on Windows 10.
My problem is the **insomnia.Request.db**, it's big around 700 MB (I do not understand why)
If i delete it the app opens normally. 
I need recover my requests, how can I recover them?

**Comment by gschier** [comment]
@kerobero if you deleted it, you cannot recover your requests. If you made a backup, you may be able to manually edit the file to remove the large responses.

There are a few issues at play here.

1. Insomnia uses NeDB to store data locally. NeDB uses an append-only file format so every modification to a request appends a new copy of said request to the end of the request DB.
2. NeDB cannot open files larger than 256MB because that's the max string length of NodeJS

This bug happened a lot with responses early on, so a change was made to store response externally to the entry in the DB file. A similar thing could be done for requests so that large request bodies don't cause the DB to balloon out of control.

**Comment by kerobero** [comment]
Thanks @gschier , 
I split the file and recover the data. I think that there is a bug because some lines at the end of file are duplicate.
