### ISSUE TITLE
[Feature Request] Self-signed SSL Validation on MacOS

### ISSUE THREAD

**Issue by StummeJ** [getinsomnia/insomnia#1081]
- Insomnia Version: 6.0.1.2298
- Operating System: MacOS 10.13.3

## Details
When trusting a self-signed cert in the OSX keychain Insomnia still does not trust the certificate.  This forces me to disable all SSL validation, which I want for other requests.  Can Insomnia be updated to either read certificates from the mac keychain, or have a disable ssl validation per request/folder/workspace?

Cheers 😄

**Comment by gschier** [comment]
I don't think this will be possible, unfortunately. Insomnia uses the OS's `libcurl` to send requests which, as of High Sierra, removed support for using OS-level certs (it's now build with `LibreSSL` instead of `Secure Transport`).

SSL library reference: https://curl.haxx.se/docs/ssl-compared.html

**Comment by brolaugh** [comment]
Would it be possible to add a list of domains/ip addresses which should be white listed from the `Validate SSL Certificates` option as an option? 


The list could look something like this:
```
192.168.1.0/24
localhost
example.org
```

**Comment by StummeJ** [comment]
Any update on if this can be a possible feature?

**Comment by gschier** [comment]
Whitelist would be a good idea. It would fit right in within the Workspace settings. Please post this as a new issue since it's not related to the original report.
