### ISSUE TITLE
[Feature Request] API testing via chained requests and assertions

### ISSUE THREAD

**Issue by mbarretta** [getinsomnia/insomnia#1091]
- Insomnia Version: 6.0.1

## Details

To test an API, it's helpful to be able to define a number of requests along with success assertions (i.e. test suite) and have those requests run in sequence. This is a similar idea to ["Scenarios" in Restlet](https://restlet.com/documentation/client/user-guide/test/chain-requests)

**Comment by mbarretta** [comment]
related: https://github.com/getinsomnia/insomnia/issues/539

**Comment by gschier** [comment]
Thanks for the request @mbarretta! I thought there was an issue for this already but I couldn't find it.

Automated testing/scripting do not currently fit into the scope of Insomnia. Insomnia's goal is to be an easy-to-use HTTP client first and foremost, which means not adding features like testing/mocking/load-testing/etc as first-party features. However... I agree that features like this should be possible and that's why the plugin system exists. The plugin APIs aren't robust enough yet for someone to implement a testing plugin but they'll hopefully get there eventually.
