### ISSUE TITLE
[Bug] White screen when making HTTPS request & ignoring invalid cert

### ISSUE THREAD

**Issue by SneakyMax** [getinsomnia/insomnia#1203]
- Insomnia Version: 5.16.2 - 6.0.1 (6.0.2 -6.0.3 beta crash for me)
- Operating System: CentOS 7 (AppImage)

## Details

I am connecting to a service on `https://localhost:8000/` - it uses a self-signed SSL cert. I have SSL cert validation disabled in Insomnia. In 5.15.0, everything works fine. In 5.16.2 and later, a white screen shows up when a request is made (or the GraphQL schema is fetched). 5.16.0 and 5.16.1 do not launch for me.

Reproduction:

I'm not sure of the best steps, but in increasing specificity:

1. Connect to a regular HTTPS service with SSL validation disabled
2. Connect to a self-signed cert HTTPS service with SSL validation disabled
3. Connect to a GraphQL server with a self-signed cert with SSL validation disabled.
4. Same steps as above, but try on Linux

If the app crashes, is it possible that something better could happen than just a white screen?

**Comment by gschier** [comment]
Does this still happen on 6.2+?

**Comment by SneakyMax** [comment]
@gschier I'm still getting a white screen on the latest version.

**Comment by gschier** [comment]
Any errors in View > Toggle DevTools > Console?

**Comment by gschier** [comment]
Hmm, I'm not sure if there's another way to debug the issue. I'm 99% sure that's caused by Insomnia's included `libcurl` library not being able to locate a shared library on your machine, which doesn't really make sense.

In 5.16.0, Insomnia switched from including a shared version of `libcurl` to a static version. The purpose of this was to remove the necessity for the user to have a correct version of `libcurl` installed on their machine.

Do you know enough about Linux to figure out what's happening on your box?
