### ISSUE TITLE
[Question] symbol lookup error while running from local build

### ISSUE THREAD

**Issue by evanslify** [getinsomnia/insomnia#1227]
- Insomnia Version: `origin/develop`
- Operating System: Fedora 28

## Details

I tried to run insomnia with local build created with `npm run app-package`. As I run it, it shows:

```
symbol lookup error: /tmp/.org.chromium.Chromium.yjPue2: undefined symbol: curl_version_info
```

I do have `curl`, `libcurl` and `libcurl-devel` installed. What am I missing here?

**Comment by gschier** [comment]
Can you try again on the latest `develop`?

**Comment by evanslify** [comment]
It works if running AppImage and `linux-unpacked`, but will complain about missing `libcurl.so.4` if installed using `snap install ./insomnia_6.1.0-beta.1_amd64.snap --dangerous`.

**Comment by evanslify** [comment]
It works if running AppImage or `linux-unpacked/insomnia`, but will complain about missing `libcurl.so.4` if installed using `snap install ./insomnia_6.1.0-beta.1_amd64.snap --dangerous`.

**Comment by gschier** [comment]
I think that is because Snaps are sandboxed. If you want to generate a packaged version of the app for Linux, you should use the included `Dockerfile`, which will link `libcurl` and its dependencies as a static library.

Note, if you just want to run it for development, you should be using `npm run app-start` and not `npm run app-package`. **Can I ask why you are trying to package the app yourself?**

**Comment by evanslify** [comment]
Somehow my snap install doesn't use the right font, it uses Courier New
instead. And the version on snap is a little bit behind, so I figure that a
local install would be a temporary solution.

**Comment by gschier** [comment]
Going to close this one, as the `app-package` command is not meant to be run on arbitrary environments.
