### ISSUE TITLE
[Question] 6.2.0 version could open Multi-Window now ?

### ISSUE THREAD

**Issue by insub** [getinsomnia/insomnia#1277]
On windows 6.2.0 version I found that I could open Multi-Window now. But I didn't find it mentioned in the changelog. I'm not sure if this will lead to usage problems. It looks like everything's okay.
#667 

By the way, windows v6.2.0 installer is  120 MB size, much larger than v5.x. Is this correct?

**Comment by gschier** [comment]
I'm pretty sure you could always open multiple windows on Windows/Linux by simply launching the app twice or more. We should probably prevent this behavior somehow because the local app database does not support concurrent connections.

I'm not sure why the installer is so large but I'll take a look and see if I can find out why.
