### ISSUE TITLE
Google Chrome blocks the site

### ISSUE THREAD

**Issue by ViieeS** [getinsomnia/insomnia#1285]
https://insomnia.rest/download/#mac

![image](https://user-images.githubusercontent.com/8194543/49288556-23655680-f4b2-11e8-897e-2730b2b0ca82.png)

**Comment by gschier** [comment]
This should be fixed now. I was notified via Google Webmaster Tools of this last night. It's frustrating because they don't give you a reason but I suspected it was because that page triggered an automatic download to a 3rd-party site (GitHub.com). I have changed this behavior and they have lifted the ban.

Please let me know if you are still seeing this.

**Comment by ViieeS** [comment]
@gschier all good now 👍🏻Thanks!
