### ISSUE TITLE
More details on timeline

### ISSUE THREAD

**Issue by jackTaw88** [getinsomnia/insomnia#1416]
Hi,

It is possible to show more details on timeline? At least can it be optional?

For example the details of handshake: https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_7.1.0/com.ibm.mq.doc/sy10660_.htm

Thank you

**Comment by senoctar** [comment]
Some SSL handshake details are printed in the timeline as output from cURL. Sessions can be kept open for a while and you won't see the details every time because a handshake is not performed.
Here is an output for an expired certificate:
![image](https://user-images.githubusercontent.com/970918/56090369-3e0cfa80-5eaa-11e9-8a94-19ddbf3e9902.png)

**Comment by gschier** [comment]
Unfortunately we cannot provide any more details on this since the info is coming straight from `libcurl`.
