### ISSUE TITLE
[Bug] Paste text from clipboard into graphql body fails

### ISSUE THREAD

**Issue by royledford** [getinsomnia/insomnia#1460]
- Insomnia Version: 6.4.0.2712
- Operating System: MacOs Mojave 10.14.2 

## Details

Bug. I think this started happening after the latest update.

Open any existing (or create new) request, set to POST and body to graphQl.
paste text into body

In new, nothing happens
In existing, all existing text disappears and new pasted text does not show.

**Comment by gschier** [comment]
Hmm, I can't reproduce this. Would it be possible to provide a screen recording of the issue?

**Comment by royledford** [comment]
It seems it is a bit different than what I originally thought.

I copied text from a code block in MS Teams and pasted and that failed.

Also opened a new file in VS Code and pasted text. Works and looks correct in VS Code, copied that to clipboard, and then pasted into a query in insomnia and that failed.

To reproduce:
* create a graphql query in insomnia
* select and copy query text from teams message
* select all text in insomnia
* paste text
* Notice, existing text goes away and a lighter coloured box is displayed


![insomnia-test (1)](https://user-images.githubusercontent.com/27828240/56769280-bfa03a80-677e-11e9-9538-1d4c82f58072.gif)

Someone else on my team mentioned they see it happen when copying from one query to another with insomnia as well (they are on unbuntu). I'm on mac.

**Comment by gschier** [comment]
Unfortunately I still can't reproduce on my Mac using 6.4.1. Does this happen when you copy text from anywhere or specifically MS Teams? I'm thinking it might be cause by copying "rich text" into the Insomnia editor.

Can you also check View > Toggle DevTools > Console for any errors? Since the line numbers disappear completely after you paste, it seems like it's crashing the entire CodeMirror text editor as the default empty state should still have the first line visible.

![image](https://user-images.githubusercontent.com/587576/56774429-7993a880-6777-11e9-9ba0-82051eb5bbfd.png)

**Comment by royledford** [comment]
Yes, only when copying text from teams. I was thinking it was a rich text issue.
But odd that pasting into vs code, then copying again and pasting into insomnia had the same behaviour.

Here is the log ss
![image](https://user-images.githubusercontent.com/27828240/56835949-a44b3300-6843-11e9-89f9-87ab08661958.png)

**Comment by gschier** [comment]
Thanks for the screen shot @royledford. It might be possible that VSCode acts differently since it's backed by a different text editor framework.

Unfortunately, I can't seem to find a source to copy from that reproduces this. Do you happen to have an example from a public web page that I can test with?

**Comment by gschier** [comment]
It could also be that there are some funky unicode characters in what you are copying that get preserved when pasting them into VSCode.

**Comment by gschier** [comment]
Okay, I was able to reproduce this outcome but by pressing Option+Space instead, which inserts a weird unicode character. https://github.com/getinsomnia/insomnia/issues/1254

**Comment by gschier** [comment]
After some research, it looks like Option+Space inserts a "Non-breaking space" specifically, which is very common in HTML. So perhaps, when copying text from MS Teams, these magical spaces get included?

**Comment by royledford** [comment]
Thanks for looking into this. Don't have a public source to copy from.

I pasted from teams into https://www.soscisurvey.de/tools/view-chars.php to see what was getting pasted

![image](https://user-images.githubusercontent.com/27828240/56921955-15355980-6a95-11e9-9a64-cf008a9b1678.png)

It looks likes it's using nbsp for the tabs. Seems odd but...that's what it does.

I may go create a ticket on teams and see if they know what's happening.

**Comment by gschier** [comment]
Woah, thanks for sharing that tool. I could definitely use that in the future.

I've released an update 6.4.2 today which will convert non-breaking spaces in GraphQL queries into normal spaces. Let me know if it solves your problem.

**Comment by royledford** [comment]
Thanks for taking the time to look into this. Haven't got 6.4.2 yet but will try once it comes through.

And thanks for the quick response. Insomnia is a great product!
