### ISSUE TITLE
[Bug] Pull for Updated Snapshot is greyed out in bottom menu

### ISSUE THREAD

**Issue by Fyb3roptik** [getinsomnia/insomnia#1461]
- Insomnia Version: 6.4.1
- Operating System: MacOS

## Details

I created a new snapshot and pushed. My dev team could not do a pull from the bottom sync menu. It was really confusing! Instead they had to click the top left menu and do the pull there. Should probably update the bottom menu to match

**Comment by gschier** [comment]
_Responding here with a summary from our email thread_

Currently, in the [new sync beta](https://support.insomnia.rest/article/67-version-control), each member of the dev team needs to _pull_ the project locally in order to start collaborating. This becomes confusing when migrating from the old sync system because they will have already had the workspace on their machine but it won't be tracking the remote project yet.

When a project is shared with you, it will show up in the main application dropdown below the local workspaces in a new section labelled "Remote Workspaces".

![image](https://user-images.githubusercontent.com/587576/56771083-8cec4700-676a-11e9-8bc0-f20eca754f3d.png)

**Comment by Fyb3roptik** [comment]
Also I should note that I did another push after they subscribed and he could not pull until he closed Insomnia and re-opened it

**Comment by gschier** [comment]
Hmm, that's not expected. I will keep an eye out for that issue.
