### ISSUE TITLE
[Bug] Unable to pull, says all endpoints have been edited

### ISSUE THREAD

**Issue by Fyb3roptik** [getinsomnia/insomnia#1504]
- Insomnia Version: 6.5.3
- Operating System: MacOS 10.14.5

## Details

I push out changes regularly to Insomnia and everyone on my team pulls them. One of my team members his Insomnia shows ALL endpoints as edited and he cannot pull. He has not changed anything with the endpoints, so no idea how this is happening.

Can we either have an option to pull and overwrite all changes or a revert all changes? I need my team to be able to pull and force the pull!

**Comment by gschier** [comment]
There was a new setting added to the Request object in the latest release which is why it says they've all been modified. You can see which fields have been modified when creating a snapshot:

![image](https://user-images.githubusercontent.com/587576/57869687-900bad80-77d3-11e9-9a14-e4afac186a25.png)

Unfortunately it's not possible to revert this change since it will automatically be re-added to the local database immediately. It is possible to revert normal changes, however:

![image](https://user-images.githubusercontent.com/587576/57869785-c34e3c80-77d3-11e9-99c0-58a8f0a080d3.png)

For your teammates to pull, they will have to create a snapshot, then pull. This will merge in the new setting. They can then push the result of the merge back to the teamm.

**Comment by gschier** [comment]
That being said, performing a force pull should be an option. You can do this via a workaround by deleting the workspace locally, then pulling again from the top-left workspace dropdown.

**Comment by Fyb3roptik** [comment]
Ah ok I will have him create a snapshot and pull, then push. So far great stuff man!

**Comment by gschier** [comment]
I'm glad you're liking it! Thanks for continuing to give this awesome feedback too 😄
