### ISSUE TITLE
[Feature] Json Preview: collapse all items and collapsed snippets for humans

### ISSUE THREAD

**Issue by 4n70w4** [getinsomnia/insomnia#1536]
It will be very useful to collapse and expand all the nodes with one button (the red arrows in the screenshot).

And it will be useful to make a more informative view of collapsed elements (blue arrows in the screenshot). May be show first chars of collapsed values.

![image](https://user-images.githubusercontent.com/38257723/58696569-802dc500-83a0-11e9-86f6-883edba8f3ed.png)

**Comment by NSExceptional** [comment]
+1 for this feature. Super annoying when you need to see the last thing in a long list of objects.

**Comment by miraclx** [comment]
What's the progress on this? would be really handy.

**Comment by SergioSuarezGil** [comment]
+1 for this feature

Would be nice add an option in Insomnia to do this feature

**Comment by develohpanda** [comment]
![2020-09-25 10 31 08](https://user-images.githubusercontent.com/4312346/94206774-59db5380-ff1a-11ea-9ce5-9776ee7cad3a.gif)

With 2020.4.1 we shipped #2626 - so, resolved!

> Use Shift Cmd - or Shift Ctrl - to fold all nodes
Use Shift Cmd = or Shift Ctrl = to unfold all nodes

cc: @SergioSuarezDev @miraclx

**Comment by miraclx** [comment]
🎉

**Comment by welschmoor** [comment]
Three points
1. I wish there was a default option to always collapse top level keys in preview, because after each request I have to click into preview and use the shortcut, making it somewhat useless.

2. The performance is bad. It is sometimes slow, so I spammed the shortcut a few times which froze Insomnia on Mac with the message: "Insomnia has become unresponsive. Do you want to reload?" <- I could reproduce it by hitting the shortcut ~5 times. The response is about 6000 lines large.

3. And last: the CMD+Z  undo functionality in request body json window does not work most of the time. I lose valuable entries. It did not happen in version 8.x.x, but now I have the newest version 11.6.1 which has this bug.
