### ISSUE TITLE
[Feature Request] Literal strings in JSON post body (no environment variable replacement)

### ISSUE THREAD

**Issue by reevesm** [getinsomnia/insomnia#1561]
- Insomnia Version: 6.4.0.2712
- Operating System: macOS Mojave 10.14.5

## Details

Would like to be able to turn off environment variables for JSON body posts or have an option to use a literal string without environment variable replacement. Using some handlebars variables that use the same format inside of a string that I want treated literally, not replaced. Since they aren't known environment variables, Insomnia is throwing errors.

Example:
```
{
   "myfield": "{{ handlebars_variable_doesnt_exist_in_environment }}"
}
```

**Comment by gschier** [comment]
You can do this in the request settings, or surround your value in `{% raw %}...{% endraw %}`

![image](https://user-images.githubusercontent.com/587576/60369750-a99f3800-99c2-11e9-8dbc-8d3ca054114a.png)

**Comment by reberthkss** [comment]
@gschier can you ellaborate?

**Comment by luka-bip** [comment]
@reberthkss If you click on the arrow next to a particular request, then choose Settings, you'll get the options pictured above. Checking the one that's not checked will prevent variable substitution in the body of the request. Would be nice if there was a more general way to do this rather than on per-request basis though.
