### ISSUE TITLE
[Question] Escaping {% and %}

### ISSUE THREAD

**Issue by jkmartindale** [getinsomnia/insomnia#1602]
- Insomnia Version: 6.5.4
- Operating System: Windows 10 v1903

## Details
I'm debugging a web service that stores URL-encoded JSON in one of its cookies. Yes I know that's awful, but that's [Parse.ly](https://www.parse.ly/)'s decision, not mine.

The problem is now I have a cookie that looks like this:
```
_parsely_visitor={%22id%22:%22pid=70617273656c79207375636b73%22%2C%22session_count%22:244%2C%22last_session_ts%22:1559156958078}
```

and that `{%` trips up Insomnia's template engine.
```
unknown block tag: 22id
```

I've tried wrapping the cookie string with `{% raw %}` and `{% endraw %}` but this seems to have no effect.

**Comment by gschier** [comment]
Hmm, this is a tricky one. The reason the `raw/endraw` tags don't work is probably because Insomnia may render parts of the request multiple times depending on what it's doing. So, the first render will remove the `raw/endraw` tags and the next render will render what they used to surround.

Unfortunately there's no workaround for this that I can think of at the moment but maybe we could add a setting (global or per-request) to disable rendering of cookies. We already have a per-request setting to disable rendering of request bodies in for similar reasons.

**Comment by jkmartindale** [comment]
Dang, didn't mean to let this close. I would really appreciate a per-request or per-workspace option to disable rendering cookies.

**Comment by willpoorman** [comment]
Hi, I recently ran into this issue with a cookie being set in Insomnia by a site I'm testing requests against that contains URL-encoded JSON as well. I have to delete the cookie between every request, otherwise the next one fails with the "failed to render Request.cookies[2].valuie prior to sending" error.

Perhaps Insomnia could at least be set to not try to to render cookies that weren't set by the user with template strings. I don't think there's any reason to expect cookies set by a site would want to be using template variables set explicitly in Insomnia

**Comment by oleg-codaio** [comment]
Wanted to bump this one up - constantly running into this issue myself.

**Comment by conmute** [comment]
Got the same, wanted to test why request is failing, but getting this problem constantly

**Comment by ap1969** [comment]
Same issue here - I'm trying to send a nunjucks template, which uses {%xxx%} formatting, but Insomnia tries to parse it. A per-request ability to disable parsing would be great.

**Comment by ghost** [comment]
I had a similar issue when trying to send `%}xyz` in a field in the JSON body, and followed the advice in this reply  <a href="https://github.com/Kong/insomnia/issues/3119#issuecomment-811658723">Insomnia Issue #3119</a> to skip rendering of the request body, which seemed to solve this issue. The setting is found in the individual request settings.
