### ISSUE TITLE
[Feature Request] No names, just urls

### ISSUE THREAD

**Issue by robclancy** [getinsomnia/insomnia#1628]
I hate naming things and I don't know when I would ever want to name a request. The URL and method tells me everything I need to know. Right now my names are just copy pasted of everything after the domain. For example just named one `/api/clients/2/guests`.

Would be nice if we could just disable names and have it automatically use the URI path.

**Comment by gschier** [comment]
Please remember that a wide variety of people use Insomnia and for many different use cases. While I understand the desire for showing URLs, having names is also very important.

For example, you may have two requests with the same URL and method, but a different body or different auth. Personally, I like to use names because I find them easy to remember, which is useful when navigating via Cmd+p

There is already an open issue for the thing you have suggested so feel free to leave a comment there: #1505

Going to close this one as a duplicate

**Comment by robclancy** [comment]
That's why I said it as an option to disable them.
