### ISSUE TITLE
Line numbers overlap JSON body

### ISSUE THREAD

**Issue by arbitrary-dev** [getinsomnia/insomnia#1647]
- Insomnia Version: **v6.6.2**
- Operating System: **MacOS High Sierra 10.13.2**

## Details

1. Turn off body text wrapping
1. Scroll long body horizontally, so that line numbers start to overlap it
1. Observe:

<img width="89" alt="Screen Shot 2019-08-22 at 11 49 26 AM" src="https://user-images.githubusercontent.com/6984946/63500682-f9861100-c4d2-11e9-8b45-f78631e6474f.png">

## Proposal

Would be nice to have some 80% opaque background under line numbers, so that they're distinct.

**Comment by gschier** [comment]
Hmm, I _have_ seen this happen a long time (years) ago. I can't seem to reproduce this bug though now.

The expected behavior is that line numbers always appear beside the main content. The fact that they are overlapping in your screenshot should never happen.

Does it still do this for you after a fresh app launch?

![image](https://user-images.githubusercontent.com/587576/63561208-ef353880-c50d-11e9-83c9-4ab491763ffc.png)

**Comment by arbitrary-dev** [comment]
Sorry, forgot to mention that you need to have not only text wrapping disabled, but also a long line to scroll vertically so that line numbers start to overlap with main content.

**Comment by ranjan-purbey** [comment]
The transparency seems to be added intentionally. L74 in `packages/insomnia-app/app/ui/css/editor/general.less`
```
  .CodeMirror,
  .cm-s-seti.CodeMirror, // Hack because seti theme is dumb
  .CodeMirror-gutters,
  .CodeMirror-scrollbar-filler,
  .CodeMirror-gutter-filler {
    // Let the background behind show through
    background-color: transparent !important;
    border: 0;
  }
```
If we remove gutters class from the list, the issue is resolved. Should I create a PR with this change?

**Comment by arbitrary-dev** [comment]
I'd rather make `background-color` the same as background behind it, but with 80% transparency.

**Comment by ranjan-purbey** [comment]
The background color is stored in a CSS var `--color-bg`. Is there any straightforward way to change it's transparency?
