### ISSUE TITLE
[BUG] Insomnia fails to start on MacOS Catalina

### ISSUE THREAD

**Issue by DorianCzichotzki** [getinsomnia/insomnia#1728]
- Insomnia Version: 7.0.1
- Operating System: MacOS Catalina 10.15

## Details
The app is not starting because "Apple is unable to scan Insomnia for malware".
The error message states that the developer needs to update the app.

Insomnia was installed using homebrew.

**Comment by gschier** [comment]
That error shows when an app is not notarized (new in Catalina). Insomnia shouldn't have to be notarized because it's not a new developer ID so I'm not really sure why that happened. However, I'm working on getting a notarized build up soon so that should fix the issue.

For now, can you try installing the 7.0.2-beta.1 DMG from here? https://github.com/getinsomnia/insomnia/releases/tag/v7.0.2-beta.1

**Comment by gschier** [comment]
Should be fixed now in version 7.0.2
