### ISSUE TITLE
[Feature Request] Workspace Sync : Swagger

### ISSUE THREAD

**Issue by qlaffont** [getinsomnia/insomnia#1881]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to remove and import again my Swagger when I update my API.

**Describe the solution you'd like**
- Have a button on "Workspace Settings" to manually update Workspace according to Swagger URL (Keep Existing Environment).
- Have an option to automatically sync Workspace to Swagger (Every time Insomnia is launch OR every 5/15min)

**Other informations**
I love this product ! Keep going ! 💪

**Comment by filfreire** [comment]
Hello @qlaffont thanks for reporting this!

We have since added the [Design Documents](https://docs.insomnia.rest/insomnia/design-documents) feature into Insomnia. You should be able to for example, create a new Design Document, from a Swagger or OpenAPI file. And you should also be able to update the existing Design document, when you import a new version of that Swagger.

In theory, also with our [Git Sync](https://docs.insomnia.rest/insomnia/git-sync) feature, you should also be able to semi-automatically sync whatever changes happen on Swagger. You would still need to either edit it from within Insomnia, or reimport it to your existing Design Doc.

Feel free to open another issue if you have more ideas or problems you are facing!

**Comment by denileo82** [comment]
even with this feature (Design documents) when you reimport from OpenAPI definition URL, the environments (servers) are duplicating every time.
