### ISSUE TITLE
[Feature Request] Allow access to OS env variable values

### ISSUE THREAD

**Issue by edirinIndex** [getinsomnia/insomnia#1883]
**Is your feature request related to a problem? Please describe.**
I use tokens & keys generated from an external site. I currently have to replace these values every day in the environment variable before making requests. However, these values are refreshed every day as an underlying system variable. e.g. on startup bash/zsh would run function to refresh the token.

**Describe the solution you'd like**
I will like to have Insomnia us underlying OS variables so I can take advantage of pre-populated keys, which enable me to reduce copy/pasting effort and allow teams to share collections as all team members have effectively the same underlying variables. 

**Describe alternatives you've considered**
None

**Additional context**
None.

**Comment by arboleya** [comment]
I am also looking forward to this.

**Comment by etauker** [comment]
I created a simple plugin for doing this https://www.npmjs.com/package/insomnia-plugin-system-env. 
Then I found that there was already a plugin for this https://www.npmjs.com/package/insomna-plugin-system-variable. Strangely neither one appears in the new plugin hub https://insomnia.rest/plugins and I cannot seem to find documentation on what is required to list it there.

**Comment by bongosway** [comment]
@etauker Nice one. I already plugged away to create without checking here to see you have created one.

Mine here:
https://github.com/bongosway/insomnia-plugin-systemenv

We can discuss to see which one to keep. With mine, I added functionality to load a .env file as during testing I noticed insomnia process don't have access certain custom variables.

**Comment by develohpanda** [comment]
Very much related to #2593 as well, leaving both open as there is discussion in each 😊

@etauker I can see [insomnia-plugin-system-env](https://insomnia.rest/plugins/insomnia-plugin-system-env) on the plugin hub. The other one, likely doesn't show because it's quite old? Not entire sure.

@bongosway, it looks like your plugin is not published to NPM so Insomnia is not able to install it. It's awesome to see that a plugin already exists for consuming .env files! Perhaps you could update yours to be named something like `insomnia-plugin-dotenv` and focus specifically on consuming `.env` files, with the system-env one existing on its own? The plugin itself looks wonderful 😄

**Comment by bongosway** [comment]
*Perhaps you could update yours to be named something like insomnia-plugin-dotenv*

@develohpanda  This will be done today.

**Comment by bongosway** [comment]
> Perhaps you could update yours to be named something like `insomnia-plugin-dotenv` and focus specifically on consuming `.env` files, with the system-env one existing on its own? The plugin itself looks wonderful 😄

https://www.npmjs.com/package/insomnia-plugin-dotenv is now published. Please give it a test run and let me know of any bugs or enhancements

**Comment by develohpanda** [comment]
Hi @edirinIndex, I will go ahead and close this issue as it is achievable with [insomnia-plugin-system-env](https://insomnia.rest/plugins/insomnia-plugin-system-env). Please reopen or create a new issue as you see fit :)
