### ISSUE TITLE
[Bug] Schema not re-fetched until server is restarted (Ruby)

### ISSUE THREAD

**Issue by tambakoo** [getinsomnia/insomnia#1884]
Each time I make any modification in a query on the code, the schema on insomnia does not get updated until I restart the ruby server. This did not happen earlier. Earlier, it would re-fetch the schema with the introspection query without needing to restart my server.

**Desktop (please complete the following information):**
 - OS: [macOS 10.14 Mojave]
 - Installation Method: dmg]
 - App Version [7.0.6 (7.0.6.3258)]
 - Ruby 2.5.0
 - Rails 6.0.0.rc2

**Comment by filfreire** [comment]
Hi @tambakoo thank you for reporting this issue, we are going through old and unanswered issues and we're sorry for not getting back sooner! 🙇 

The app version you were using is quite old, right now we are at [version 2022.4.2](https://github.com/Kong/insomnia/releases/tag/core%402022.4.2). We would also need more details of the failure you are seeing.

If your problem was GraphQL schema fetching, you could also try the `Refresh Schema` option in there:


![Image](https://user-images.githubusercontent.com/11976836/180995199-0ef745d7-3753-4183-aa78-2b0f517e3185.png)


Feel free to open a brand new issue if you still face problems, or any other issues you come across.
