### ISSUE TITLE
[Feature Request] Create new folder from Query context-menu

### ISSUE THREAD

**Issue by mxmlnglt** [getinsomnia/insomnia#1899]
**Is your feature request related to a problem? Please describe.**
When creating a new folder, I find it rather disturbing to find it created at the top of the list. When you have plenty of queries, you have to drag&drop it down until the place you want it to be. And most of the times, I have to do this when wanting to sort my queries into... subfolders.

**Describe the solution you'd like**
What would be great is to be able to a create a new folder from the context-menu of a Query, like "Move to a new folder", and the folder would be created right at the same place as the query was before.

**Describe alternatives you've considered**
An alternative would be to create the folder (via the menu or the Shift+Ctrl+N combination) right before or after the current Query, that would avoid having to drag&drog the new folder right from the top.

**Comment by filfreire** [comment]
Hi @mxmlnglt thanks for reporting this, and sorry for not getting back to you sooner!

We have since changed a bit the way folders and requests work, so now you should be able to create a new folder inside another one:


![Image](https://user-images.githubusercontent.com/11976836/181257646-91e822e1-71d5-4f94-9be8-99468ad03125.png)

And you should also be able to run the `Create Folder` keyboard shortcut (`Shift+Cmd+N` or `Shift+Ctrl+N`) when you have a request selected, and it will create a folder on that level.

Feel free to report any other issues you come across!
