### ISSUE TITLE
[Feature Request] Edit Variable...allow me to actually edit the value of the variable, not just change variables

### ISSUE THREAD

**Issue by sturose** [getinsomnia/insomnia#1907]
**Is your feature request related to a problem? Please describe.**
I want a quick way to edit the value of a variable.  I can see the variable being used, I can click on it.  A box comes up named 'Edit Variable'...but all I can do is switch the variable, but not edit the value.
I see a Live Preview box that I can click on, but it isn't editable. 

**Describe the solution you'd like**
I'd like to be able to click on the Live Preview box and actually edit the value associated with currently selected Environment Variable

![image](https://user-images.githubusercontent.com/6200368/72927627-3cffd800-3d1c-11ea-861b-c1b258c476d8.png)

**Comment by sturose** [comment]
Is there any thoughts on the feasibility of this from a dev's perspective?  Right now, in order to edit a variable's value, I have to click 3 times, then find the element by eye inside of a json object to update it, which is quite cumbersome.

**Comment by mebius01** [comment]
I have the same difficulties. I would be glad if this functionality was present

**Comment by develohpanda** [comment]
> Is there any thoughts on the feasibility of this from a dev's perspective?

This _is_ feasible off the top of my head, but it may be fairly involved so some exploration would be worthwhile. The environment variable source (root environment, sub environment, folder) is provided, as well as the JSON path of the variable (eg. `a.nested.variable`). Another option may be to open the environment editor and highlight the variable, rather than adding edit functionality to this modal.

**Comment by ntextreme3** [comment]
After searching I kept winding up at "request chaining" issues and almost opened a new request and finally found this 😃

This is what I'm looking to do as well -- just be able to edit the environment variables in a faster way. 

> Another option may be to open the environment editor and highlight the variable, rather than adding edit functionality to this modal.

I think even if this functionality was completely separate from the modal that would be nice and solve this issue. Something like: "ctrl+click" on variable name takes you right there on the `Manage Environments` modal to edit it, bypassing the `Edit Variable` modal completely 👍

**Comment by kreosus** [comment]
Hi @sturose 
Good day and I hope that all is well. Have you tried our newest release located here: https://github.com/Kong/insomnia/releases/

**Comment by sturose** [comment]
@kreosus This still is not working as I was hoping for in the latest release.

Getting the Edit Variable dialog gives me to something like
![image](https://user-images.githubusercontent.com/6200368/194649731-ca1ad7a4-e94b-425a-ab4a-77eda6f1649f.png)



But I don't want to switch away from using the variable, I want to change the value of variable.  In order to accomplish this I need to click on the collection -> Manage Environments -> then click to the appropriate environment/base environment.

But it would be so much nicer if I could edit the value that the variable it set to within that Edit Variable dialog.

If I could edit the Live Preview and it persist to the appropriate place, that would be ideal (although renaming it from Live Preview would probably be in order).

**Comment by ntextreme3** [comment]
+1, was there some new functionality that was added to address this? I didn't see anything that looked related in the last couple bunch of release notes, and functionality on latest looks the same.

**Comment by rus-ik** [comment]
+1.

**Comment by abdulhameedinfo2** [comment]
this is very basic thing, insomia should provide. it is very difficult currently to edit the variable same the id every time you add new item then you have go the colleciton, environment and bla bla to edit that id, so that you can use this id for other collection items. this is time consuming, please provide the open box to edit the value.

**Comment by ozkit** [comment]
+1
even Postman finally added this feature as popup, it's your turn, Insomnia

**Comment by mathisgauthey** [comment]
+1, we need to be able to have for instance an `id` that would be a variable but we also need to be able to quick edit that variable. Maybe adding an edit form in the middle between the `Environment Variable` and the `Live Preview` 

![Image](https://github.com/user-attachments/assets/552651a4-6d4b-4dce-b742-4671cac81bd4)

**Comment by king-11** [comment]
I am not sure why is this request closed but definitely a useful feature.

**Comment by stephen1274** [comment]
+1 for this too.

**Comment by mathisgauthey** [comment]
I created a discussion so that the issue could live on : https://github.com/Kong/insomnia/discussions/8423

**Comment by ryanoboril** [comment]
Why is this BUG being perpetually ignored?  This is not a feature request, it is a bug, the "edit" option should allow you to modify the value of an environment variable;  there is no other context in which "Edit" makes any sense, we do not need to choose an option from a dropdown list in a context menu to change what is inside double quotes in a JSON body.  We have it right there, we can change it right there.  What we CANNOT CHANGE RIGHT THERE is the actual value of the environment variable, because the "Edit" option only shows the environment variables and lets you select a different one.  THIS IS COMPLETELY USELESS, WHAT VALUE DOES THIS PROVIDE?
