### ISSUE TITLE
[Bug] File descriptor not properly closed

### ISSUE THREAD

**Issue by NewLunarFire** [getinsomnia/insomnia#1911]
**Describe the bug**
Insomnia does not properly close the file descriptor when saving a raw response from a request.

**To Reproduce**
1. Create a new request and input a pdf in the URL field (ex: http://www.thewritesource.com/apa/apa.pdf)
2. Click 'Send'
3. Click 'Preview', then 'Save Raw Response'
4. Save the file
5. Without closing Insomnia, try to open the file in another program. You should get an error opening the document.
6 (Extra): Close insomnia, then try reopening the file. It should work properly.

**Expected behavior**
You should be able to open the file in another application after Insomnia has finished saving it to the file system.

**Screenshots**
![image](https://user-images.githubusercontent.com/10763734/73189853-13b3c300-40f3-11ea-9ce3-8998b5dd47a8.png)

![image](https://user-images.githubusercontent.com/10763734/73189831-0ac2f180-40f3-11ea-819d-2eff63381da3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Installation Method: Windows Installer
 - App Version: 7.0.6

**Additional context**
 I have only tested this for PDF file (which I then tried to open with Adobe Acrobat) but I am confident that this behaviour does not depend on content type or application used. Also, it might be a Windows-only bug.

**Comment by sc911** [comment]
Just was about to open _exactly_ the same issue. 

Can't tell since what version this problem occurs but I know for sure it was not present some versions ago (facing this issue after switching to a new machine about three weeks ago). Saving a ZIP-File from Raw-Response, served by an Asp.NET Core App (2.1.1) returned as `Microsoft.AspNetCore.Mvc FileContentResult`

Can confirm that the handle is still open after download using _Sysinternals Process Explorer_. Closing the handle from there releases the file without any side effects, so no app crash, no corrupted file.

Output of **Help->About**:

> Version 7.0.6
> Shell 3.1.13
> Node 10.2.0
> V8 6.6.346.32
> Architecture x64
> libcurl/7.57.0-DEV OpenSSL/1.0.2o zlib/1.2.11 libssh2/1.7.0_DEV

**OS**:

> Win 10 Pro
> 1909
> Build 18363.592

**Comment by kreosus** [comment]
Hi @NewLunarFire 
Do you see the same behavior with our latest release located here: https://github.com/Kong/insomnia/releases/tag/core%402022.6.0-beta.4
