### ISSUE TITLE
[Feature Request] Single Sign On Support (SSO)

### ISSUE THREAD

**Issue by m-v-k** [getinsomnia/insomnia#1999]
Really Really need Team Collaboration (the $8,- one) support for Single Sign On (we use AzureAD but any openid-connect provider should be possible).
i cannot manage 80+ developer accounts in all tooling that my company uses :(
i want to move to insomnia for all our devs, but we really need this.

**Comment by gschier** [comment]
Hi @m-v-k,

This is something we've been hearing from other large organizations as well and is something we'll be focusing on going forward.

I know this explanation won't help your current situation, but the reason Insomnia does not currently support SSO is because it uses end-to-end encrypted sync, requiring each user to have an email and password to encrypt/decrypt data. Even with SSO, users would still need to create and manage a password within Insomnia, eliminating the main benefit of SSO.

That being said, we are currently exploring other options to get around some of these high-friction points for larger organizations.

**Comment by jsalva** [comment]
For organizations, a major benefit of SSO is seamless on-and-offboarding/role change and centralized RBAC to protect company IP/secrets and enforce policies across complex IT landscape. Github has an enterprise model where users both create their own user/pass and the org can be protected by another layer of authentication via an IDP. I would recommend taking that hybrid approach to support this -- governance is a huge concern / show stopper, limiting your enterprise growth potential. This is not only a concern for large orgs but security conscious startups. Really need this or we're going to have to use a tool like postman instead, despite a large portion of the team wanting to use insomnia.

**Comment by filfreire** [comment]
Hi folks! the team is working on SSO, initially for GitHub, and soon for other platforms.

We'll provide more information as soon as possible.

heads up @subnetmarco @wongstein

**Comment by psstoyanov** [comment]
Is there a way to track the progress for this feature?

**Comment by subnetmarco** [comment]
Shipping this summer.

**Comment by gatzjames** [comment]
Closing as Insomnia is now supporting SSO!
