### ISSUE TITLE
Insomnia.Designer-2020.1.3.deb shows package information as 1.2

### ISSUE THREAD

**Issue by rmharrison** [getinsomnia/insomnia#2084]
**Describe the bug**
Insomnia.Designer-2020.1.3.deb shows package information as 1.2
I'm not sure if it's mislabeled 1.2 and is actually 1.3.
Or is actually 1.3 and the package builds are pointing to the wrong verson.

**To Reproduce**
- Ubuntu 19.10
- Download `Insomnia.Designer-2020.1.3.deb` from https://github.com/Kong/insomnia/releases/tag/designer%402020.1.3

**Expected behavior**
Should show and **be** 1.3

**Screenshots**
GUI
![Screenshot from 2020-04-29 18-37-14](https://user-images.githubusercontent.com/4275722/80653609-93ca2b80-8a48-11ea-9e67-48e4220b4fd4.png)

Command-line
```
> sudo dpkg -i Insomnia.Designer-2020.1.3.deb
(Reading database ... 398480 files and directories currently installed.)
Preparing to unpack Insomnia.Designer-2020.1.3.deb ...
Unpacking insomnia-designer (2020.1.2) over (2020.1.2) ...
Setting up insomnia-designer (2020.1.2) ...
```

About menu
![Screenshot from 2020-04-29 18-40-35](https://user-images.githubusercontent.com/4275722/80653790-ec99c400-8a48-11ea-8616-efabb4872044.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Installation Method: dpkg .deb
 - App Version Insomnia.Designer-2020.1.3

**Comment by gschier** [comment]
This was intentional. The Linux build failed for 2020.1.3 so we uploaded the 2020.1.2 binaries instead as a quick fix. The only difference between them was some fixes for the Windows installer so you're not missing anything 🙂

Going to close this issue, as it was intentional, and will be resolved with the next release.

Thanks for taking the time to report it @rmharrison 🤗
