### ISSUE TITLE
Designer snap

### ISSUE THREAD

**Issue by porozhnyy** [getinsomnia/insomnia#2089]
Hello! I wanted to install the Designer through snap, but I didn’t succeed - the site contains links only for the Core application (`sudo snap install insomnia`). Are you planning add to snap the Designer? Thank!

**Comment by rmharrison** [comment]
They're working on it. There isn't a PPA either.

For now, install latest release from `.deb` [^1]
https://github.com/Kong/insomnia/releases

```
> wget https://github.com/Kong/insomnia/releases/download/designer%402020.1.3/Insomnia.Designer-2020.1.3.deb
> sudo dpkg -i Insomnia.Designer-2020.1.3.deb
```

[^1] "About" and `dpkg` will show `v1.2` instead of `v1.3`. This caught me off-guard as well, but it's a known issue. https://github.com/Kong/insomnia/issues/2084#issuecomment-621514027

**Comment by porozhnyy** [comment]
> They're working on it. There isn't a PPA either.
> 
> For now, install latest release from `.deb` [^1]
> https://github.com/Kong/insomnia/releases
> 
> ```
> > wget https://github.com/Kong/insomnia/releases/download/designer%402020.1.3/Insomnia.Designer-2020.1.3.deb
> > sudo dpkg -i Insomnia.Designer-2020.1.3.deb
> ```
> 
> [^1] "About" and `dpkg` will show `v1.2` instead of `v1..3`. This caught me off-guard as well, but it's a known issue. [#2084 (comment)](https://github.com/Kong/insomnia/issues/2084#issuecomment-621514027)

Oh, I already installed by this method, the question about snap was due to updates

**Comment by rmharrison** [comment]
Sorry about that. Should have noticed from your doing an assignment that you're a maintainer. Derp.

That said, I strongly suspect others will be having the same issue until the main download link is updated.

**Comment by porozhnyy** [comment]
Oh, everything is fine, thanks for your attention to this problem)
Snap is nothing more than a convenient tool, and I decided to immediately ask this question to know how to proceed

**Comment by futaz** [comment]
Hey!

I think you should consider to remove the _installing via snap_ option from the [download page](https://insomnia.rest/download/designer/) because it is misleading. At least until it will be available. I've wasted some time because of that and I'm sure others will too.

Anyway, I haven't used the Designer yet but I'm sure it's a great tool so thanks for your effort!

**Comment by DMarby** [comment]
Closing this as Insomnia Designer has been discontinued and it's functionality have been merged into Insomnia, which is available to install via `snap install insomnia`: https://insomnia.rest/blog/insomnia-2021-1
