### ISSUE TITLE
Menu item for copying app info to clipboard

### ISSUE THREAD

**Issue by nijikokun** [getinsomnia/insomnia#2097]
See **additional info** [here](https://github.com/Kong/insomnia/issues/2094#issue-610168314), and maybe there are more instances of this.

Idea is that there is a menu item that when clicked will copy application details such as the version, operating system, etc... that one could paste into an issue body or comment body instead of having to manually type it out.

**Comment by MicahRamirez** [comment]
Thinking about grabbing this one if that's okay. Just to clarify what the expectation is for this... 

Adding a menu item (Copy: 'Copy Support Information' ?) on the 'Help' menu, that on click would write to clipboard the following:

1. OS Version
2. App Version
3. Shell (electron version) 
4. Node Version
5. V8 Version
6. Architecture
7.  Curl Version

As far as installation method listed in the referenced github issue, is that a requirement for this? If it is, not entirely sure where to start with that so if there are any ideas let me know otherwise I can get to researching! 

Thanks
