### ISSUE TITLE
deck sync fails with URL property

### ISSUE THREAD

**Issue by doctorwu** [getinsomnia/insomnia#2175]
**Describe the bug**
When there is a url in the declarative configuration file, we get the below error when using `deck sync`

Error: reading file: validating file content: 1 errors occurred:
	services.0: Additional property url is not allowed

**To Reproduce**
_format_version: "1.1"
services:
  - name: LCE_Order_API
    url: http://mockbin.org/request
    plugins: []
    routes:
      - tags: []
        name: LCE_Order_API-path-get
        methods:
          - GET
        paths:
          - /v1/order/(?<id>\S+)$
        strip_path: false
        plugins:
          - name: mocking
            config:
              api_specification_filename: orders.yaml
    tags: []
upstreams:
  - name: LCE_Order_API
    targets:
      - target: mockbin.org:80
    tags: []

**Comment by nijikokun** [comment]
Thanks for raising this @doctorwu 

I [previously mentioned](https://github.com/hbagdi/deck/issues/123) this on the deck repository and @hbagdi [implemented a fix](https://github.com/hbagdi/deck/commit/1d9a915c117f58ead7113570f380c8a996ef81f6).

Can I ask what version of deck you are using? 

I ask this because [v1.0.1](https://github.com/hbagdi/deck/blob/master/CHANGELOG.md#v101---20200214) contained the fix

**Comment by doctorwu** [comment]
Aha!

decK v0.7.2 (5d9aa56)
