### ISSUE TITLE
Git checkout branch, pull and reset operations don't update the spec editor properly

### ISSUE THREAD

**Issue by develohpanda** [getinsomnia/insomnia#2244]
Related to #2224, which fixes this case for checking out a branch, but a more robust solution is needed for other git cases which will show the same behavior.

Possibly use react context to trigger different sections of the application to update on git operations, and to share the gitVCS object.

The current workaround is to force an update, by going to the dashboard and opening the document again.

**Comment by filfreire** [comment]
While triaging this with @kreosus we found this issue is still applicable. We also noticed something:

When pulling a branch, it seems we do update the Preview of a spec according to the branch:
For example, pulling one branch with changes:
![002](https://user-images.githubusercontent.com/11976836/175304626-6720da7d-002f-4f9f-b6d7-2a4ab208d00a.png)

And pulling back the main branch:
![001](https://user-images.githubusercontent.com/11976836/175304634-b90f8907-c633-417e-add3-210698a3439b.png)

Perhaps this can be solved somehow applying the same update we are doing already for `Preview` inside the code editor.
