### ISSUE TITLE
HTTP headers being lowercased when sent to https server

### ISSUE THREAD

**Issue by bluntelk** [getinsomnia/insomnia#2245]
**Describe the bug**
I have a HTTP Header I am using for authentication. It has capital letters in it, like so X-Blah-Token

When sending to a https URL (either direct or via redirect) the HTTP header is lowercase: x-blah-token - this causes auth to fail.

It works find on HTTP servers

**To Reproduce**
1. Setup an environment and configure it with ```json
{"interconnect": {"api-key": "a-string-of-characters", "host": "https://your.server/api"}}```
2. add a new API using our variables to: POST ```[interconnct.host]/some/endpoint```
3. add a HTTP header: `X-Blah-Token` with the value of ```[interconnect.api-key]```
4. run the request, see in the timeline that the header being sent is lowercased

**Expected behavior**
the header key is not being lowercased

**Screenshots**
![Screenshot_20200603_141945](https://user-images.githubusercontent.com/203695/83602740-bb5f6700-a5a5-11ea-8ac2-f91301295a8d.png)

**Desktop (please complete the following information):**
 - OS: KDE Neon (which is based on Ubuntu 18.04)
 - Installation Method: [snap and appimage]
 - App Version: snap v7.1.1 and appimage 2020.2.1

**Comment by JCMais** [comment]
Just want to point out that according to RFC2616, section 4.2 header names must be case-insensitive, so if you server is not working correctly, it's not spec-compliant. 

https://www.ietf.org/rfc/rfc2616.txt

**Comment by bluntelk** [comment]
> Just want to point out that according to RFC2616, section 4.2 header names must be case-insensitive, so if you server is not working correctly, it's not spec-compliant.
> 
> https://www.ietf.org/rfc/rfc2616.txt

I am sure I have known and then forgotten that at some stage!

I can however argue that being inconsistent with sending the header field names is more of a bug than a feature.

You can also argue for a new robustness testing feature where the case of field names is altered on every request (with a special note about it in the timeline)

**Comment by gschier** [comment]
It looks like `libcurl` lowercases headers by default for HTTP/2 because HTTP/2 headers *must* be lowercase. 

https://http2.github.io/http2-spec/#HttpHeaders
https://stackoverflow.com/questions/54067796/preserving-case-of-http-headers-with-curl

Perhaps Insomnia should have a way to force HTTP 1.1 usage

---

I definitely agree that Insomnia should send exactly what the user specifies where possible, since it would be useful to send upper-case headers for debugging.

**Comment by OgawaTakasi** [comment]
I need to use such upper-case header names, so I chose Insomnia.
Because the running API behaves as case sensitive.
But recently I was surprised Insomnia corrects header names as lower cases.
Which version doesn't correct header names? I want to rollback to that old version.
Or can I expect the reverting this feature?

**Comment by shellscape** [comment]
FWIW AWS Lambda does not provide headers lowercased (and has no intention of modifying that behavior). Although I would consider that incorrect, it is what it is for a large swath of users.

**Comment by shellscape** [comment]
@gschier which version is this landing in? I'm up to date on the regular channel and don't see this feature yet.
