### ISSUE TITLE
[Improvement] Password in Environment Variables

### ISSUE THREAD

**Issue by bkonia** [getinsomnia/insomnia#229]
I created an environment variable, "password" to store a password for Basic Authentication. In the Basic Auth settings, it allows me to enter a variable for the username, but the password field does not seem to recognize variables.

I get that it's not a good practice to store passwords in plain text, but if the user wants to take the risk, Insomnia shouldn't get in the way. Also, in the environment variables web page, it shows an example of storing an API key, which is essentially the same thing as storing a password.

In my case, I'm working with an API that uses Basic Auth and there are tons of different methods, so it would be cumbersome to have to enter the password each time, and update each one manually, whenever the password changes.

**Comment by gschier** [comment]
hi @bkonia. A variable would still work with the raw template syntax (`{{ password }}`) but I agree that this is not ideal. As of 5.0, this template syntax is no longer user-facing so it is not intuitive. 

As a temporary workaround, you can flip the "Show Passwords" toggle in the app's settings but there should probably be a better way.

## Potential Solutions

- Figure out a way to passwordify (hide text) in the regular Codemirror-based input field (difficult)
- Add an inline button to password fields to toggle back and forth (instead of using the hidden option in setting) (easy)
