### ISSUE TITLE
Some team members cannot see certain workspaces when shared

### ISSUE THREAD

**Issue by dmeunier** [getinsomnia/insomnia#2302]
We meet some workspace synchronization problems inside our development team. We are working with "version control beta". Some of the workspaces are successfully shared but other developers cannot see them in the remote workspace list.

**To Reproduce**

1. Create workspace
2. Create and Push Snapshot
3. Share with "Boxtal Developers"

We are all developing on Linux Operating Systems and we are all up to date (Insomnia 2020.2.2).

**Comment by DMarby** [comment]
Hi @dmeunier,

We just released [2020.4.2](https://insomnia.rest/changelog/core/2020.4.2) which contains a number of fixes for issues related to the version control beta sync, including this one.

Please give it a try, and if you're still having issues, send us an email at support@insomnia.rest so that we can best assist you with these issues!
