### ISSUE TITLE
How to sort folders in the left hand pane

### ISSUE THREAD

**Issue by wesleyjconnorsesame** [getinsomnia/insomnia#2340]
**What is your question?**
I have alot of folders in insomnia one for each microservice and we have 50+, I have created the folders as I needed them and I now find it very hard to find for instance 'search-service' because it is not alphabetical
Is it possible to sort them by name?

**Comment by wongstein** [comment]
Hello @wesleyjconnorsesame !  I know you left this question awhile ago.  The App has changed a lot since then and I believe we have sorting of Folders.  I tested this on the latest build (2022.4.2), and was able to find a folder via the left pane search bar (see attached image).  I suggest giving it a try and seeing if it fits your needs!


![Image](https://user-images.githubusercontent.com/12381507/181040463-0c96ce0e-7ceb-4bf9-a215-c7b7cdf19e47.png)

**Comment by wongstein** [comment]
I'm going to close this issue from now, but feel free create a new issue if you come back and still find this problem in the latest Insomnia version
