### ISSUE TITLE
Allow escaping a specific double curly braces entry in body

### ISSUE THREAD

**Issue by sgautrin** [getinsomnia/insomnia#2355]
This is somewhat related to issue #1415 as it targets the same mechanism.

Currently with the settings highlighter as an answer to #1415, you either have the possibility of using variables in your body or you have the possibility to input litteral double curly braces. This is limiting as when you need the litterals, you're locked out of also being able to use environment variables.

My context is creating spark jobs on databricks with their API ([databricks API doc](https://docs.databricks.com/dev-tools/api/latest/jobs.html)), while specifying spark configuration referencing databricks secrets (the format of which being `{{secrets/<scope_name>/<secret_name>}}` (see [databricks docs on secrest in spark conf](https://docs.databricks.com/security/secrets/secrets.html#store-the-path-to-a-secret-in-a-spark-configuration-property)), while having the ability to specify some of the body based on the environment, like for example the `instance_pool_id`.

Using version 2020.2.2 I could not find a way to have both.

Ideally there would be a syntax to either escape double curly braces when “skip rendering of request body” is not checked, or to input an environment variable in body when “skip rendering of request body” is checked.

**Comment by develohpanda** [comment]
Do Nujucks [Raw](https://mozilla.github.io/nunjucks/templating.html#raw) tags suit your purpose?

![image](https://user-images.githubusercontent.com/4312346/113256195-55f31880-9325-11eb-8c73-14f85e96f3e1.png)

The header value I have in the screenshot above is `{% raw %}{{ _.var }}{% endraw %}`, and I have an environment variable called `var` which is being ignored because of the raw tags.

Works in the body as well 
![image](https://user-images.githubusercontent.com/4312346/113256423-a9656680-9325-11eb-9b52-133dba1d21a7.png)

**Comment by sgautrin** [comment]
Yes this is exactly what was needed, and it was there all along. Thank you.

**Comment by develohpanda** [comment]
Excellent! Will make sure to document this. I learned something while researching a related feature request 😄
