### ISSUE TITLE
How can I send `withCredentials` in a post request?

### ISSUE THREAD

**Issue by edalzell** [getinsomnia/insomnia#2393]
I need to set `withCredentials` to true for a request, how can I set that in Insomnia (macOS)?

Thanks

**Comment by nijikokun** [comment]
Welcome 👋 

Since Insomnia uses CURL for it's networking, we don't deal with CORS / XHR type requests which is what `withCredentials` is for. Instead here are four different ways you can send credentials in Insomnia (assuming normal authentication methods):

You can choose an authentication mechanism from the "Auth" dropdown in a request.

![image](https://user-images.githubusercontent.com/198276/87208414-8391c080-c2c3-11ea-9554-eb7303061064.png)

You can create a Cookie, by clicking "Cookies" (located next to environments in the sidebar) and adding your authentication token / cookie value here which will be sent along with any request to the domain specified.

![image](https://user-images.githubusercontent.com/198276/87208425-8d1b2880-c2c3-11ea-924a-b968322fe610.png)

You can set the expected authentication header value using the Headers menu under the Request pane.

![image](https://user-images.githubusercontent.com/198276/87208489-ba67d680-c2c3-11ea-9989-315f9f7855a4.png)

Or, you could send your authentication value in the body should the server allow it.

![image](https://user-images.githubusercontent.com/198276/87208515-cfdd0080-c2c3-11ea-9d30-dd2259943102.png)
