### ISSUE TITLE
When the user switches to "RAW DATA" viewing mode in a binary file, insomnia crash.

### ISSUE THREAD

**Issue by VitorSantosCruz** [getinsomnia/insomnia#2397]
1. Create a request for an api that responds with a binary file (PDF, ZIP).
2. Switch from "visual preview" mode to "row data" mode.

Screenshots
![image](https://user-images.githubusercontent.com/33767387/87244709-7e448b00-c415-11ea-846e-9d112e1b539a.png)

**All functions of the Insomnia crashes, nothing works**
![image](https://user-images.githubusercontent.com/33767387/87244722-b0ee8380-c415-11ea-8d29-bb5f9dc4ce5d.png)

Description
When the answer files are deleted, the insomnia will work again

Info
 - OS: Windows 10
 - App Version: v8 6.6.346.32

**Comment by aszx87410** [comment]
I can reproduce this issue and I found that it's not actually crash but just very slow. It takes lots of time to load huge file. I have tried smaller file (~100 KB), when the raw data gets loading, the app became unresponsive, I think it's because loading huge raw data block main thread.

There are two solutions came to my mind, first one is we can set textarea by chunk, split huge raw data in pieces and load inside `requestIdleCallback`  or `requestAnimationFrame` callback to prevent blocking the main thread. Another solution is, replace textarea with `CodeEditor` component, because `codemirror` already handle this part.

I am willing to try the second solution first and work on this issue.
