### ISSUE TITLE
Remove usages of @autobind to allow for react-hot-reloading to work

### ISSUE THREAD

**Issue by develohpanda** [getinsomnia/insomnia#2468]

**Comment by MrSnix** [comment]
Is this still requested?

If so, what should we do in order to deliver it?

Considering the removal of the `@autobind` decorator and its import, transforming all the functions to arrow functions should solve the .bind() problem. Isn't it? 

**EDIT:**
I was able to perform the transformation from `common function to arrow function` on all the classes using auto bind inside the project, then I successfully removed the decorator and its declaration from the insomnia-app & insomnia-component and it's running like before. Here is a branch on my fork with the transformation: [tech-debt/remove-autobind](https://github.com/Kong/insomnia/commit/4506984e9c1160e45e6976f4efa0f933256f21cd)

Let me know if it can be helpful or I am missing something.

**Comment by develohpanda** [comment]
This _is_ still requested but using arrow functions to replace the `.bind()` is not as clear-cut a solution as it may seem at first sight. Depending on the implementation, arrow functions will be recreated on each render and sent via props to child components. Even if the function implementation does not change, React will detect it as a prop change and cause a re-render. To my understanding, this is generally discouraged because it is inefficient.

I need to put some more thought towards the approach but haven't been able to yet.
