### ISSUE TITLE
[Feature] Support to import/convert/parse json to form fields

### ISSUE THREAD

**Issue by joubertredrat** [getinsomnia/insomnia#248]
Hi guys,

Yesterday I received a big json with 30 or 32 fields and I needed to make one POST request with  Content-Type `application/x-www-form-urlencoded`. I copied and pasted all fields into form for make mine request but with this I had an idea.

I think that is good idea to have support to parse one json into fieds, like example below:

1 - I have this json 
```json
{
  "from": "Me",
  "to": {
    "name": "You",
    "email": "your@email"
  },
  "subject": "foo",
  "message": "bar"
}
```
2 - I open a option to parse this json into fields, paste json and confirm.

3 - Done like image below:
![screenshot at 16-57-08](https://cloud.githubusercontent.com/assets/1520407/26422949/199fdbd6-40a2-11e7-8e35-f553ec7ee94a.png)

I think that is good idea if you have big json and your endpoint support only `application/x-www-form-urlencoded` or `multipart/form-data`.

What you think guys?

**Comment by gschier** [comment]
Hey @joubertredrat. Sorry for the delayed response on this one. In my opinion, this feature is too use-case specific and subjective to be supported by Insomnia. It would be much better suited for a plugin once a plugin framework exists (#51).

Since form-data only supports strings, it would be impossible to convert JSON to form-data without losing information. There is also no defined standard for representing nested objects and arrays in form-data, so it's possible that the resulting form-data will not work for all web frameworks.

_this is similar to #295_

**Comment by jpresutti** [comment]
I ask you to reconsider.  It actually makes perfect sense to allow importing of **simple** JSON objects as long as there is no nesting. This would save my sanity right about now where I instead have to manually type out every single part.

**Comment by hardeaux** [comment]
oh man - same here ;) 
++

> I ask you to reconsider. It actually makes perfect sense to allow importing of **simple** JSON objects as long as there is no nesting. This would save my sanity right about now where I instead have to manually type out every single part.

**Comment by mindaugasbudreika** [comment]
I'm also very interested in this feature.
