### ISSUE TITLE
Exception does not contain spaces

### ISSUE THREAD

**Issue by lrweck** [getinsomnia/insomnia#2506]
**Describe the bug**
I'm using java to develop a webservice and when I throw an exception it returns the correct response code, however the message does not contain spaces.

**To Reproduce**
1. throw exception that contains spaces in its messages in the app

**Expected behavior**
The returned message should contain spaces.

**Screenshots**
Insomnia:
![image](https://user-images.githubusercontent.com/26086198/89966041-a138a980-dc24-11ea-8f24-788c445ffa2d.png)

Postman:
![image](https://user-images.githubusercontent.com/26086198/89966066-b31a4c80-dc24-11ea-85a9-d4f3c258aa8b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Installation Method: Chocolatey
 - App Version: 2020.3.3

**Comment by githubcansuckmypenis** [comment]
I am having the same issue as you do.
A temporary workaround is to switch from Visual Preview to Raw Data in the right panel, at the top.

**Comment by murilokprado** [comment]
Hi, I'd like to try to do this, would I?

Can you send me the webserver? @lrweck

**Comment by cobwebsonsale** [comment]
The problem isn't really about exception messages. It happens on success too:
<img width="820" alt="Screenshot 2020-10-22 at 8 25 23 PM" src="https://user-images.githubusercontent.com/1848127/96890251-1803e580-14a5-11eb-9c21-f9a7ecf152a7.png">

This is happening because an incorrect header is set (`application/json`) by the server when the response isn't a valid JSON. The issue gets resolved if either the header is set properly (`text/plain`):
<img width="846" alt="Screenshot 2020-10-22 at 8 26 42 PM" src="https://user-images.githubusercontent.com/1848127/96890493-513c5580-14a5-11eb-9194-21bb57a4215a.png">

or if the response is sent as a valid JSON:
<img width="828" alt="Screenshot 2020-10-22 at 8 26 03 PM" src="https://user-images.githubusercontent.com/1848127/96890572-61543500-14a5-11eb-9e7c-ff5efcdef182.png">

The spaces are removed by insomnia-prettify's [json.js](https://github.com/Kong/insomnia/blob/bd4ed35dab63a91b55384fe7c36029589e6cc7ae/packages/insomnia-prettify/src/json.js#L144-L149) because it does not expect spaces outside a string. Unsure if this behaviour should be changed, or if users should be expected to supply the correct header.

**Comment by johanhammar** [comment]
A simple (and maybe naive) solution is to only prettify the response if it's valid json otherwise display the response as is. However, it seems like insomnia-prettify prettifies json with trailing commas (which is not valid json), see [trailing-comma-input.json](https://github.com/Kong/insomnia/blob/develop/packages/insomnia-prettify/src/__fixtures__/trailing-comma-input.json).
