### ISSUE TITLE
Allow pulling / pushing to repositories with existing content

### ISSUE THREAD

**Issue by nijikokun** [getinsomnia/insomnia#2525]
**Is your feature request related to a problem? Please describe.**

Unable to publish or pull from repositories with existing content on initial setup of Git Sync in Insomnia Designer. When attempting to connect to a repository that already contains content such as a readme, a user will run into the error dialog detailing that they cannot pull or push depending on the action taken.

**Describe the solution you'd like**

Configure and publish to a repository with existing content.

**Describe alternatives you've considered**

Currently, the only way to connect git sync is to use a completely clean repository, or an existing insomnia designer repository.

**Additional context**

![image](https://user-images.githubusercontent.com/198276/90441307-969b6b80-e08d-11ea-9ce4-cb7c3ac10c17.png)

**Comment by dselans** [comment]
Hi folks, any update on this?

My current workaround for syncing API spec with an existing repo (using github):

1. Import spec via file
1. Create a temp repo
1. Setup git sync in Insomnia Designer with new repo
1. Commit and push to temp repo
1. Clone temp repo
1. Grab `.insomnia` dir from temp repo and move to your existing repo
1. Commit and push in existing repo
1. Open Insomnia designer and create new spec by importing from existing repo

^ I'm sure there's a simpler/quicker way, but this worked first try 🤷

**Comment by mxmlnglt** [comment]
Hi, any news regarding this?

Also I encountered something related which might be related:
I started with an existing repo but with a brand new branch (didn't know of the issue above), commit, push. Everything went fine at the time.

Then I recently (1 month later) switched to my regular /develop branch where I have the rest of the project (Java code, and I use Eclipse IDE) so my repo now includes some hidden files/folders like .project or .settings or "target".
Now switching back to my "spec-only" branch these files & folders are considered new & unstaged because there isn't any .gitignore file.
I managed to commit new changes I made to my OpenAPI spec file but I don't see the commit, and I can't even push because I get this error:

![image](https://user-images.githubusercontent.com/29626929/109284434-2467c880-7820-11eb-8973-6100cbe78c56.png)
