### ISSUE TITLE
Is it possible to have a private base environment?

### ISSUE THREAD

**Issue by rbrianhazzard** [getinsomnia/insomnia#2540]
**What is your question?**
The documentation [here](https://support.insomnia.rest/article/18-environment-variables) under `Sub Environments` specifies that you can mark a sub-environment as private. Is this possible with base environments?

**What is the context?**
If I export a workspace to source control, I'd like to have a private environment with variables like "me" and "password" for authenticating. That way I could share this workspace with teammates, who have a similar (but different 😁) "me" and "password" defined.

Thanks!

**Comment by nijikokun** [comment]
Unfortunately, at this time, it is not possible to mark your base environment as private. It seems like you're already aware of private sub-environments, which should be used for this functionality.

It would be nice to have required variables that don't get set, not sure what the expected workflow or usage would look like in that scenario, any thoughts? Since it would require user engagement on sync.

---

Note, currently this is resolved on a gradual introduction, when someone syncs and there is a variable missing they will have to add it, either to a private environment of their own or a public one, ideally they keep the same train and use private environments. We might need more thought around how to enforce certain variables as private.

**Comment by rbrianhazzard** [comment]
My initial thought was to just have a "Base Private Environment". This doesn't work right now since I'd have to select the private environment in place of the sub-env I actually want to use

For Example:
![image](https://user-images.githubusercontent.com/45824358/90914258-965fe080-e3ab-11ea-8d47-6f848c262c3c.png)

The idea being I can flip `Staging` and `Prod` while falling back to a private base environment that has my `username` and `password` defined

**Comment by nijikokun** [comment]
Yeah, we currently don't support the functionality in the way that you describe so it'd be a feature request, allowing users to have a private base environment.

Currently, you'd have to swap between two private sub-environments.

**Comment by rbrianhazzard** [comment]
Got it, thanks!
