### ISSUE TITLE
Unit Testing > UI Lag

### ISSUE THREAD

**Issue by sonicyeti** [getinsomnia/insomnia#2562]
**Describe the bug**
When multiple test suites exist, each containing multiple tests the Unit Testing UI is slow to initially render.

**To Reproduce**
See replication steps [here](https://github.com/Kong/insomnia/issues/2562#issuecomment-681013144).

**Expected behavior**
Near zero lag.

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/52717970/91326481-64c38c80-e792-11ea-8219-b01423f8ca46.png)

**Comment by nijikokun** [comment]
Reproduction is now possible:

1. Create two unit testing suites
1. Add 20+ unit tests to each suite
1. Use a code block longer than five lines for more than half of the unit tests (see example below)

Now when switching between test suites, or between debug and test, there is noticeable lag of around 3-10 seconds (see attached performance test).

![image](https://user-images.githubusercontent.com/198276/91335393-2c698180-e785-11ea-9b0a-cb7f51406afd.png)

**Example unit test code block to replicate:**

```js
const response1 = await insomnia.send();
expect(response1.status).to.equal(404);
const response2 = await insomnia.send();
expect(response2.status).to.equal(404);
const response3 = await insomnia.send();
expect(response1.status).to.equal(404);
const response4 = await insomnia.send();
expect(response1.status).to.equal(404);
const response5 = await insomnia.send();
expect(response1.status).to.equal(404);
const response6 = await insomnia.send();
expect(response1.status).to.equal(404);
```

---

This indicates that the issue is related to the CodeMirror instantiation logic. We have a few options to explore with this and are defined below:

1. Make editors collapsible, collapsed by default, with the first open.
  - Concerns to be addressed:
    1. Should the application remember editor open state while swapping between panes / test suites?
    1. Should the application support keyboard navigation and keyboard actions (up / down, and space to open/close)?
    1. What should the indicator be? Arrows or plus / minus, and a darkened background to indicate close status?
2. Improve performance
3. Activate editors on click, only if there’s an easy way to do it.
