### ISSUE TITLE
Allow customizing curl DNS cache timeout

### ISSUE THREAD

**Issue by iandunn** [getinsomnia/insomnia#2606]
### Problem

#1529 describes how libcurl reuses connections for `60` seconds by default. Because of that, switching between local and production hosts is inconvenient, if they share the same hostname.

Setting a `Connection: close` header doesn't seem to help.

It seems like the way to modify that cache is with the [`CURLOPT_DNS_CACHE_TIMEOUT`](https://curl.haxx.se/libcurl/c/CURLOPT_DNS_CACHE_TIMEOUT.html) option. There doesn't seem to be a way to modify that in Insomnia, so I just have to wait 60 seconds each time I switch environments.

### Ideal solution

What about introducing an environment variable that would pass the value along to `CURLOPT_DNS_CACHE_TIMEOUT`? That would let people set it to `0` if they want to disable the cache, or `120` if they want to extend it, etc.

Setting it per-environment would be good, since some environments can share hostnames while others don't.

### Alternate solution

Allow plugins to set `CURLOPT_DNS_CACHE_TIMEOUT`.

cc @AdityaHarindar, @Shawyeok

**Comment by iandunn** [comment]
Still a problem.

**Comment by Shawyeok** [comment]
Multiple environments (qa/stage/production etc) share a same domain name will met this problem.
@iandunn 
I found a workaround, here it is:

**Send request with ip address instead of domain name, put domain name into `Host` header.**

![image](https://user-images.githubusercontent.com/5058708/120278684-2b531b00-c2e8-11eb-84bf-94ca10839873.png)
![image](https://user-images.githubusercontent.com/5058708/120278730-3908a080-c2e8-11eb-8936-43e99b4a2fff.png)
![image](https://user-images.githubusercontent.com/5058708/120278756-4160db80-c2e8-11eb-9665-6cba56e6fdf7.png)

**Comment by iandunn** [comment]
Thanks @Shawyeok. I tried that, but I still get SSL errors. It looks like you're using `http` rather than `https` in your screenshots.

Maybe your server is setup to accept both? Mine redirects `http` to `https`.

**Comment by Shawyeok** [comment]
> Maybe your server is setup to accept both? Mine redirects http to https.

Yes, we still use `http` protocol for most internal apis.

> but I still get SSL errors.

You can disable `Validate certificates` in preferences if that's ok for you.

Now `Validate certificates` setting is effect for entire application, maybe add it in per request settings is more convenient.

**Comment by iandunn** [comment]
I need to use HTTPS locally to test code that relies on SSL.

I can't disable cert validation because that would be a significant security problem. Even disabling it for a single site would be a problem in situations where production and local environments share the same hostname.
