### ISSUE TITLE
Add insomnia V4 import support to Insomnia CLI

### ISSUE THREAD

**Issue by abbasc52** [getinsomnia/insomnia#2666]
**Unable to use insomnia designer export with CLI**
I am planning to use the inso cli to integrate with CI. I don't plan on create a separate git repo and would like to use it along with my existing repo.

**Importing insomnia export in the CLI**
If the cli can import the insomnia_export file and create the .insomnia folder or directly run it , that can simplify using inso for CI

**Comment by develohpanda** [comment]
Insomnia Designer can certainly sync with an existing repo, co-exist with other files. There are some edge cases that we need to work through, but the intention is for your code and Insomnia Designer data to co-exist. The `.insomnia` folder format is a little nicer to review changes for, because each model exists as a standalone file in a particular folder structure. 

Would that suffice as a long-term solution?

I'm saying that, I do agree that consuming the v4 export format as a data source for inso is an entirely valid request as well, and we had talked about it in the past but had not implemented. This would be a great short term solution, and it shouldn't be too challenging as the data structures used by the app and inso are very similar. 

Also, I'd love to understand what your intended workflow is, and maybe what your _ideal_ workflow would be. I'm assuming you have a manual process to export the v4 format file and place it in your repository?

**Comment by abbasc52** [comment]
@develohpanda you are right having `.insomnia` folder would we ideal for a long term solution. But the current challenge i am facing is essential exporting the designer data to a local folder which can be directly accessed by CLI. It would also work if insomnia designer can create `.insomnia` folder via export data feature. Although we plan on maintaining versioning for the data, we would prefer handling it ourselves as it gives us more freedom

**Comment by develohpanda** [comment]
Great point about the freedom it provides, keen to explore that as you further implement your workflow. Perhaps inso can be extended with some export functionality.

What is your reason for needing a local folder containing designer data for inso?

Running inso locally, it should detect the app data folder for Designer, and work seamlessly. (And running inso in CI, it would detect the `.insomnia` folder and use that automatically.) 

Could there be something I'm missing, in that it's _not_ detecting your local app data folder?

**Comment by abbasc52** [comment]
@develohpanda let me explain my scenario:
We have our API project and we plan to run tests on CI
We also have some strict rules where we can't check in any credentials.
So currently we use postman and export the collection to our repository and run newman(postman cli) for our CI tests.

I am planning to replace it with insomnia designer + inso but having trouble with exporting it and running it on CI
Essentially if i could locally export the tests, i can push it to whichever repository i want. Also as i mentioned, we are little skeptic of giving a tool credentials to check in code on our behalf.

**Comment by develohpanda** [comment]
Totally makes sense. Thanks for explaining your workflow, that's very insightful! 

I'll add some notes to this issue (when on computer) around how to add v4 support to inso 👍

**Comment by develohpanda** [comment]
For anybody looking to pick this up, it is a matter of adding a new adapter [here](https://github.com/Kong/insomnia/tree/develop/packages/insomnia-inso/src/db/adapters) for the Insomnia V4 export format, returning a database object in this format: https://github.com/Kong/insomnia/blob/19a9d6a7e7925afa8285a76972f32bc2dc0f8c2c/packages/insomnia-inso/src/db/index.js#L17-L25

An update will be required to `loadDb` in order to consume the new adapter: https://github.com/Kong/insomnia/blob/19a9d6a7e7925afa8285a76972f32bc2dc0f8c2c/packages/insomnia-inso/src/db/index.js#L48-L52

There will also need to be a global option to specify the export file: https://github.com/Kong/insomnia/blob/19a9d6a7e7925afa8285a76972f32bc2dc0f8c2c/packages/insomnia-inso/src/cli.js#L171-L178

The new option will need to be configurable via a config file: https://github.com/Kong/insomnia/blob/19a9d6a7e7925afa8285a76972f32bc2dc0f8c2c/packages/insomnia-inso/src/get-options.js#L21-L27

There are lots of unit tests set up, so please add to them as well. 😄

**Comment by Aconitin** [comment]
I'm having the same issue(s) - I'd like to use an existing Insomnia Export (with all the tests in it) to run CLI tests with, but inso doesn't allow importing that.
