### ISSUE TITLE
Having an env var point to an attribute of either of multiple responses

### ISSUE THREAD

**Issue by AmirShitrit** [getinsomnia/insomnia#2683]
My problem is that I'm trying to test a paging endpoint where paging is done using a continuation token (as opposed to using skip and limit params). In this scenario, requesting the first page not only returns the results, but also a token pointing to the next page. The second page will be requested using the token retrieved from the previous response.
Today, if I want to iterate through N pages, I'll have to create N distinct requests, each retrieving the token from its predecessor.

The solution I'm suggesting, is to have an env var point to response X's attribute and to fallback to response Y's attribute if X hasn't ran yet (being the second/third/... page and Y being the first page).

An alternative would be to enable running custom scripts.

**Comment by develohpanda** [comment]
Because Insomnia uses Nunjucks templates, you can do conditionals as part of a template. Note, the tag for the `resolved` variable is simply `{{ first or second }}`.

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/4312346/94858596-c5c83980-048f-11eb-8b1c-d5db5006e074.png">

This _somewhat_ works though. If `first` cannot find the token, it actually returns an error rather than a blank/falsey result, so the condition itself doesn't work exactly - some further investigation needed there.

If `{{ first or second }}` worked as expected here, would it satisfy your use case?
