### ISSUE TITLE
[Bug] Beautify JSON doesn't respect environment vars unless quoted

### ISSUE THREAD

**Issue by jc21** [getinsomnia/insomnia#271]
## Overview
- `Insomnia Version:` _5.0.20.162_
- `Operating System:`  _MacOS 10.12.5_
- `Summary: ` _Beautify JSON doesn't respect environment vars unless quoted_

## How To Reproduce
1. _Create new request with a JSON body_
2. _Insert an environment var like so:_
```
{
    "list_id": {{ list_id }}
}
```
3. _Click Beautify JSON_
4. _See that the beautifier has treated the curly braces of the env var as json instead of ignoring them:_
```
{
	"list_id": {
		{
			list_id
		}
	}
}
```

## Other Notes

It's annoying more than anything. As JSON is a strict format I use integers and booleans in my env vars and I cannot treat them as strings in my JSON payloads.

**Comment by gschier** [comment]
This issue is a fairly difficult one and requires two changes.

1. modify the `prettifyJson()` function ignore Nunjucks tag syntax. This shouldn't be too difficult, but I can't think of an elegant way to implement it off the top of my head.

2. write a custom `json` mode for Codemirror so that the syntax highlighting also ignores Nunjucks tags. I don't have any experience in this area but I'm sure it's possible.
