### ISSUE TITLE
Use response tag as a default value for a prompt

### ISSUE THREAD

**Issue by cbejensen** [getinsomnia/insomnia#2722]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to chain my commands together using response variables, but other times I just want to use one of the commands in that chain real quick with a prompt. For example, I have a create user command followed by a get user command that pulls the created ID from the create user command. However, sometimes I want to get a user with an ID I already have in my clipboard. To solve this, I've been creating two entires in insomnia for most endpoints - one that uses a response variable for chaining, and one that uses a simple prompt. But this is not fun to maintain.

**Describe the solution you'd like**
It would be nice if I could avoid duplicating entries by having the default value of a prompt be a response variable from another command. To use the previous example, the get user command could use a prompt, but the default value of the prompt would be the ID from the create user command.

I realize that this opens some questions, such as what to use as the default for the next get user command after pasting a custom ID. Should it be the response variable still or the last used value (the pasted ID)? 🤷‍♂️  But I wanted to at least get this idea out there.

Thanks for taking the time!

**Comment by Kaitachi** [comment]
Hey there! I'm quite frankly a novice to this product and began lurking around the repo to check out comments related to features.

Have a question regarding your setup: do you need to send these parameters (User ID and others) as query parameters or as part of the URL itself? That is, do you query for a specific user with a syntax similar to `api/users?user_id=7` or `api/users/7`? Depending on your specific scenario, Insomnia may have a solution that could help you out.

This is a solution that works with the first request structure: I've noticed that there are these checkboxes next to each query parameter when configuring your endpoint request (in the Query tab). You could add two parameters with the same in this section, one with a static ID and another with an ID supplied by a tag. After adding both of these parameters, you can then uncheck the parameter that you wouldn't want to send and only keep checked the ID corresponding to the scenario you want to test. It might be better explained with images, so you'll find an attachment with a sample screenshot.
<img width="1392" alt="Screen Shot 2020-10-30 at 12 15 19" src="https://user-images.githubusercontent.com/824487/97730024-b1388a80-1aa9-11eb-947c-9c25382df1ed.png">

You'll see that I circled in red the checkboxes I'm talking about. And in that example, I've set up the parameter `postId` twice: once with a fixed version that I could change on-demand and another with an environment variable that is currently set up to `7`. If you notice in the URL Preview above it, the URL only shows `?postId=7`, since it's the parameter that's enabled to send. Now, when I check the first parameter only (making sure to uncheck the second parameter), the URL changes to `?postId=1`, reflecting the ID for the selected postId.

Regarding the second convention for querying data, the one that would use a URL scheme similar to `api/users/7`, I wouldn't be able to tell if it's possible to perform at the moment with Insomnia. It would be pretty neat to see how it works, if at all.

If I'm understanding correctly from your scenario, it seems like my suggestion above would be a viable solution (or at least work better than having two endpoints that serve pretty much the same purpose). So I'm hoping this at least leads you in a good way.

**Comment by cbejensen** [comment]
Thanks @Kaitachi for the feedback! I am using the second convention you described, so unfortunately that won't work for me. In other words, a get user command might look like this:

`users/Prompt`

where `Prompt` is the usual Insomnia template tag. And the feature being requested (which you seem to understand but I'll reiterate here for others) is to enable a default value of the `Prompt` template tag that points to a value in a response from another call. As it is, you can assign a default value, but you can't use a dynamic value like you can with the `Response` template tag.

**Comment by Kaitachi** [comment]
Ah, it's a bit sad to see the example I illustrated won't fit neatly for your scenarios, @cbejensen. 🙁

Have been experimenting a little bit more with Insomnia after reading your last post a couple of times, and I now understand the `Prompt` template tag you were referring to -- I honestly didn't know of it, for it was just this morning that I first heard of Insomnia and downloaded it... 😛 Anyways, after reading up on #2664 (wasn't too helpful but they address the same deal of having parameters as part of the URL path) and some [documentation on Environment Variables](https://support.insomnia.rest/article/18-environment-variables), and reading your posts a couple more times, I think now I may have a bit of a grasp as for how to solve this issue when the query parameters are parts of the URL path.

Haven't formally tested this with a system that would create records per se, but this seems to be quite promising and achievable...

## Possible solution/workaround
So, you may notice from the [documentation on Environment Variables](https://support.insomnia.rest/article/18-environment-variables), near the end of the page, there's a section where it talks about having **recursive variables**, and it mentions that Environment Variables could also hold Template Tags. This is what sort-of got my gears running into possibly "storing" the created User's ID into an Environment Variable. So, after more playing and fiddling around with Insomnia, I built up the following scenario based on GitHub's public API:

First, I began by retrieving a specific user. Kept things plain and simple here, since I currently don't have any development environments to simulate the creation of records/objects, I'm just querying for a specified user (in this case myself). I'm somewhat certain that this could easily be replaced by your user-creation endpoint without undergoing any major changes.
<img width="1216" alt="Screen Shot 2020-10-30 at 18 04 47" src="https://user-images.githubusercontent.com/824487/97760807-6a16bd80-1ada-11eb-8f14-d832d956f54a.png">

From here, I went to the Environment Variables section and created an object called `cache` where I'd like to store any "temporary" variables that would result from any additional requests. As you can see here, I've just added the key `cache.github_user_login` and set its value to a `Response -> Body Attribute` Template Tag, which I'm figuring would be similar to what you have in one of the GETs by User ID already. Note that this Template Tag is enclosed in quotation marks. Even though the User ID you may be using is numeric, you should also enclose it in these quotation marks -- otherwise, you'd get a compile error for the Environment Variables.
<img width="1216" alt="Screen Shot 2020-10-30 at 18 10 08" src="https://user-images.githubusercontent.com/824487/97761072-27091a00-1adb-11eb-9fc9-8e2c69f8aacb.png">

Now, I believe that you wouldn't have any problems setting up this first Template Tag, but I believe the most important setting would be the "Trigger Behavior," which is how the Template Tag determines when to fill this Environment Variable. I've set this value to "No History" and seems to be working pretty well for me -- it sticks with the values from the last request that has been performed for the `/users` endpoint above. It is possible that, if things are not working as expected for you handling user creation, you may wish to change this value for one of the other options available. I've taken the `$.login` JSONPath, which contains the username for the user that was queried (most of GitHub relies on user login names rather than user IDs).
<img width="1216" alt="Screen Shot 2020-10-30 at 18 15 27" src="https://user-images.githubusercontent.com/824487/97761359-e5c53a00-1adb-11eb-90ca-bc57d3c19ade.png">

And, with this, we're almost done! What's left is to simply use the `Prompt` Template Tag as you suggested, but configuring the `Prompt` to read values from the Environment Variable we just set up. What I'm doing for my example is simply querying the `/followers` endpoint for the user that we queried with the `/users` endpoint.
<img width="1216" alt="Screen Shot 2020-10-30 at 18 25 18" src="https://user-images.githubusercontent.com/824487/97761870-45701500-1add-11eb-911e-98f9bcb5b249.png">

Within the `Prompt` itself, just set the _Default Value_ to the cached Environment Variable we set up above, and make sure to uncheck the _Default to Last Value_ checkbox -- keeping it checked will show up the last value that was set within this Prompt box, without checking whether the Environment Variable has changed or not.
<img width="1216" alt="Screen Shot 2020-10-30 at 18 28 41" src="https://user-images.githubusercontent.com/824487/97762023-be6f6c80-1add-11eb-8ba2-58e6b275318a.png">

So now, if I search for another user from the `/users` endpoint, when I go to the `/followers` endpoint and hit submit, the prompt actually shows me the latest username that was queried with `/users`! 😁 (Didn't include a screenshot for this action, but I queried for your username with the `/users` endpoint before executing `/followers` again)
<img width="1216" alt="Screen Shot 2020-10-30 at 18 33 52" src="https://user-images.githubusercontent.com/824487/97762305-78ff6f00-1ade-11eb-8149-e730404fcc59.png">

There's quite a bit of pictures and text, but hopefully, this can help you and anyone else getting around this "issue" in the future. Also, if there's anything that may seem unclear, feel free to ask.

Granted, this may not seem extremely straightforward, but at least seems to get the job done! 😊 I'm thinking of this as an alternative to literally setting values within the Environment Variables: instead of concretely specifying an Environment Variable, you're specifying it by reference, so to speak.

I'm really looking forward to reading whether this was helpful for your scenario. 😊

EDIT: Just noticed that the [Chaining Requests Documentation](https://support.insomnia.rest/article/43-chaining-requests) has a tip that claims to "Use this tag inside an Environment Variable to prevent duplicated effort". Just haven't found anywhere more clearly that this is the way to go as an alternative to modifying Environment Variables.

**Comment by cbejensen** [comment]
@Kaitachi - so sorry for not replying! I had not read your response until now, but your workaround is working for me! Thank you very much for the detailed reply, that was extremely helpful.
