### ISSUE TITLE
Add support for importing GraphQL schemas from local files.

### ISSUE THREAD

**Issue by milessabin** [getinsomnia/insomnia#2743]
Complementary to #2629 ...

Sometimes server deployments disable GraphQL introspection. It would be nice if in those situations Insomnia could load the schema from a local SDL file.

**Comment by lodi-g** [comment]
This would definitely be a good feature. I'm willing to contribute to making that happen but I would need to make sure first that 1- Insomnia maintainers are willing to accept a related PR and 2- some guidance provided I've never worked on Insomnia's code before.
Thanks!

---

Because I had some time I went ahead and did the PR. Here is why I think this feature is useful:

I often work with GraphQL, and sometimes the introspection requests are blocked. In these case, the developers give me a GraphQL schema so I can still have the documentation.
However, Insomnia does not support importing local schema files, only fetching from internet. Therefore I must use Postman for this case, but I'd prefer to use Insomnia.

**Comment by milessabin** [comment]
It's still a feature I'd like :smile:
