### ISSUE TITLE
Support Object Literals for environments instead of JSON

### ISSUE THREAD

**Issue by nijikokun** [getinsomnia/insomnia#2762]
Since the application already converts the provided JSON object to a Object Literal. Not only would it be backwards-compat this change would reduce the time it takes to write the environment and also reduce the number of issues we see due to missing quotation marks as quotation marks inside of Object Literals is not required, but supported - as well as being able to support trailing commas.

Object Literal

```js
{
  firstName: "Xie",
  lastName: "Bo",
}
```

JSON

```json
{
  "firstName": "Xie",
  "lastName": "Bo"
}
```

**Comment by diyorbek** [comment]
Hello @nijikokun ! Can I get this task?

**Comment by nijikokun** [comment]
Welcome @Diyorbek! Absolutely, feel free to ask questions if needed

**Comment by diyorbek** [comment]
@nijikokun I played around with code and somehow achieved what we want. But there is a problem with the code editor. 

There are javascript and JSON modes. Currently, it's working in JSON mode. 

We will need JS mode to be able to use object literals, but JS mode gives us syntax error. Because it treats `{` here as the start of a block. Besides, we will have to limit the usage of JS.

It seems like we need a specific document type for this case. I made a research, but couldn't find anything helpful.

What is your thoughts on this?

Btw, as I said, I achieved what we want. But the editor is in `text/plain` mode. 😬

**Comment by nijikokun** [comment]
> We will need JS mode to be able to use object literals, but JS mode gives us syntax error. Because it treats `{` here as the start of a block. Besides, we will have to limit the usage of JS.

This makes sense, I'll defer to @develohpanda for implementation details, a naïve approach I can think of is to wrap the object with something like `var x = ... object here ...;` when passed to the linter/codemirror so that way it treats it as JavaScript. By default the highlighting as JS works (tested on codemirror without linting) for Object Literals.

**Comment by diyorbek** [comment]
@nijikokun Hello! It's been a while since the last time I gave some updates.

The feature is ready! 

But there are still some enhancements to be done. I will send a PR so that we could discuss some implementation details and improve it. I am sure that there are some problems as I am not very familiar with the codebase and the conventions).

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/29589560/101246544-56332c80-3714-11eb-97e8-ec20c4a8fcac.gif)
