### ISSUE TITLE
Can't import workspace "as is" (either I lose history or hierarchical org + config)

### ISSUE THREAD

**Issue by mxmlnglt** [getinsomnia/insomnia#2771]
**Describe the bug**
The whole export feature is inconsistent.

You have to choose between 3 formats, of which the first 2 are basically the same (JSON and YAML), and the 3rd one (HAR) is radically different:
 - with JSON/YAML you keep the hierarchical organization of your workspace(s) with folders + configuration (environments + variable templating) but NO request history is exported
 - with HAR you have history, BUT ONLY the LAST response of each & every request is exported AND you can't import it in a new Insomnia install (well, I mean the history is NOT imported) + you loose everything "Insomnia-esque" (i.e. folders + configuration)

I'm currently in a (forced) process of migration from Windows to MacOS and I don't know how to transfer my Insomnia config.

**To Reproduce**
1. Go to 'Application' menu, click on 'Preferences' then 'Data' tab
2. Click on 'Export Data' then 'All Workspaces'
3. Choose either format you want/expect (see above)
4. Save your export file and sync it to your new computer
5. On you new computer, import the file into Insomnia.

**Expected behavior**
The export file contains ALL that is included in Insomnia : the workspace(s), the requests & folders, environments + whole requests history.

Note: ALL this data is saved into the various `*.db` files located into the `%UserProfile%\AppData\Roaming\Insomnia` + I just found there are also responses bodies & timelines into the `.\responses` subdirectory.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional (64 bits, French)
 - Installation Method: Windows .msi file
 - App Version: v2020.4.0

**Additional context**
None.

**Comment by nijikokun** [comment]
Welcome @mxmlnglt, glad you brought this up. This has been discussed in the past, HAR was user requested from #416, lately discussion around sync in these issues #2587, and further even going so far as to being able to include plugin data #2695.

Here it does pose a challenge, as sometimes for security reasons, on-boarding team members, or third-party sharing purposes some users might not want to export _everything_. 

This makes me think having something like an option to select what level of detail seems like a good idea, and have it set to a sensible default - maybe the setting it is at currently to avoid messing with existing workflows or expectations.

---

Side note, I'm not sure that we could get the HAR export to support the same mechanism as above, but that would be _ideal_ so that way both forms produce the same output on import.

**Comment by mxmlnglt** [comment]
I did see that issue where HAR was request, but as far as I could see, this is rather a limited format and/or not really suitable for the whole "export" of Insomnia configuration & so.

Also I do understand the problem with security-related data, e.g passwords should not be exported by default, user should explicitly ask for it, but a question remains: how to flag such data as sensitive? (in my case, most of the passwords are stored as  strings in the various environments).

Now @nijikokun: a question for "now" regarding my current need: can I safely copy-paste from Windows to MacOS the database files I mentioned above?

**Comment by mxmlnglt** [comment]
any news @nijikokun?

**Comment by lucasgcb** [comment]
When importing a HAR, neither the history or the latest requests are imported into the application which has made some implementation directives more difficult.

It would be nice to have this feature considered, as it makes sense to me that an imported HAR would allow Insomnia to export the same HAR.
