### ISSUE TITLE
Authorization-Window incorrectly themed

### ISSUE THREAD

**Issue by BuchholzTim** [getinsomnia/insomnia#2779]
**Describe the bug**
The selected Theme in Insomnia Designer does not correctly apply to the "Authorize"-Window.

**To Reproduce**
1. Select a Theme other than "Designer Light", preferably some dark theme
2. Define a Security Scheme (in my Case JWT Bearer)
3. Click on the "Authorize"-Button, which should have appeared after defining the Scheme
4. The new Window should not be correctly themed, as shown in the screenshot.

**Screenshots**
![Insomnia-Theme](https://user-images.githubusercontent.com/25686940/97170486-13347f80-178c-11eb-96e0-9657d2b14f3c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 19042
 - Installation Method: .exe-Installer
 - App Version: 2020.4.2

**Comment by filfreire** [comment]
This should have since been fixed. I tried reproducing it on[ latest beta (2022.6.0-beta.1)](https://github.com/Kong/insomnia/releases/tag/core%402022.6.0-beta.1) but was unable to. Examples:



![Image](https://user-images.githubusercontent.com/11976836/184339972-beea71b9-9fb4-45fb-ade1-0de7d9ee6853.jpg)
![Image](https://user-images.githubusercontent.com/11976836/184339970-53a0ad08-ba80-40d5-b7ec-4e23f46932f1.jpg)
![Image](https://user-images.githubusercontent.com/11976836/184339971-ec05d31c-13d2-4d87-8ab7-488ad86edf71.jpg)
