### ISSUE TITLE
Feature Request: Extend template tags system to chose one of several username/password pairs

### ISSUE THREAD

**Issue by tauinger-de** [getinsomnia/insomnia#2789]
I have a "Log In" request, whose output is chained to other requests (access token).

Now I am looking for a way how to add several username/password pairs to my environment to chose from, so that I can log in with one of those test users but still have all my subsequent requests chained to that single login request.

Maybe the "prompt" tag can be extended for this?

**Comment by zigfreid5** [comment]
You can accomplish this several different ways. I recently adopted a variation of the suggestion from this comment on another feature request: [Issue #283](https://github.com/Kong/insomnia/issues/283#issuecomment-733739487)

Prior to that I was using a "Prompt" tag in "Username" and "Password" environment variables and then using chained requests for the access token. The issue that came from this was that I was getting prompted twice because of what I consider a bug in the chained request implementation, so I actually used a plugin I wrote for a different initial purpose called "Prompt-Once" as a workaround. You can find it on [Github](https://github.com/zigfreid5/insomnia-plugin-prompt-once). Make sure you have the Insomnia option to "Filter Responses By Environment" to fit your use case.

I've wanted a similar feature for other use-cases, so I may take a crack at creating another plugin to be used as sort of a drop-down selection from a list of predefined values. We'll see. Anyway, hopefully you get something to work for you!

**Comment by zigfreid5** [comment]
Actually, I just came across this plugin: https://insomnia.rest/plugins/insomnia-plugin-param which seems much more fully-featured than the basic one I wrote. Might do what you're looking for!

**Comment by kreosus** [comment]
Hi @zigfreid5, Good day and I hope that all is well. We are closing this issue out. If you require any future assistance please let us know. Have a nice day.

**Comment by tauinger-de** [comment]
Sorry, I don't get it. Why is this marked "as completed"..? Has it been implemented in Insomnia core? The workarounds above don't provide what my original feature request is aiming at
