### ISSUE TITLE
Breaking change in env variable auto-completion in 2020.5.0-beta.2

### ISSUE THREAD

**Issue by jgiovaresco** [getinsomnia/insomnia#2872]
**Describe the bug**
In version `2020.5.0-beta.2`, it seems that values coming from an environment are prefixed with `_.` when I use autocompletion.

The main issue is that it breaks compatibility with previous versions. `2020.4.2` can find an env var name `_.foo`.
However, if I open an existing request, `v2020.5.0-beta.2` can find the env `foo`

**To Reproduce**
1. With the following environment

```
{
  "foo": "foo",
  "bar": "bar"
}
```

2. Use an env var inside the request body using auto-completion (Cmd+Space)
3. All the env vars are prefixed with `_.`

**Expected behavior**
I expect to see the var `foo` instead of `_.foo`.

**Screenshots**
in `2020.5.0-beta.2`
<img width="348" alt="Screenshot 2020-11-25 at 17 07 40" src="https://user-images.githubusercontent.com/4171593/100254015-1a44de00-2f42-11eb-861d-71e2c30dc215.png">

in `2020.4.2`
![image](https://user-images.githubusercontent.com/4171593/100254105-30eb3500-2f42-11eb-8542-d1c4dfcceea3.png)

**Desktop:**
 - OS: macOS 10.15.7
 - Installation Method: homebrew
 - App Version Insomnia Core 2020.5.0-beta.2

```
Version: Insomnia Core 2020.5.0-beta.2
Release date: 18/11/2020
OS: Darwin x64 19.6.0
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0
```

Using `git bisect` I've found the commit responsible of the new behaviour: https://github.com/Kong/insomnia/commit/1bbbf38a9653792fd137662d015846f4334b1989

**Comment by develohpanda** [comment]
Hey @jgiovaresco, yes this is by design but should be transparent to a user upgrading _to_ 2020.5, The old syntax `{{ foo }}` and the new syntax `{{ _.foo }}` both work in 2020.5, but moving forward, auto-completion will prefix with `_.`

Try use the following environment in 2020.4.2 and 2020.5.0-beta.2 and see how each version behaves differently.

```json
{
  "foo-bar": "foobar"
}
```

The `_.` prefix was introduced with #2601 in order to support kebab-case environment variable keys, among other special characters in the keys. Unfortunately supporting downgrades and compatibility with previous versions has always been out of scope; our database changes and sync features are also impacted by downgrading. 

We can't actually do anything about it either, since we can't change the logic in 2020.4.2 that users have installed to gracefully handle a new features like this. 🙂 Thanks for taking the time to investigate and report!

**Comment by jgiovaresco** [comment]
👌 
I took the liberty to create an issue when I noticed that when I've updated a request using 2020.5 it brokes the request when a co-worker using the 2020.4.2 tried to execute this updated request.

I was not aware that compatibility with previous versions is out of scope. I can see the benefit of that :)

I don't know if you already plan it, but it would be nice to add a note on that in the future release note, to inform users of that change.

**Comment by develohpanda** [comment]
No worries, I'll make a note in the changelog for the stable release for this! Thanks for bringing to my attention 😊

We have some cards in place to address backwards compatibility with sync as well, although in general we don't support downgrades, it wasn't out of scope for this feature in particular.

We're anticipating less of an issue with the stable release of this, as it should auto update for the large majority of users and keep everyone on the same version. 😊
