### ISSUE TITLE
Black font for all dark thems in macOS Big Sur

### ISSUE THREAD

**Issue by DeeGeeMan** [getinsomnia/insomnia#2884]
**Describe the bug**
The font color is black for all dark themes

**To Reproduce**
1. Select any one of the dark themes (e.g. 'Simple Dark')
2. The font color is black

**Expected behavior**
White font color for all dark themes.

**Desktop (please complete the following information):**
 - OS: macOS 11.0.1
 - Installation Method: homebrew
 - Version: Insomnia Core 2020.4.2

**Comment by MrSnix** [comment]
Hi, I tried to reproduce the bug on 'Simple Dark' and 'Hyper' but I was not able to.

![image](https://user-images.githubusercontent.com/20780192/100794247-91381600-341d-11eb-8ed1-cc58b31c0df2.png)

**Tested on:**
Version: Insomnia Core 2020.4.2
Release date: 21/10/2020
OS: Darwin x64 20.1.0 // macOS BigSur 11.0.1
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0

**Can you try to inspect the console?** 
You can do that on `View > Toggle DevTools` and clicking on the `Console` panel.
If you find something interesting please, post it.

**Comment by DeeGeeMan** [comment]
It looks like a font issue, I am using **Source Code Pro** font...
<img width="764" alt="image" src="https://user-images.githubusercontent.com/21670040/100901444-cf6f1d00-3491-11eb-9a00-8eddfe751890.png">
If I change it back to the default, it works.

**Comment by DeeGeeMan** [comment]
Btw, the font is registered correctly, I use it in other editors...
<img width="984" alt="image" src="https://user-images.githubusercontent.com/21670040/100901972-6cca5100-3492-11eb-83ea-0c077a9ee3b5.png">

**Comment by inimicus** [comment]
I experienced the same issue after upgrading to Big Sur from Catalina and found no way to resolve since. All themes rendered with dark fonts in the editor/results and text was unreadable.

I, too, am using a Source font, albeit Source Sans Pro instead of Source Code Pro.

Coming across this issue, I tried changing my fonts. No effect. Any font I selected continued to render dark even after restarting the app. Then... I selected to a non-Source font and immediately changed themes. Boom, back to the proper and expected text color. Changing back to Source Sans Pro maintains the correct colors and all is well.

I can no longer reproduce the issue to confirm the steps involved, but perhaps this may help others in a similar situation. It was some combination of changing the selected `Interface Font` and `Text Editor Font` followed by a change of theme immediately after.

Version: Insomnia Core 2020.5.2
Release date: 12/9/2020
OS: Darwin x64 20.1.0
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0

**Comment by nijikokun** [comment]
This looks like it may be resolved by #3223 - I am currently running the Alpha Build with no issue. Followed the steps above exactly as written with no issue.

Steps Taken:
1. Changed Interface Font
2. Changed Text Editor Font
3. Changed Theme

Outcome:

Theme rendered perfectly.

<img width="1392" alt="Screen Shot 2021-03-23 at 9 09 10 AM" src="https://user-images.githubusercontent.com/198276/112178997-7f8aa200-8bb7-11eb-9428-e5ee28b69888.png">
