### ISSUE TITLE
Use pkce can't be enabled

### ISSUE THREAD

**Issue by kdankert** [getinsomnia/insomnia#2889]
**Describe the bug**
Using the latest early access version 2020.5.0-beta.2 it is not possible to activate pkce support in the authorization code flow. Any authentication request are done without pkce support.

**To Reproduce**
1. Create a new request
2. Add OAuth2 authentication
3. Click on use pkce

**Expected behavior**
The checkbox should toggle and pkce should be used 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Installation Method: homebrew and standard produce the same error
 - App Version 2020.5.0-beta.2

**Additional context**

Might be interesting for @DASPRiD, who implemented pkce support.

**Comment by rafaelrenanpacheco** [comment]
Since this option need to be fixed, I'll hop on this thread and suggest a reorder on the PKCE checkbox, to be like this:

![image](https://user-images.githubusercontent.com/12160864/100949134-54852100-34e8-11eb-82d4-12063038721c.png)

The current placement seems a little odd:

![image](https://user-images.githubusercontent.com/12160864/100949237-901feb00-34e8-11eb-8305-da5067733ce1.png)

Another request would be to bring the `Clear OAuth 2 session` to the `Advanced Options`. This button is only reachable from the preferences window, which difficult testing using different users. This is the button:

![image](https://user-images.githubusercontent.com/12160864/100949369-e3923900-34e8-11eb-95b2-326916ff3b9d.png)

**Comment by simardst** [comment]
I have the exact same issue with version 2020.5.0

**Comment by simardst** [comment]
![image](https://user-images.githubusercontent.com/1949586/101026000-5977be00-3544-11eb-9745-7935ff85be6f.png)

![image](https://user-images.githubusercontent.com/1949586/101026171-9348c480-3544-11eb-8617-1ea4604b134b.png)

**Comment by develohpanda** [comment]
> Another request would be to bring the `Clear OAuth 2 session` to the `Advanced Options`.

@rafaelrenanpacheco could you please create a separate feature request for this? We will be hot-fixing this with a minimal change but I think your requests and suggestions are valid. Thanks!
