### ISSUE TITLE
Insomnia Designer: light themes cause mostly unusable colour scheme in examples

### ISSUE THREAD

**Issue by pohutukawa** [getinsomnia/insomnia#2948]
**Describe the bug**
When using light themes, the examples of interactions in the Insomnia Designer are almost unreadable. It appears that the examples are always rendered using a dark theme, however it's picking up colours from the pallet of the current light theme. Therefore certain elements are almost unreadable in most of all light themes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to preferences
2. Select one of the light themes (e.g. "Designer Light")
3. Open an OpenAPI spec that contains examples (e.g. of a request body)
4. View the example in the right hand live preview
5. Try to figure out what certain elements are
 
**Expected behaviour**
All UI elements are fully and well readable no matter what theme is selected. This means that likely in a light theme, the example colour pallet is using a light theme in itself as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/422922/102296350-02e19980-3fb2-11eb-9342-4d426a345e9a.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu (Kubuntu) Linux (Groovy Gorilla, 20.10)
 - Installation Method: snap package
 - App Version: 2020.5.2

**Additional context**

**Comment by YuqiHuai** [comment]
Insomina app

**Describe the bug**:
There is another similar UI problem with the Authorize modal. The window is clear when you are using light theme, and not so well when you use a dark theme.
<img width="656" alt="image" src="https://user-images.githubusercontent.com/34195403/115964286-56fb1c80-a556-11eb-87f3-7fdc1ebc2fb6.png">
<img width="659" alt="image" src="https://user-images.githubusercontent.com/34195403/115964301-62e6de80-a556-11eb-80c4-2506c4beaab6.png">

**To Reproduce**
1. Set up securitySchemes in the DESIGN document. For example:
```
  securitySchemes:
    JWT_Bearer:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT 
 ```
2. Click on the "Authorize" button at the top of the preview

**Expected behaviour**
The UI should not have a light-themed window when the user is in a dark theme. The text should also change color to increase readability.

Desktop:
- OS: macOS Big Sur Version 11.1
- Installation Method: Installation package from https://insomnia.rest/download
- App version: 2021.2.2

**Comment by develohpanda** [comment]
Seems this was fixed in https://github.com/Kong/insomnia/pull/3369 🥳
