### ISSUE TITLE
Design doesn't working in Insomnia Designer

### ISSUE THREAD

**Issue by riibeirogabriel** [getinsomnia/insomnia#2958]
**What is your question?**
I have been imported a postman collection to insomnia designer and it works fine to debug the requests, but when i switch to Design this error message appear:
![image](https://user-images.githubusercontent.com/33736256/102594736-590b2580-40f5-11eb-97f9-77663aedcb9a.png)

I sincronized the project with a git repo, and tried set a spec version in .insomnia/ApiSpec yaml without sucess:
![image](https://user-images.githubusercontent.com/33736256/102594893-966fb300-40f5-11eb-9f29-ef2782c78660.png)

Someone can help me please? thanks!

**Comment by nijikokun** [comment]
From the screenshot your specification contents are empty, this would be the cause for the lack of rendering since the renderer relies on the [specification contents](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml#L1) to infer the version.

This would be expected as we haven't built support for import of OpenAPI specifications with postman collections into Designer.

I'd be curious to see the collection, and your expectations of what would show up here. Do you store an OpenAPI specification within the collection, and is it exported?

**Comment by riibeirogabriel** [comment]
I understand, but where i can set the specification in insomnia files? i tried set the "openapi: '3.0.0'"  in .insomnia/ApiSpec yaml but this doesn't work.
I have used the insomnia editor to design the REST API of this [project]( https://github.com/learningOrchestra/learningOrchestra)
You can find the collection design in this [repo](https://github.com/learningOrchestra/restApi)

**Comment by nijikokun** [comment]
@riibeirogabriel You'd set the specification under `contents` in the ApiSpec or within the editor pane to the right of the preview pane:

![image](https://user-images.githubusercontent.com/198276/102624339-b48ae280-40f8-11eb-88ca-5bb172c7090d.png)

**Comment by riibeirogabriel** [comment]
Works here, thanks @nijikokun!!
