### ISSUE TITLE
[Bug] Long Query parameter value prevents editing

### ISSUE THREAD

**Issue by reevesm** [getinsomnia/insomnia#300]
## Overview

- `Insomnia Version:` 5.2.0
- `Operating System:`  MacOS 10.11.4
- `Summary: ` Query parameter with long value prevents editing due to large url preview window and no scrolling

## How To Reproduce

1. Create new request
2. Add a single query parameter with a very long value
3. You can no longer add any more query parameters or edit the just added one because the url preview window takes up the entire space and cannot be scrolled down

**Comment by gschier** [comment]
hi @reevesm, thanks for the report. Can you attach a screenshot of the problem?

**Comment by gschier** [comment]
I assume this is what you mean? Here's a screenshot of a fix I just implemented:

![image](https://user-images.githubusercontent.com/587576/27056991-0fefe3c4-4f7f-11e7-9c64-c9dc742731ac.png)

**Comment by reevesm** [comment]
Yes, sorry I didn't get the screenshot to you yet. Looks like your solution solves the problem. Thanks for the quick turnaround.

**Comment by murame** [comment]
- Insomnia Version: 5.16.2
- Operating System: Windows 7 Professional x64

This bug seems to occur also in the 5.16.2 version.
![long](https://user-images.githubusercontent.com/39079071/39742049-127f19a0-52d7-11e8-87ac-d23b2170f227.png)
![ver](https://user-images.githubusercontent.com/39079071/39742054-154c55c6-52d7-11e8-8b73-a7eea2d65a68.png)

**Comment by gschier** [comment]
@murame please post a new issue with more details at to what your problem is
