### ISSUE TITLE
Forced to upgrade to a beta feature

### ISSUE THREAD

**Issue by petefox** [getinsomnia/insomnia#3050]
We started seeing a notification every few seconds, that tells us to upgrade to the beta of Version Control.

1: Why would you **FORCE** someone to upgrade to a BETA feature?

2: Why would you **FORCE** someone to upgrade from one minute to another, instead of letting them do it when they have time? 
You are essentially taking control of your users' daily schedule and forcing them to work on this before they can continue finishing up whatever they were otherwise working on.

**Comment by nijikokun** [comment]
Welcome @PeteFox

Apologies for the interruption, let me address these in detail as to our thinking and understanding around why we did the following actions.

> Why would you **FORCE** someone to upgrade to a BETA feature?

While it is called "Version Control Beta" today, it's hardly "Beta" in our eyes, and over the past few releases we have been improving it more and more, and it's far more stable and less prone to data-loss than the existing Legacy sync feature. In the next release we will be removing the Beta text from Version Control Beta and promoting it to stable. This is merely a cosmetic change and not any change to the underlying code powering Version Control. 

With this change we will also be removing Legacy Sync. Currently due to the way that the sync system is setup, being end-to-end encrypted, it's not possible for our backend to migrate users and the only way for users to migrate is to do it themselves. So we launched these notifications to warn users, and give them the chance to migrate before we switch the system off from the servers.

> Why would you FORCE someone to upgrade from one minute to another, instead of letting them do it when they have time?
You are essentially taking control of your users' daily schedule and forcing them to work on this before they can continue finishing up whatever they were otherwise working on.

The reason for the drastic nature of this is because we do not want users to lose data. I know it's inconvenient and we apologize that it's intrusive, admittedly so, and that was the intention behind it, to force users to upgrade to avoid losing data as soon as possible - and as early on, so it's not something they forget, and when the Legacy Sync system is offline, they do not lose that data forever.

---

While it is intrusive, this should be the only time we have to take action like this, as going forward with Version Control, we can do migrations without interrupting your workflow. I apologize for the inconvenience this time around. 🙏
