### ISSUE TITLE
[Bug] issue with updates

### ISSUE THREAD

**Issue by vavgustov** [getinsomnia/insomnia#306]
## Overview
- `Insomnia Version:`  5.1.1 (5.1.1.361)
- `Operating System:`  OS X 10.11.6
- `Summary: ` App always show notification about update on startup

## How To Reproduce
1. Launch Insomnia
2. After some time app will show notification: 'Insomnia Update Ready. Relaunch the app for it to take effect'
3. Relaunch Insomnia
4. I'm again see the message from step 2 on each launch

**Comment by gschier** [comment]
Hi @vavgustov,

I'm not sure how much help I can provide, as Insomnia uses Squirrel (build into Electron) to manage auto-updates. It's possible that something like something like strict file permissions or a non-standard installation could cause it to fail. Was 5.1.1 the first version of the app that you installed? Did you install it via the DMG download on the website?

Since you are seeing the update notification, it means that Squirrel has at least downloaded the latest update (currently 5.2.0) and thinks that it has installed it correctly. I'm not sure, but it looks like Squirrel downloads updates to `/Applications/Insomnia.app/Contents/Frameworks/Squirrel.framework/Versions`.

![image](https://user-images.githubusercontent.com/587576/27097788-4ca6ed02-502a-11e7-9dc9-ba5374f945b4.png)

Let me know if any of that helps.

**Comment by vavgustov** [comment]
I installed DMG from website. 

5.1.1 wasn't first version. First version was 5.0.20 or 5.1.0 and updates are worked ok.

My terminal output similar to yours except my dates are May 29 and May 30 (seems these dates related to v5.1.1 release date).

I'm think if it's related to Squirrel I'll keep this app version for some time and may be it will start work with next updates. Otherwise I'll reinstall DMG.

Thanks!
