### ISSUE TITLE
Inso run tests failure

### ISSUE THREAD

**Issue by findrella** [getinsomnia/insomnia#3098]
![issue](https://user-images.githubusercontent.com/10885283/108472147-a8eca100-728c-11eb-8066-ec156f93c7ad.PNG)
**What is your question?**
Inso test run command Fails for test which queries contain an Environment variable in their headers/Body, any ideas please?

**What is the context?**
I am trying to run inso test run in order to execute  my test Suite, but all the Tests corresponding to queries that have an Environment variable in their headers or Body fail. any ideas please?

Same when using a plugin related feature on a header, like using insomnia-plugin-save-access-token, it also fails with the error message  'Error: unknown block tag: apitoken'
![image](https://user-images.githubusercontent.com/10885283/109274813-32afe780-7814-11eb-9bbe-8060233797b5.png)
![image](https://user-images.githubusercontent.com/10885283/109274899-4fe4b600-7814-11eb-98b9-ef80851ae063.png)

**Comment by andressalro** [comment]
What command are you executing? if you have environment variables, when executing` inso run test` you must indicate the environment tag with `--env `

Check the documentation: https://support.insomnia.rest/article/116-cli-run-test

**Comment by findrella** [comment]
> What command are you executing? if you have environment variables, when executing` inso run test` you must indicate the environment tag with `--env `
> 
> Check the documentation: https://support.insomnia.rest/article/116-cli-run-test

Thanks for your answer.
The command run is: inso run test --workingDir "...\AppData\Roaming\Insomnia Designer" --appDataDir ...\AppData\Roaming" 
that interrupts me afterwards to choose the environment and after choosing it i got that error, the error concerns the environment variables rather than the insomnia environment where the tests should be run.

**Comment by develohpanda** [comment]
Hi @findrella! Plugins aren't supported with unit tests being run through inso currently, but environment variables inside the headers and body _should_ be working. I can't seem to reproduce it locally on Windows with the latest version of Insomnia (2021.1.1) and Inso (2.2.30). I have a request, which consumes an environment variable in it's header, and a unit test which executes that request, running successfully through inso. 

---

Also just a note, you shouldn't need to add the `--workingDir` or `--appDataDir` flags. Inso will find the Insomnia directory by itself if it's installed in the [default location](https://support.insomnia.rest/article/202-application-data). Using `inso run test` should work, and if it doesn't you can run `inso run test --verbose` to see what data source it has loaded.

As of Insomnia v2021.1.1, Insomnia Core and Designer were merged into a single application, Insomnia. And inso v2.2.30 was updated to look at the Insomnia directory by default (instead of Insomnia Designer).

**Comment by develohpanda** [comment]
Closing this issue assuming accessing environment variables has been resolved. The lack of plugin support for Inso is being tracked through #3261 and some other related tickets. Please re-open this or open a new issues if you have any more questions! 😄
