### ISSUE TITLE
Add curly brace escaping feature

### ISSUE THREAD

**Issue by iinuwa** [getinsomnia/insomnia#3119]
Double curly braces `{{ ... }}` are used to inject Insomnia environment variables, but if your payload has a double curly braces pattern, the only way to send this to the upstream is by disabling rendering of the request body. However, that means you can't use environment variables at all in this payload.

It would be nice to be able to escape Insomnia environment variables so you can use both patterns in one payload.

**Comment by TheSamsa** [comment]
Yes, this would be nice!

**Comment by dimitropoulos** [comment]
I'm interested in hearing more about this.  Could you please provide a concrete example on one such request (say, that we could use to build a failing test that we would then make pass by implementing your feature).

**Comment by TheSamsa** [comment]
First: It seems I can do what I need if I enable "Skip rendering request body". Since my Insomnia Environment is only used for the URL, but not in the request body.
But as soon as I want to extend my request chain I'll run into trouble (if I want to use responses from a request before)

I have a REST API where the user can POST some Template file, and our template engine uses `{{ .var }}` syntax to fill in values. The user does send something like this
```
{
  "name": "template name",
  "content": "Example {{ .title }}",
  "keys": [
    {
      "key": "title",
      "type": "string"
    }
  ]
}
```
But if I want to use it as request body in insomnia it does tell me I don't have a environment variable `title` specified. Which is true, but this is just my request, I do not want to paste a Insomnia Environment variable there.

**Comment by dimitropoulos** [comment]
thanks.  what would be the syntax to tell insomnia you _did_ have a `title` variable that you _did_ wan to paste in there?  how would you suggest we differentiate between the two?

**Comment by TheSamsa** [comment]
My fist impulse would be to escape the `\{\{ .title \}\}` if I want insomnia to know it is only text.
Well it is kinda ugly, but I could live with that (regex anyone?). And it does match the default escape sequences out there.

On the other hand I understand this is some niche case ;)

**Comment by iinuwa** [comment]
Using backslashes was my first inclination when I figured out it didn't work.
I think the only problem with the above is that it wouldn't be valid JSON (although using templates besides within JSON strings also results in invalid JSON. There are also other formats supported by Insomnia besides JSON, so that might not be a big deal.)

Some alternatives? E.g.
`{{{{ title }}}}` (two braces escapes a single brace) or
`{{{ title }}}` (surround template with one pair of curly braces to ignore templating)
`\{{ .title }}` (prefix template with backslash to ignore templating)

I agree that it's a niche for payloads that include curly brace templates inside them (for me I was working with Teams webhooks that uses curly brace templates to enable formatting the date/time in the user's local timezone). If it were pursued, maybe it would be an advanced option that is disabled by default.

**Comment by TheSamsa** [comment]
Another alternative could be an escape sequence inside the curly braces:

`{{ #.title }}` (everything after `#` is printed raw

**Comment by develohpanda** [comment]
Hey folks, for the time being, is disabling rendering of the request body an option? This does mean that template tags and environment variables cannot be used, but it also means your curly brace payload would work.

This option is available under request settings for each individual request.

![image](https://user-images.githubusercontent.com/4312346/113248897-491cf780-931a-11eb-931e-5931f80c4722.png)

**Comment by develohpanda** [comment]
Actually it seems like [raw tags](https://support.insomnia.rest/article/189-how-can-i-temporarily-disable-nunjucks-templating) should be able to cater for this!

**Comment by inabajunmr** [comment]
The following pattern I tested works well also.
```
{{ '{{variable}}' }}
```

ref. https://github.com/mozilla/nunjucks/issues/604#issuecomment-465493535

**Comment by develohpanda** [comment]
Thanks for that @inabajunmr! Just tested it myself and it seems to work as well, although Insomnia attempts to add a pill in the UI for `{{ '{{variable}}' }}` and spectacularly fails. The syntax for the raw tag would be `{% raw %}{{variable}}{% endraw %}` which is also standard Nunjucks syntax and has special case handling in Insomnia.

<img width="873" alt="image" src="https://user-images.githubusercontent.com/4312346/120268350-bee11780-c2f9-11eb-9fe1-aa4cc77431db.png">

@iinuwa I will close this issue as resolved because it does seem to work without disabling rendering entirely - anything inside the raw tags will be used raw, and other areas in the same text field can still use environment variables.

Please re-open this issue if it does not cater for your use case!

**Comment by tyler71** [comment]
For reference, this also worked well surrounding an entire JSON POST body
```json
{% raw %}
[
  {
    "valuea": {
      "_gte": "{{ date_from }}"
    }
  },
  {
    "valuea": {
      "_lte": "{{ date_to }}"
    }
  }
]
{% endraw %}
```
