### ISSUE TITLE
Duplicated workspace always use original project Environment

### ISSUE THREAD

**Issue by RobGThai** [getinsomnia/insomnia#313]
## Overview
- `Insomnia Version:` _5.3.3_
- `Operating System:`  _MacOS 10.12.5_
- `Summary: ` Duplicated project doesn't use itsown environment_

## How To Reproduce
1. _Create workspace with sub environments_
2. _Open workspace setting, select duplicate and give it proper name_
3. _Make sure you switch to the newly duplicated workspace_
4. _Try changing the environment in the new workspace_
5. _Your workspace will not recognized the new value, even if you add a new key_

## Other Notes

Duplicated workspace should also duplicated the environments.
Adding new environment seems to refresh the environment configuration but the app should do this by default.

**Comment by gschier** [comment]
Thanks @RobGThai. 

It turned out that everything _was_ being duplicated correctly, but the new workspace still had it's `activeEnvironmentId` set to the old workspace's environment. Activating a different environment on the new workspace will provide a temporary workaround to this until the next release is out (probably tomorrow).
