### ISSUE TITLE
Reduce Header padding to match the UI

### ISSUE THREAD

**Issue by fayazara** [getinsomnia/insomnia#3168]
**Is your feature request related to a problem? Please describe.**
The Header in the new update is extremely big and does not match the Insomnia UI I have been using for years.
![image](https://user-images.githubusercontent.com/15716057/110355657-7d74ff00-805f-11eb-9c25-3a8978364b11.jpg)

**Describe the solution you'd like**
I have added `padding: 0.65rem;` to `.app-header` class, which makes the UI look much cleaner and uniformed.
![image (1)](https://user-images.githubusercontent.com/15716057/110355795-a0071800-805f-11eb-84d6-8db7dd1305e6.jpg)

**Comment by sonicyeti** [comment]
@fayazara Thanks for the observation and padding tweak! There are a few child elements inadvertently impacting the overall height that would be great to address vs. compensating via wrapper padding reduction.

@nijikokun The increased height is partially due to the padding of the settings & login items in addition to their icon font size. We pick up about 6px by dropping the font size from xl to lg. See attached.

![Screen Shot 2021-03-08 at 12 35 08 PM](https://user-images.githubusercontent.com/52717970/110358855-cf3f6a00-800a-11eb-9d5b-af8195493deb.png)

Thoughts?

**Comment by nijikokun** [comment]
> The increased height is partially due to the padding of the settings & login items in addition to their icon font size. We pick up about 6px by dropping the font size from xl to lg. See attached.

From observation it seems we can definitely reduce the sizing of the icons as the account icon looks stretched in the current version with the default font size.

**Comment by sopidos** [comment]
I very much question the addition of the header at all. It cuts away quite a huge chunk of screen real estate, compared to previous URL up-top: ![](https://raw.githubusercontent.com/Kong/insomnia/17cd05690a029b52e55db8e5017aa6808edbea59/screenshots/main.png)

Starting from this
![](https://user-images.githubusercontent.com/15716057/110355657-7d74ff00-805f-11eb-9c25-3a8978364b11.jpg)
it can pretty much be condensed down to this
![2021-03-23_1616517792](https://user-images.githubusercontent.com/1887036/112186598-981faa00-8c01-11eb-826c-7963dd7853a3.png)

No need to have both logo and Dashboard text, make the logo the dashboard button.

The cog and profile icons look rather out of pace compared to all other iconography as well, but I guess that is unrelated to the header, they just happen to be in the header now.

**Comment by nijikokun** [comment]
@sopidos thank you for the additional input but as it's not related to the original topic I've marked it as off-topic considering it already has a PR. 

That said there is an [item on the roadmap](https://github.com/Kong/insomnia/projects/5) to address the header footprint and navigation in a more robust manner which will address the concerns you've raised. You should see a fully-fledged roadmap brief show up shortly on the repository with more information instead of it's current placeholder. 🤗

**Comment by sopidos** [comment]
I would consider it very much on topic, it being extremely big, quoting the original text from https://github.com/Kong/insomnia/issues/3168#issue-824768288

> The Header in the new update is _extremely big_ and does not match the Insomnia UI I have been using for years.

(emphasis mine)

And that fact that no PR fixing it has been accepted yet.

**Comment by nijikokun** [comment]
@sopidos apologies - I'd like to keep it scoped to the level of the PR for this issue and title (padding). We have another issue pending that more directly addresses the broader topic (footprint / navigation), hence marking as off-topic for this specific issue. The PR while not accepted / worked on is mostly due to major release work priority - not a product issue.

**Comment by K2ouMais** [comment]
@sonicyeti

How do you have your header like that? I am also in the newest version and my header looks different.

![{90F70030-D502-441E-B88A-39300E214D6C}](https://user-images.githubusercontent.com/52510455/112600630-be1b9900-8e11-11eb-9c91-2b34cf740aef.png)

Any plugins installed?

**Comment by sonicyeti** [comment]
> How do you have your header like that? I am also in the newest version and my header looks different.
> Any plugins installed?

@K2ouMais this was after tweaking a few css props via dev tools. Not to worry though, we have some header evolution work in the backlog!

**Comment by nijikokun** [comment]
@K2ouMais you can get that header by creating a Design Document from the dashboard 👍

**Comment by nijikokun** [comment]
Update for longer-term solution, we have a roadmap item to address the header footprint here #3243 (design pending) will open up to comments once the design is available
