### ISSUE TITLE
[Feature] Create a Docker image to build for both development and production

### ISSUE THREAD

**Issue by lucraraujo** [getinsomnia/insomnia#324]
Since I started to use Docker last year, I'm having a tendency to use Docker images for almost everything related to development and deploy.
I think it would help a lot have an image (or more) to deploy Insomnia, since it would have all dependencies embedded in the image and provide a homogeneous environment for everyone willing to contribute to the project.

**Comment by gschier** [comment]
Hey @lucraraujo.

What exactly do you mean by "deploy Insomnia"?

I love Docker as well, but I'm not sure it would work for Insomnia for the following reasons:

1. Insomnia uses native NodeJS c++ addons, which need to be compiled on each platform (Docker is only Linux)
2. `electron` needs to be available on the host machine (since it's a GUI) to run Insomnia in dev mode (would require nodejs/npm anyway)

Let me know if you think Docker could still help in some way.

**Comment by lucraraujo** [comment]
1. Deploy Insomnia in a sense of build packages for distribution.
2.  Ok, I'll give it a try this weekend.
2.1 I'll have to consider all the drawbacks of using Docker for both development and package build.

**Comment by gschier** [comment]
Let me know what you find 😄

**Comment by gschier** [comment]
Going to close this one for now but feel free to revive it if you figure something out
