### ISSUE TITLE
Feature request: Allow dark mode during Insomnia startup

### ISSUE THREAD

**Issue by AlexNaga** [getinsomnia/insomnia#3250]
Even though I have dark mode selected as a theme in Insomnia, during startup, it will flash a white page before Insomnia has fully loaded.

![Insomnia startup](https://user-images.githubusercontent.com/14061533/112956013-4cf52200-9140-11eb-90b0-e4f5cf20001e.png)

Could this be set to a dark color? As my eyes are incinerated during late nights when opening Insomnia.

```
Version: Insomnia 2021.2.1 
Release date: 3/24/2021
OS: Darwin x64 20.3.0
Electron: 9.3.5
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.73.0 OpenSSL/1.1.1j zlib/1.2.11 brotli/1.0.9 zstd/1.4.9 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0
```

**Comment by dimitropoulos** [comment]
![image](https://user-images.githubusercontent.com/15232461/113001499-db68a400-913e-11eb-8359-32328f715e64.png)

I share your desire to fix this.  Turns out it's an electron thing and can be fixed with a one-liner.  The above screenshot is just for the primitive fix.

The "real" fix would be to set the initial electron window to whatever the theme background is.

Would you mind opening a PR with (at least) the above, and we can go from there.  I see no reason we can't get this fixed quickly enough.  I share your frustration on this one!  MY EYES! MY EYES! haha.

**Comment by AlexNaga** [comment]
@dimitropoulos I tried adding the `backgroundColor` option and it worked. The problem however is that we can't access the Insomnia settings (and the current theme) during the build step.
