### ISSUE TITLE
Import File:  Difficulty accessing import data from file

### ISSUE THREAD

**Issue by adoniasvitorio** [getinsomnia/insomnia#3275]
**Describe the bug**
When I try import my collections all the texts in my file box become illegible.

**To Reproduce**
1. Go to 'Home Insomnia Collection'
2. Click on 'Import from File'
3. See error in file box

**Expected behavior**
I was hoping to open my file box and choose the schema to import.

**Screenshots**
![Captura de tela de 2021-04-10 07-38-48](https://user-images.githubusercontent.com/46370687/114267421-d70b7900-99d1-11eb-8153-366ae65c7ce3.png)

**Desktop**
 - OS: Fedora 33 (Workstation Edition)
 - Installation Method: sudo snap install insomnia
 - App Version V2021.2.2

**Comment by develohpanda** [comment]
This looks similar to https://github.com/Kong/insomnia/issues/2614 and is an issue with the snap package :( As per a comment in that issue, it worked for a user when they downloaded the AppImage directly, which you can try from here: https://github.com/Kong/insomnia/releases/tag/core%402021.2.2.

In any case, because there is further discussion in #2164 I will close this as duplicate. Thank you for reporting! 🙌🏽
