### ISSUE TITLE
"Send Request" does not cancel a pending Request

### ISSUE THREAD

**Issue by shrink** [getinsomnia/insomnia#3277]
**Describe the bug**

A pending Request continues to wait for a Response from the server in the background even after another Request is sent. As a consequence, if the second Request completes first, the Response will be displayed until the eventual Response to the first Request replaces it. 

I think there's a couple of options to solve this:

1. `Send Request` could cancel any pending requests
2.  `Send Request` could be disabled while there is a pending Request
3.  The original Request is allowed to complete, but the Response is added to the Response history without rendering in the current Request's Response frame

Personally, I think the first option is best because by clicking `Send Request` while a Request is pending, the user is communicating they _don't_ want the Pending Request to complete. I have created this as an issue rather than as a Pull Request because I am not sure which option most meets the expectations of other users. I am happy to submit a Pull Request for the chosen solution.

**To Reproduce**

1. Send a Request to an endpoint that will take `n` seconds to return a Response
2. Send a second Request to an endpoint that will take less than `n` seconds to return a Response
3. Observe Response to second Request is displayed
4. ...`n` seconds pass
5. Observe Response to first Request is displayed in place of the second Request's Response

This reproduction can be performed using the [`httpstat.us`](https://httpstat.us) service:

1. URL `https://httpstat.us/400?sleep=10000` Enter URL -> Send Request
2. URL `https://httpstat.us/200?sleep=1000` Replace previous URL -> Send Request

**Expected behavior**
 
Pending Request is cancelled when I click "Send Request".

**Screenshots**

![image](https://user-images.githubusercontent.com/349689/114427878-7340a600-9bb3-11eb-9087-aa33a6dc53f7.png)

![image](https://user-images.githubusercontent.com/349689/114428743-79835200-9bb4-11eb-9ab5-e5037db9da31.png)

**Desktop (please complete the following information):**
 - macOS Big Sur 11.2.3 (20D91)
 - download via insomnia.rest

```
Version: Insomnia 2021.2.2
Release date: 3/29/2021
OS: Darwin x64 20.3.0
Electron: 9.3.5
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.73.0 OpenSSL/1.1.1j zlib/1.2.11 brotli/1.0.9 zstd/1.4.9 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0
```

**Comment by develohpanda** [comment]
Thank you for reporting this! I was able to reproduce it.

To me the bug lies in the fact that once an older request completes, it overwrites the response pane, which it shouldn't, and should complete in the background. So IMO the least restrictive solution would be option 3. If someone wants to send a request multiple times in quick succession without waiting for a response, they still can, but the response shown will always be the last request to be fired.

Food for thought: looking at other tools they seem to change the "send" button to "cancel", similar to the GRPC implementation in Insomnia - which is option 2 from the list above.

Open to other ideas here as well, though! I'll raise with the team too, to see what they think.

**Comment by develohpanda** [comment]
I've started a discussion [here](https://github.com/Kong/insomnia/discussions/3291) to seek some community feedback for this 🙂

**Comment by wdawson** [comment]
Closing this issue in favor of the discussion above ^
