### ISSUE TITLE
Does it surport node version 6.11?

### ISSUE THREAD

**Issue by shangxinbo** [getinsomnia/insomnia#329]
I need use node LTS ,but the latest LTS node version is 6.11.does it surport version 6.11？

**Comment by gschier** [comment]
I know you already closed this, but I thought I'd follow up anyway.

Since Insomnia uses [Electron](https://electron.atom.io/), it is restricted to the version of NodeJS that Electron is bundled with (currently 7.4). It will probably work to use 6.11 to build/run/test the app, however, there may eventually be some compatibility issues if a test (for example) makes use of newer features not available in older Node versions.
