### ISSUE TITLE
Implement a response time calculation to test API response latency.

### ISSUE THREAD

**Issue by nknapp3** [getinsomnia/insomnia#3297]
**Is your feature request related to a problem? Please describe.**
I would like to test my API endpoints latency by adding a test that measures it. Currently, Postman uses responseTime: 

```
pm.test("Response time is less than 1000ms", function () {
    pm.expect(pm.response.responseTime).to.be.below(1000);
});
```

**Describe the solution you'd like**
After talking to @reynolek  - the solution would be seem to be as follows: 

"It would need a variable added to the request config (a start time), and then once the request has returned, calculate the time between return and start time in milliseconds, and include that in the data being returned by send."

**Additional context**
Looking to move away from Postman, so hoping to have this added. Thank you!

**Comment by reynolek** [comment]
The method that I believe needs updating is here: https://github.com/Kong/insomnia/blob/fa64e6b5e896c2d043499b6b937e1a8f616d5346/packages/insomnia-testing/src/run/insomnia.js#L70

Axios (the promise library we use) doesn't support response time out of the box so it would have to be done manually through request config and then calculating the time once the response has come back.

**Comment by amaaniqbal** [comment]
I can try working on this issue @reynolek. In which format is the response time desired? 
I suppose returning `responseTime` in seconds rounded to 3 decimal places would be recommended.

**Comment by reynolek** [comment]
I would say milliseconds would be the preferred measurement, as often you are intending an API call to return in milliseconds for SLAs.

And an update from my original comment, this is no longer goes through the Axios library. @develohpanda will know specifics but I believe this call functionality was moved to insomnia's network layer using `send_request`, but im fuzzy on details.

**Comment by amaaniqbal** [comment]
@develohpanda @gschier Could you please elaborate on the specifics for this issue?

**Comment by develohpanda** [comment]
Hi @amaaniqbal!

When writing a unit test, the `insomnia` class instance for Mocha is set up here: https://github.com/Kong/insomnia/blob/5f4c19da35e90ffa2f3ae27e9b309ee48f9d4e16/packages/insomnia-testing/src/run/run.ts#L30-L30

This class will use a `sendRequest` callback if it exists in the options sent to the constructor, and use axios _as a fallback_. https://github.com/Kong/insomnia/blob/5f4c19da35e90ffa2f3ae27e9b309ee48f9d4e16/packages/insomnia-testing/src/run/insomnia.ts#L78-L80

That options object in the constructor of `Insomnia`, is sent either from `insomnia-app` or `insomnia-inso`:
https://github.com/Kong/insomnia/blob/6e073c8a38f4b9c783786e3a2c149a10c7d38dec/packages/insomnia-app/app/ui/components/wrapper-unit-test.tsx#L279-L283

https://github.com/Kong/insomnia/blob/5f4c19da35e90ffa2f3ae27e9b309ee48f9d4e16/packages/insomnia-inso/src/commands/run-tests.ts#L97-L103

This means, because all of the entry points in the app and the CLI actually provide the `sendRequest` callback, axios is never consumed. (As an aside, we can likely remove axios, it was a remnant of the initial build PoC)

Finishing off the links, `sendRequest` is defined here, exposing Insomnia's networking logic as a standalone library: 
https://github.com/Kong/insomnia/blob/6e073c8a38f4b9c783786e3a2c149a10c7d38dec/packages/insomnia-app/app/common/send-request.ts#L41-L62

The response returned from that `sendAndTransform` function is what is available to you in unit tests.

---

It appears that the elapsed time for a request is already available on the `res` response object in `sendAndTransform`! So if you add it here, in theory you should have the elapsed time available for you in unit tests
<img width="934" alt="image" src="https://user-images.githubusercontent.com/4312346/121259233-f48e8d80-c903-11eb-907a-e38495a95740.png">

> In which format is the response time desired? I suppose returning responseTime in seconds rounded to 3 decimal places would be recommended.

In terms of precision, I would stick with returning the time in ms with no decimal places, since working in milliseconds is fairly standard in JS.

**Comment by amaaniqbal** [comment]
Thanks a lot for the detailed overview @develohpanda! I will try creating a PR for this today itself.
