### ISSUE TITLE
[Feature Request] One click request creation

### ISSUE THREAD

**Issue by JayAndCatchFire** [getinsomnia/insomnia#331]
I often find myself wanting to quickly create a new request to test something out.  My usual workflow involves pasting a curl request from Chrome's devtools into Insomnia, so I don't spend a lot of time handcrafting the request.

But it takes at least three clicks to create a new request.  One on the "add" icon next to the filter text input.  One on the "New Request" menu item.  One on the "Create" button in the "New Request" modal.  I just discovered that you can bring this down to two interactions by using the command-n keyboard command to open the "New Request" modal.

Can you somehow bring this down to one click or one interaction?  Is the "New Request" modal really necessary?

**Comment by gschier** [comment]
Currently, Insomnia is geared towards a more "project" based approach, which is why the initial name prompt exists. It's difficult to say whether or not it is _actually_ a necessary step for most people, but it's difficult to change such a fundamental part of the user experience at this stage without a significant amount of evidence for the alternative. Maybe there could be a keyboard shortcut specific to creating a new request from the contents of the clipboard?

There has been some discussion on making Insomnia more debug-friendly (see #177) but nothing has been decided upon yet.

As for the "single click" option... after pressing command+n, you can press Enter to proceed immediately using the default request settings, essentially making it a single keyboard shortcut.
