### ISSUE TITLE
Error pushing to Azure DevOps repository

### ISSUE THREAD

**Issue by lcravopt** [getinsomnia/insomnia#3317]
**Describe the bug**
I've created a repository on my company server Azure DevOps and created a personal access token. After that I configured the repository on my Document project. Until here everything went without any problem.

After I created a commit and when I try to push I getting the error message:
"Cannot read property 'request' of undefined"

**Stack Trace**
TypeError: Cannot read property 'request' of undefined
    at httpPlugin (file:///C:/Users/LMC/AppData/Local/insomnia/app-2021.2.2/resources/app.asar/bundle.js:187270:19)
    at async Function.discover (C:\Users\LMC\AppData\Local\insomnia\app-2021.2.2\resources\app.asar\node_modules\isomorphic-git\dist\for-node\isomorphic-git\index.js:6453:15)
    at async Object.getRemoteInfo (C:\Users\LMC\AppData\Local\insomnia\app-2021.2.2\resources\app.asar\node_modules\isomorphic-git\dist\for-node\isomorphic-git\index.js:8429:20)
    at async GitVCS.canPush (file:///C:/Users/LMC/AppData/Local/insomnia/app-2021.2.2/resources/app.asar/bundle.js:31624:24)
    at async GitSyncDropdown._handlePush (file:///C:/Users/LMC/AppData/Local/insomnia/app-2021.2.2/resources/app.asar/bundle.js:203519:17)

**To Reproduce**
1. Open a Document project
2. Configure Azure DevOps repository
3. Commit 
4. Push

**Expected behavior**
Items are pushed to repository

**Screenshots**
![Error](https://user-images.githubusercontent.com/82532766/115862639-48184b00-a42c-11eb-8117-2fd445428862.png)
![Repository](https://user-images.githubusercontent.com/82532766/115862645-49e20e80-a42c-11eb-8181-fc058daec83d.png)
![Insomnia_Repo](https://user-images.githubusercontent.com/82532766/115862650-4babd200-a42c-11eb-847d-56edb251cb6f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Installation Method: download from https://insomnia.rest/download
 - App Version: Insomnia 2021.2.2

**Additional context**

**Comment by filfreire** [comment]
Hi @lcravopt sorry for us not getting back to this issue sooner.

I've tried reproducing the steps you mention here and was not able to (at least on Azure Devops in the cloud). 

- Could it be that your company's Azure Devops instance has some more protection in order to Git Clone?
- Would you mind trying with our [latest app version ](https://github.com/Kong/insomnia/releases/tag/core%402022.3.0)? We've been doing improvements on Git Sync for a while that might have helped mitigate this in the meantime.


I created an empty repo on Azure Devops in the cloud, used the auto-generated clone password as personal access token:
<img width="477" alt="Screen_Shot_2022-05-10_at_08_11_40" src="https://user-images.githubusercontent.com/11976836/167570676-8b35d65b-d2d4-4e3c-a2c0-bdd48e649abd.png">

And then was able to create some requests and push them to the repository:
<img width="1562" alt="Screen Shot 2022-05-10 at 08 02 24" src="https://user-images.githubusercontent.com/11976836/167571030-a9ba0fb7-487c-4633-8ab3-305837cf8524.png">

**Comment by filfreire** [comment]
@lcravopt I'm going to go ahead and close this one, please re-open if you are still facing issues and share more details.

In the meantime feel free open other issues you find 👍
