### ISSUE TITLE
[Install] Insomnia Installation Security Risk

### ISSUE THREAD

**Issue by usuresh80** [getinsomnia/insomnia#335]
when I try to install  insomnia through windows installer Symantec Endpoint Protection Client is not allwoing , Here is the error , Do you know why ?

Security Risk Found!WS.Reputation.1 in File: c:\users\suppala\downloads\insomnia.setup.5.4.0.exe by: Auto-Protect scan.  Action: Quarantine succeeded.  Action Description: The file was quarantined successfully.

**Comment by gschier** [comment]
I've had other users report this before. 

It seems that a lot of antivirus programs automatically block apps that do not have enough reputation yet (not many installs). I'm not sure there is anything I/you can do about this except mark Insomnia as "safe" in the antivirus program. This should help it get whitelisted for other users too.

**Comment by SylwesterZarebski** [comment]
EV Code Signing should help, but it is very costly way:
https://blogs.msdn.microsoft.com/ie/2012/08/14/microsoft-smartscreen-extended-validation-ev-code-signing-certificates/

**Comment by gschier** [comment]
I started using a DigiCert code signing certificate a few months ago (hoping to solve this) but I guess it didn't help. I could have gone for an EV but, apparently, you need need to plug in a designated USB device to use it, meaning Insomnia wouldn't be able to sign on a CI server. 

Also, I'm not sure if this is true, but I think the reputation resets every new version because the installer file changes. If anyone with a Windows development background can chime in, that would be great.

I'm closing this one for now. I can re-open if anyone has any ideas on how to get around this.
