### ISSUE TITLE
Insomnia does not import all methods from wsdl

### ISSUE THREAD

**Issue by TahirJalilov** [getinsomnia/insomnia#3356]
**Describe the bug**
I have a local WSDL URL. When I import it to the SoapUI application, all methods imports successfully. But when I import data from the same URL to Insomnia I realize that not all methods imports

**To Reproduce**
1. Go to 'Import data'
2. Click on 'Import from url'

**Expected behavior**
All methods from WSDL must be imported

**Screenshots**
![image](https://user-images.githubusercontent.com/43037294/117054905-a4804200-ad2b-11eb-93c0-8aafe9b79435.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Installation Method: exe
 - App Version v2021.3.0

**Comment by filfreire** [comment]
Hi @TahirJalilov, thank you for reporting this!

It has been a while since you reported this issue, do you still notice problems?

I would recommend you try using our latest beta release, [2022.3.0-beta.3](https://github.com/Kong/insomnia/releases/tag/core%402022.3.0-beta.3), it has some minor fixes for our WSDL importer.

If possible, it would help if you can share some example `.wsdl` file where you are able to reproduce the problem.

**Comment by TahirJalilov** [comment]
Good day @filfreire Unfortunately, I left that job and do not have access to the .wsdl file ((I can't reproduce the problem

**Comment by filfreire** [comment]
Hi @TahirJalilov, no worries, feel free to report other issues you may find.

We've recently fixed WSDL importers on our [major release](https://insomnia.rest/changelog#2022.3.0), so it could have been the case it was the same problem.

Feel free to report any issues you may find in the meantime 👍
