### ISSUE TITLE
[Feature Request] Export and import requests as curl.

### ISSUE THREAD

**Issue by Euphorbium** [getinsomnia/insomnia#336]
## Overview
Chrome browser has a feature to copy a request as curl. It would be great if it was possible to then import this request into insomnia and have all of the fields populated. And it would be great if it was possible to get the same export feature as in chrome, right click on request in insomnia and choose copy as curl.

**Comment by gschier** [comment]
Well @Euphorbium, I have good news for you. Both of these are already possible!

You can import a Curl command by pasting it into the current request's URL bar, and you can export as curl using the Generate Code feature.

![image](https://user-images.githubusercontent.com/587576/27653439-e32e30bc-5bf3-11e7-97ea-45dc04963cd9.png)

Let me know if you have any questions.

**Comment by gschier** [comment]
@Euphorbium any ideas on how to make that feature more obvious?

**Comment by gschier** [comment]
Pasting Curl is referenced in the Data tab in Preferences. It might be worth having a dedicated button during the "Create Request" flow to paste a curl command, though. 

![image](https://user-images.githubusercontent.com/587576/27702030-8cdd1d30-5cb7-11e7-8211-018f71a6034c.png)

Also, that's a good point about curl not being code. I agree with that statement as well.

**Comment by gschier** [comment]
Just added a couple things

![image](https://user-images.githubusercontent.com/587576/27704026-03a32530-5cbe-11e7-8526-3a2c72e3d7b9.png)
![image](https://user-images.githubusercontent.com/587576/27704040-0bb8b42e-5cbe-11e7-865d-b8e2155ae5af.png)

**Comment by jeffreydwalter** [comment]
@gschier sorry to comment on a closed issue, but I was wondering if it is or would be possible to export the authentication cURL?

**Comment by dginovker** [comment]
Very confused. I keep pasting my cURL into the URL bar but it doesn't do anything special
![image](https://user-images.githubusercontent.com/32943174/171661784-138de93b-5eb0-44b9-b61f-aa4ab228f3c2.png)

**Comment by savikko** [comment]
> @Euphorbium any ideas on how to make that feature more obvious?

I was searching for this feature and this issue was where I learned how this works. Of course now it is clear for me, but it was not before. First google result is some video, then Insomnia docs (which does not yet mention this feature) and third was this issue.

Created little PR on this: https://github.com/Kong/insomnia-docs/pull/103

Pasting to URL works flawlessly for me , both "cmd" and "bash" flavors.
@dginovker : please provide curl command which does not work, might help solving the issue.

But just as an idea:
![image](https://user-images.githubusercontent.com/7020294/173011090-6316a925-d7b6-4695-91f1-4a9737d29071.png)

As a user I normally would like to add new request from copied cURL, so that dropdown item would create new request and get content from clipboard.

**Comment by adrian-skybaker** [comment]
As well as not being obvious, pasting into the url bar results in really poor error handling / feedback if there is a problem with the curl. It also looks like a real mess if the curl is large + multiline.

Being able to paste into a dedicated multiline text area with clear feedback if the command can't be parsed would be preferable.

**Comment by sellrock-de** [comment]
Today i faced with the problem, that the pasted curl request copied from chrome, can't import above the url bar
