### ISSUE TITLE
[openapi-2-kong] Key-auth plugin is missing from generated declarative config

### ISSUE THREAD

**Issue by jacky96623** [getinsomnia/insomnia#3389]
**Describe the bug**
DecK generated by Insomnia does not contain a global key-auth plugin.

**To Reproduce**
1. Install the Insomnia IDE and then open it
2. Create a `Design Document`
3. Paste the following OpenAPI to the code area:
    ```yaml
    openapi: 3.0.1
    info:
      title: test-openapi
      version: 1.0.0
    servers:
      - url: http://localhost
    paths:
      /some-path:
        get:
          tags:
            - get
          summary: get response
          description: Returns a single pet
          operationId: get response
          responses:
            '200':
              description: successful operation
              content: {}
    components:
      securitySchemes:
        ApiKeyAuth:
          type: apiKey
          in: header
          name: X-API-Key
    security:
      - ApiKeyAuth: []
    ```
4. Click on `Declarative Config` generator and then the following DecK yaml is shown:
    ```yaml
    _format_version: "1.1"
    services:
      - name: test_openapi
        protocol: http
        host: test_openapi
        port: 80
        path: /
        plugins: []
        routes:
          - tags:
              - OAS3_import
            name: test_openapi-get_response
            methods:
              - GET
            paths:
              - /some-path$
            strip_path: false
        tags:
          - OAS3_import
    upstreams:
      - name: test_openapi
        targets:
          - target: localhost:80
            tags:
              - OAS3_import
        tags:
          - OAS3_import
    ```

**Expected behavior**
The DecK generated should contains key-auth plugin.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - App Version: v2021.3.0

**Additional context**
I am not sure if it is an expected behaviour, but if this sounds to be an issue to the team - just IMO, the cause seems to be at <https://github.com/Kong/insomnia/blob/5f4c19da35e90ffa2f3ae27e9b309ee48f9d4e16/packages/openapi-2-kong/src/declarative-config/services.ts#L127>, as the code does not contain a section to generate global plugins while in contrast the code in k8s folder does.

Thanks for any help.

**Comment by rLitto** [comment]
I verified the same behaviour, it only works at route level, not at root level

**Comment by Kovbasiuk-Mykhailo** [comment]
+1 there is a bug in the code where plugins are generated. You are calling generateSecurityPlugins only in a loop that iterates over paths array

**Comment by filfreire** [comment]
Hi @jacky96623, 

I was trying to debug this issue and I noticed that on [openapi-2-kong documentation](https://github.com/Kong/insomnia/tree/develop/packages/openapi-2-kong#generic-plugins), it would appear folks need to define the `x-kong-plugin-key-auth` object on their OpenAPI spec so that Insomnia (or Inso CLI) will return the plugin information on Declarative Config generation.

I've tried that and it seems to do the trick and add the plugin. Check my example section bellow.

BUT, for instance, if we try the example you provided, the generated Kong config on the other hand does mention that plugin without even needing the `x-kong-plugin-key-auth` part on the OAS:

![Image](https://user-images.githubusercontent.com/11976836/181496794-00be037e-7f05-4012-af98-b1f5f848fbf6.png)

So perhaps we do have a bug in there or at least we should follow a similar behaviour for Declarative configs.

Tagging @Tieske - any suggestions or ideas what the default or accepted behaviour should be?


## Example 

Spec:
```yaml
openapi: 3.0.0
info:
  title: 'test'
  version: 1.0.0
  x-kubernetes-ingress-metadata:
    name: insomnia-api                          # Kubernetes Ingress document name
    annotations:                                # Annotations to automatically apply
      'example': 'example'
x-kong-plugin-custom-global:                    # Global plugin to always be applied
  name: custom-global
  enabled: true
  config:
    key_in_body: false
servers:
  - url: http://one.insomnia.rest/v1
  - url: http://two.insomnia.rest/v2
    x-kong-plugin-custom-server:                # Server plugin to be applied to documents for this server
      name: custom-server
      enabled: true
paths:
  '/path':
    post:
      summary: Some functionality
      responses:
        '200':
          description: successful operation
          content: {}
  '/another-path':
    get:
      summary: Some functionality
      responses:
        '200':
          description: successful operation
          content: {}
      x-kong-plugin-key-auth:                   # Operation plugin on GET /another-path
        name: key-auth
        enabled: true
        config:
          key_names: [api_key, apikey]
          key_in_body: false
          hide_credentials: true
```

Shows the plugin information in the generated declarative config:
![Image](https://user-images.githubusercontent.com/11976836/181496156-1f9548e1-a574-40d4-99ff-5c47111b00f3.png)

**Comment by Tieske** [comment]
As reference for future us: 

Using `x-kong-plugin-key-auth` is the generic way of adding plugins. This will work with any plugin. So it is different from the user expectations that the generator would take the `security` directives into account and would then generate the proper `key-auth` config automatically.

The difference being that using `security` (the OAS concept) would not require the user to have any knowledge about Kong whatsoever. Whereas using the plugin directive, would require that knowledge.
