### ISSUE TITLE
[Bug] Json Preview Filter doesn't work properly with Russian symbols.

### ISSUE THREAD

**Issue by AgentFire** [getinsomnia/insomnia#3415]
The title says it: there is a bug in the JSON preview panel.

If the JSON is perfectly valid, but uses Russian (assuming any non-English) symbols/letters as keys, then the JSON filter (at the bottom right corner of the UI) in the Visual Preview panel simply shows empty result if any Russian symbols are used in the filter's text field.

Unlike some other tools (like https://jsonpath.com/), which work perfectly.

**Comment by filfreire** [comment]
Hello @AgentFire, thank you for reporting this issue!

We have tried reproducing it, but it seems this problem is no longer happening in [recent versions of Insomnia (example)](https://github.com/Kong/insomnia/releases/tag/core%402022.4.2):

![Screenshot 2022-06-23 at 14 32 38](https://user-images.githubusercontent.com/11976836/175311580-4064e109-6cac-4620-b631-5cea1867aa58.png)
![Screenshot 2022-06-23 at 14 32 22](https://user-images.githubusercontent.com/11976836/175311587-79bf63bd-30c6-47ec-9eec-ae870f565e2c.png)

Feel free to report any other issues you come across.
