### ISSUE TITLE
[Improvement] Avoid placing a shortcut on the desktop during each update

### ISSUE THREAD

**Issue by isobit** [getinsomnia/insomnia#348]
## Overview
- `Insomnia Version:` 5.3.6
- `Operating System:`  Windows 10
- `Summary: `  On every update, Insomnia places a shortcut on the Windows desktop. This is frustrating for users that don't want a desktop shortcut, since not only do they have to remove it after the first installation, but every time Insomnia auto-updates.

## How To Reproduce
1. Install Insomnia on Windows
2. Delete desktop shortcut
3. Wait for update
The desktop icon will reappear following an update to Insomnia.

## Other Notes

The issue seems to caused by the behavior of [`electron-squirrel-startup`](https://github.com/mongodb-js/electron-squirrel-startup/blob/master/index.js#L21).

**Comment by gschier** [comment]
I've heard this complaint from a few other Windows users, but wasn't sure which part of the install/update process was causing it. Thanks for pointing me to `electron-squirrel-startup`. I found the line that's causing it: https://github.com/mongodb-js/electron-squirrel-startup/blob/master/index.js#L20

Since that module is so small (1 file), it's probably worth pulling it into the Insomnia project and making the modification directly. I'll get this done for the next release.

**Comment by thejonwithnoh** [comment]
I had commented on issue [#44](https://github.com/getinsomnia/insomnia/issues/44#issuecomment-337584079), which is a duplicate of this issue, without realizing this ticket existed as well.

I've just been updated to version 5.11.7, and it still created a desktop icon.  Though I see this issue was auto-closed by the stale bot.

Should I open a new ticket?  Should this one be reopened?  It doesn't seem like the solution mentioned in [an earlier comment](https://github.com/getinsomnia/insomnia/issues/348#issuecomment-313884608) was applied, or was effective.

**Comment by gschier** [comment]
I reopened #44. I haven't had time to work on it yet but if you'd like to give it a shot I'd be glad to offer guidance 👍
