### ISSUE TITLE
After pasting curl into address bar, deleting results in the cursor losing focus

### ISSUE THREAD

**Issue by OllieCrook** [getinsomnia/insomnia#3485]
**Description**
After creating or editing a request by pasting a curl into the address bar the cursor will lose focus after pressing the backspace key. You can regain focus by pressing the tab key or by clicking into the address bar again. After that, there are no issues deleting.

**To Reproduce**
1. Click the plus icon
2. Click 'New Request'
3. Click 'Create'
4. Click into the address bar
5. Paste a curl: `curl 'https://example.com/' --compressed`
6. Press backspace

**Expected behavior**
I expect the cursor to not lose focus on the address bar when deleting.

**Screenshots**
https://thumbs.gfycat.com/CloudyAdventurousGuineafowl-mobile.mp4

**Desktop (please complete the following information):**
 - OS: macOS 11.4
 - Installation Method: Homebrew
 - App Version 2021.3.0

**Additional context**
This bug is an extension of #3002 and #3118.

If you use the workaround of pasting the curl twice in order to get Insomnia to properly process it then the cursor also loses focus.

My current workflow is: Paste curl -> select all -> paste curl -> backspace -> readd last character -> select domain -> replace with env variable -> send

I would like it to be: Paste curl -> select domain -> replace with env variable -> send

**Comment by dimitropoulos** [comment]
Thank you for the reproduction steps.  I was able to reproduce.

**Comment by hernancerm** [comment]
Hi, I want to work on this issue, is it ok? I've inspected the app with React dev tools and it seems that the input component of the address bar is [CodeEditor](https://github.com/Kong/insomnia/blob/develop/packages/insomnia-app/app/ui/components/codemirror/code-editor.tsx), so I could start looking there.

Though it would be my first time contributing to Insomnia so I would appreciate any pointers.

**Comment by dimitropoulos** [comment]
@HerCerM I sent you an email to have a call and help you get started with it.

**Comment by hernancerm** [comment]
Hi @dimitropoulos, I have done some research in the code and want to share my findings. Also and unfortunately, I won't be able to continue with this issue. However, I've created a draft [PR](https://github.com/Kong/insomnia/pull/3808#issue-688281492) if anyone would like to followup

### What causes the bug

I have learned that the input loses focus because importing a request prepares a forceful update of the request pane. I use the word _prepares_, since the update doesn't happen immediately after the import.

From what I gather, this forceful update is achieved by **changing the key** of the element to update, which triggers an unmount / mount, making the cursor lose focus. The key of the address bar component (`OneLineEditor`) looks like the following:

```
1626131715669::req_2915e5a89f76416bbe123a172df0ed47
```

From [this line](https://github.com/Kong/insomnia/blob/60ef1a83f97fa1e9cf79e9eb29ffe09362ca6e4e/packages/insomnia-app/app/ui/components/panes/grpc-request-pane/index.tsx#L70), the first number seems to be the `forceRefreshKey`, while the part after the `::` is the request id.

The part of the key which is changed corresponds to the `forceRefreshKey`. It is changed by [this call to `_forceRequestPaneRefresh`](https://github.com/Kong/insomnia/blob/60ef1a83f97fa1e9cf79e9eb29ffe09362ca6e4e/packages/insomnia-app/app/ui/components/wrapper.tsx#L167). I attach a video showing when the change occurs:

https://user-images.githubusercontent.com/42811720/125369469-e936e380-e341-11eb-9ab7-0bf394ca75db.mov

### Additional information

- The focus is lost in the address bar also after doing the double paste as described in #3002. Since the key of  `OneLineEditor` changes after the second paste, I think the cause of the loss of focus is the same.
- I have also been able to reproduce the bug by importing a request in HTTP Archive Format (HAR), following the same steps as with cURL. I suspect the bug would also be present with other formats.

<details>
<summary>Example HAR to reproduce the bug</summary>

```json
{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "Firefox",
      "version": "89.0.2"
    },
    "browser": {
      "name": "Firefox",
      "version": "89.0.2"
    },
    "pages": [
      {
        "startedDateTime": "2021-07-12T17:59:42.880-05:00",
        "id": "page_1",
        "title": "React lifecycle methods diagram",
        "pageTimings": {
          "onContentLoad": 1052,
          "onLoad": 1553
        }
      }
    ],
    "entries": [
      {
        "pageref": "page_1",
        "startedDateTime": "2021-07-12T17:59:42.880-05:00",
        "request": {
          "bodySize": 0,
          "method": "GET",
          "url": "https://projects.wojtekmaj.pl/react-lifecycle-methods-diagram/",
          "httpVersion": "HTTP/3",
          "headers": [
            {
              "name": "Host",
              "value": "projects.wojtekmaj.pl"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0"
            },
            {
              "name": "Accept",
              "value": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
            },
            {
              "name": "Accept-Language",
              "value": "es-MX,es;q=0.8,en-US;q=0.5,en;q=0.3"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, br"
            },
            {
              "name": "Alt-Used",
              "value": "projects.wojtekmaj.pl"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Upgrade-Insecure-Requests",
              "value": "1"
            },
            {
              "name": "Pragma",
              "value": "no-cache"
            },
            {
              "name": "Cache-Control",
              "value": "no-cache"
            },
            {
              "name": "TE",
              "value": "Trailers"
            }
          ],
          "cookies": [],
          "queryString": [],
          "headersSize": 479
        },
        "response": {
          "status": 200,
          "statusText": "OK",
          "httpVersion": "HTTP/3",
          "headers": [
            {
              "name": "content-type",
              "value": "text/html"
            },
            {
              "name": "last-modified",
              "value": "Mon, 21 Jun 2021 07:34:24 GMT"
            },
            {
              "name": "etag",
              "value": "\"3d4-60d04100-4e616530cf26f528;br\""
            },
            {
              "name": "accept-ranges",
              "value": "bytes"
            },
            {
              "name": "content-encoding",
              "value": "br"
            },
            {
              "name": "vary",
              "value": "Accept-Encoding,User-Agent"
            },
            {
              "name": "content-length",
              "value": "332"
            },
            {
              "name": "date",
              "value": "Mon, 12 Jul 2021 22:59:43 GMT"
            },
            {
              "name": "server",
              "value": "LiteSpeed"
            }
          ],
          "cookies": [],
          "content": {
            "mimeType": "text/html",
            "size": 980,
            "text": "<!doctype html><html lang=\"en-US\"><head><meta charset=\"utf-8\"/><meta name=\"viewport\" content=\"width=720\"><meta property=\"og:type\" content=\"website\"/><meta property=\"og:title\" content=\"React Lifecycle Methods diagram\"/><meta property=\"og:url\" content=\"https://projects.wojtekmaj.pl/react-lifecycle-methods-diagram/\"/><meta property=\"og:image\" content=\"https://projects.wojtekmaj.pl/react-lifecycle-methods-diagram/ogimage.png\"/><meta property=\"og:description\" content=\"Fully interactive and accessible React Lifecycle Methods diagram.\"/><meta name=\"description\" content=\"Fully interactive and accessible React Lifecycle Methods diagram.\"><title>React lifecycle methods diagram</title><link rel=\"icon\" href=\"favicon.ico\"/><script defer=\"defer\" src=\"487.74756c5b.js\"></script><script defer=\"defer\" src=\"577.400cc057.js\"></script><script defer=\"defer\" src=\"src.d58ba3eb.js\"></script><link href=\"src.d58ba3eb.css\" rel=\"stylesheet\"></head><body><div id=\"react-root\"></div></body></html>"
          },
          "redirectURL": "",
          "headersSize": 285,
          "bodySize": 617
        },
        "cache": {},
        "timings": {
          "blocked": 0,
          "dns": 0,
          "connect": 0,
          "ssl": 0,
          "send": 0,
          "wait": 176,
          "receive": 0
        },
        "time": 176,
        "_securityState": "secure",
        "serverIPAddress": "195.78.66.116",
        "connection": "443"
      }
    ]
  }
}
```
</details>

**Comment by develohpanda** [comment]
Nice findings @HerCerM, I am very familiar with this concept of "force refresh the app using a key" and it's side-effects and we're trying to move away from it slowly. For now I'm not certain what the best way forward is but your initial attempt does look decent. Thank you for working through it 🙏🏽

**Comment by hernancerm** [comment]
You're welcome :) I found @dimitropoulos' help very useful to reach my findings — thank you Dimitri

**Comment by OllieCrook** [comment]
This seems like it has been fixed. Worth testing on other machines along with the linked issues in my post. Could be able to close three issues!
