### ISSUE TITLE
[Bug] Generated json content has newline, breaking curl

### ISSUE THREAD

**Issue by simplesteph** [getinsomnia/insomnia#375]
## Overview
- `Insomnia Version:` 5.6.3
- `Operating System:`  Mac OS X
- `Summary: ` Multiline JSON break the "generate code" functionality

## How To Reproduce

1. Create a POST query with JSON payload
2. Make the JSON payload multilines
3. Right click and generate `curl`
4. The data will have newlines, which isn't valid json `--data '{\n"deviceId":"20000055"}`

**Comment by gschier** [comment]
Insomnia uses [`httpsnippet`](https://github.com/Mashape/httpsnippet) to generate code snippets. I opened an issue for this specific issue a while ago but have not gotten a response yet. I should probably just submit a PR, as it should be a pretty easy fix... https://github.com/Mashape/httpsnippet/issues/96

If you're interested in contributing the fix, let me know. Otherwise, I'll try to get to it when I can.

**Comment by simplesteph** [comment]
probably isn't worth fixing at the httpsnippet level because that project seems rather inactive?
how about just removing newlines before passing it as an argument to httpsnippet, within insomnia?

**Comment by gschier** [comment]
I'd like to avoid altering request content without the user knowing. Even though removing newlines would not break JSON, it would go against the user's expectations. Also, there _are_ whitespace-dependent content-types where stripping newlines could change the meaning.

Since snippet generation is a fairly major feature of Insomnia, it's probably worth maintaining a custom fork if a pull-request is not accepted.

**Comment by simplesteph** [comment]
@gschier makes sense. End of the day, I understand there are tradeoffs. Hope you can find the easiest / cleanest solution

**Comment by gschier** [comment]
@simplesteph I've made a custom fork so everything should be working as expected in the next release.
