### ISSUE TITLE
Impossible to delete remote collection

### ISSUE THREAD

**Issue by gpasq** [getinsomnia/insomnia#3889]
**There is no way to delete a remote collection**
I have a remote collection that was created previously.  There appears to be no way to delete it, either from the tool or from the half-baked website.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Installation Method: [e.g. homebrew]
 - App Version 2021.4.1

**Comment by DMarby** [comment]
Hi there @gpasq!

Apologies for the confusion, you can delete a remote collection by entering the collection and using the "Delete Collection" button in the Sync menu to the top right:
![image](https://user-images.githubusercontent.com/174626/128741258-f97875fb-4d21-4812-bdd7-3f46a0d0071b.png)
Note that this requires you to have pulled the collection so that it exists locally.

If you run into any further issues with the sync features, please send an email to support@insomnia.rest and we'll be able to better assist you.

**Comment by gpasq** [comment]
Got it, thanks.  The problem was that I didn't have the collection locally.
