### ISSUE TITLE
Less performance using "Preview" than "source code", even if the output from both options is the same

### ISSUE THREAD

**Issue by RenatoLopes771** [getinsomnia/insomnia#3901]
**Describe the bug**
When you get a response from your request, you can choose from some options. Say I choose Preview and it's an HTML response, it shows the html page. Source code would show the html code instead.

However, I'm dealing with JSON responses. The output from both options is the exact same, yet using "preview" is less performatic (I can notice by how my computer gets slower when using here).

**To Reproduce**

Make a normal request like you would with insomnia.
Choosing between "preview" and "source code" should be less performatic.
A way to test this is having a big JSON file on a slow system (I was dealing with 2k+ lines of JSON at one point).

**Expected behavior**
There's no wrong behaviour on it it's just less performatic.

**Desktop (please complete the following information):**
 - Linux Ubuntu LTS

**Comment by develohpanda** [comment]
Hi @RenatoLopes771, if I am understanding correctly, you notice that when you first send the request and the response renders with "Preview" it's slow. But when you switch to "Source", it's much faster. Is that right?

What happens if you have "Source" selected, and send the request again. Does the response render slowly? It should behave the same.

This is because for a JSON response, the "Preview" and "Source" code paths render the [exact same thing](https://github.com/Kong/insomnia/blob/853cefca7555cafde1d356f01b3a674f583df118/packages/insomnia-app/app/ui/components/viewers/response-viewer.tsx), thus switching between the two is very fast, but rendering a new response is slow.

We also do have [safety nets](https://github.com/Kong/insomnia/blob/853cefca7555cafde1d356f01b3a674f583df118/packages/insomnia-app/app/ui/components/viewers/response-viewer.tsx) in place to stop rendering altogether if we think the response is too large. Unfortunately "too large" varies for each user because of hardware differences, maybe that needs to be configurable in the future.

Thank you for taking the time to write this up! I will close for now but please re-open if you notice anything adverse 🤗

**Comment by RenatoLopes771** [comment]
> 
> 
> Hi @RenatoLopes771, if I am understanding correctly, you notice that when you first send the request and the response renders with "Preview" it's slow. But when you switch to "Source", it's much faster. Is that right?
> 
> What happens if you have "Source" selected, and send the request again. Does the response render slowly? It should behave the same.

No, weirdly sending the response while I have "source" as default is a little tad faster. I don't know if the two render json differently but that would be my guess. When I noticed this switching between the two did slow it a little too, but the slow isn't for too long in this scenario.
