### ISSUE TITLE
Typo on method list

### ISSUE THREAD

**Issue by LocalHeroPro** [getinsomnia/insomnia#3972]
On left side, on method list we have `PTCH` against `PATCH`.

![image](https://user-images.githubusercontent.com/42643563/131316325-d222f949-2085-46c5-9c33-9f18f97d6fb1.png)

**Comment by develohpanda** [comment]
Thank you for taking the time to report this! 🙌🏽

This is actually by design; anywhere a HTTP Method tag is shown like that, we remove the vowels to keep the tag under four characters in length so that it visually looks consistent.

https://github.com/Kong/insomnia/blob/e6e9e2a748c71f0e28550e0641428396a247b487/packages/insomnia-app/app/common/misc.ts#L124-L138

**Comment by LocalHeroPro** [comment]
Can I turn off that feature?

**Comment by develohpanda** [comment]
Unfortunately that's not something that can be toggled at this stage. Feel free to open a feature request/discussion for it!
