### ISSUE TITLE
Bearer Token is passed as null even after setting the token

### ISSUE THREAD

**Issue by Samad-Shaikh** [getinsomnia/insomnia#4061]
### Is there an existing issue for this?
- [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

Insomnia _Info_ 
>Version: Insomnia 2021.5.3
Release date: 9/13/2021
OS: Windows_NT x64 10.0.19042
Electron: 11.2.3
Node: 12.18.3
V8: 8.7.220.31-electron.0
Architecture: x64

### Last Known Working Insomnia version
not known

### Expected Behavior
a kvp named "Authorization" : "Bearer {token}" should get added in the Headers (_like Postman_)

### Actual Behavior
As seen in Timeline tab, the "authorization: Bearer" is null and there is no Authorization information has been added in the Headers

### Reproduction Steps

1.  Login to an Authenticated API endpoint which provides Bearer Token
2.  Get the bearer Token
3.  Request protected resource that requires Bearer Token
4.  Select Authentication type Bearer Token
5.  Paste the token and _send_
6.  Check the log in Timeline tab
7.  Header tab is empty

### Additional Information
none

**Comment by thewheat** [comment]
Hi @Samad-Shaikh just wanting to confirm, are you seeing the token in the request at all? In my testing the token does get sent but just that there isn't  a new entry in the "Header" section that includes the token that was added

Below is my testing on
```
Version: Insomnia 2021.5.3
Release date: 14/09/2021
OS: Darwin x64 20.6.0
Electron: 11.2.3
Node: 12.18.3
V8: 8.7.220.31-electron.0
Architecture: x64
node-libcurl: libcurl/7.73.0 OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.9 zstd/1.4.9 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.42.0
```

If Bearer is not enabled, request has no authorization header
![image](https://user-images.githubusercontent.com/892961/135743945-09538f0b-3fa8-4161-b791-a817f7dead79.png)

If Bearer is enabled, request has authorization header
![image](https://user-images.githubusercontent.com/892961/135743975-5924bc17-8323-4909-8ff9-98b6ff24e9fc.png)

If Bearer is enabled, request has authorization header, but there is not added entry in the "Header" section
![image](https://user-images.githubusercontent.com/892961/135744177-22dbf0ac-2ea4-46d3-a8bf-ab2282ff7b06.png)


> Expected Behavior
> a kvp named "Authorization" : "Bearer {token}" should get added in the Headers (like Postman)

So strictly look at the "Expected Behaviour", I feel that that sounds more like a feature request that requires a design decision to be made by the creators if that should be done
- I can understand how seeing all headers in the "Header" section could be useful
- But then it is also duplicating information and could lead to complications of which has priority (I guess a simple solution is that any changes made elsewhere could update any headers that would match the value but there could be edge cases such as multiple entries in the headers, how do deal with enabled/disabled entries)

**Comment by Samad-Shaikh** [comment]
Hello!

Thanks for thoroughly repodrucing and testing this issue. I also see the configuration setup is MacOS.

I have tested again on Win setup, in addition, I have created an environment variable for the Access Token instead of pasting the value in the _Token_ field. But as seen in the below image, the Bearer value is null.

![Capture](https://user-images.githubusercontent.com/39049113/135747049-85a9eb53-e836-4305-b6eb-d5f104b14ebb.JPG)

If I set the header manually, it works.

![Capture](https://user-images.githubusercontent.com/39049113/135747333-014fab91-c930-4565-842c-fa96f5498e00.JPG)

**Comment by thewheat** [comment]
I've tried this in a Windows 10 VM and I can't seem to replicate. 😕 

```
Version: Insomnia 2021.5.3
Release date: 9/13/2021
OS: Windows_NT x64 10.0.19043
Electron: 11.2.3
Node: 12.18.3
V8: 8.7.220.31-electron.0
Architecture: x64
node-libcurl: libcurl/7.73.0-DEV OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.9 WinIDN libssh2/1.9.0_DEV nghttp2/1.41.0
```

![image](https://user-images.githubusercontent.com/892961/136532854-e823286f-7846-44e7-975b-321011bdecc2.png)

**Comment by Samad-Shaikh** [comment]
Hi @thewheat 

I have managed to fix the issue.

I have uninstalled the old installation of Insomnia which was recently updated to latest version _on top of_ old version.
I installed a fresh install and it did the trick.

Since there is a less possibility that this issue will get reproduced, I am closing this issue.
