### ISSUE TITLE
[Feature Request] Export request/response history as HAR

### ISSUE THREAD

**Issue by vfaronov** [getinsomnia/insomnia#416]
It would be great if Insomnia could export the request/response history into a [.har](https://en.wikipedia.org/wiki/.har) file.

This would allow integrating Insomnia with other HTTP-related tools (my use case is [HTTPolice](https://github.com/vfaronov/httpolice)).

I can actually see something called `exportHar` in the Insomnia codebase, but I can’t figure out how to invoke it, or whether it’s what I’m looking for at all. In any case, the [Import/Export](https://insomnia.rest/documentation/import-export/) documentation page only mentions *importing* from HAR.

HAR is a poorly defined format, but it’s the best we’ve got, and by navigating certain pitfalls it should be possible to achieve decent interoperability.

**Comment by gschier** [comment]
Hi @vfaronov,

HAR export sounds like a great idea. The `exportHar` function that you found is used to convert the Insomnia `Request` data model into HAR, for use with the [`httpsnippet`](https://github.com/Mashape/httpsnippet) library (for code generation). 

Are you looking to export a single request, or multiple?

**Comment by vfaronov** [comment]
> Are you looking to export a single request, or multiple?

Exporting the entire current history would be a sensible default. That’s what other tools do (browsers’ network consoles, etc.).

And, just to be clear, I’m talking about exporting requests **and** responses. Exporting just requests would not be very useful.

**Comment by Atvaark** [comment]
I implemented HAR export (single workspace/all workspaces) over at https://github.com/Atvaark/insomnia/tree/har-export.
Had to recreate the flow types according to http://www.softwareishard.com/blog/har-12-spec/ to add comment support and prevent exporting insomnia-specific properties.
Requests that haven't been sent yet will be exported as **HTTP/1.1 0 Request not sent** at the moment (instead of being dropped when exporting). How do other tools handle these requests or requests that timed out without a response?

Missing features (per entry) as of now
* *startedDateTime*: All requests "start" at the moment of the export now. But the exports are ordered according to their workspace and metakey, which I honestly prefer.
* *time*: Since it's displayed in the response-pane I guess it's available in the database.
* *timings*: I don't know how accurate the timings are saved right now. The send, wait and receive timings should be enough.

**Comment by gschier** [comment]
@Atvaark that branch looks awesome! Do you want to submit it as a PR? I'd love to merge this in ASAP.

> How do other tools handle these requests or requests that timed out without a response?

I just turned off my wi-fi and tried it in FireFox. This is what it does: https://gist.github.com/gschier/65f23cfd210f5ef5d1f1acf82225f988

As for missing features...

`startedDateTime`: If I understand correctly what this is, you should be able to set it to `new Date(response.created).toISOString()`
`time`: Should be the same as `response.elapsedTime`
`timings`: We don't have this data easily accessible at the moment, but it could be added down the road

**Comment by vfaronov** [comment]
@Atvaark Thank you for your work on this. But does this feature actually work as intended? I can’t find a way in the Insomnia UI to export the *history* of requests/respones, as opposed to just the request/response currently displayed.

The use case I had in mind was: I submit a series of requests to an API — all different *HTTP requests*, but not necessarily corresponding to different *workspace entries* — and they end up in the history that is accessible from the upper right hand corner menu. It is this history, in chronological order, that I would like to export to HAR.

Am I missing something?

**Comment by vfaronov** [comment]
> What you are looking for is an HAR export of the *past responses* and not of the workspace right?

Yes. That’s why it says “history” in the issue title.

@gschier Would you like me to open a new issue?
