### ISSUE TITLE
Inso --ci argument doesn't seem to do anything

### ISSUE THREAD

**Issue by filfreire** [getinsomnia/insomnia#4218]
### Expected Behavior

I get a prompt asking for spec and environment if I run `inso run test` on an insomnia git based sync repo. 
I was expecting the `--ci` flag to pick a spec and an environment by default/omission.

### Actual Behavior

The `--ci` flag doesn't seem to do anything and I get back an error like:
```shell
[fatal] No test suites found; cannot run tests.
```

Same applies if I try to specify `--src`, `-a` and `-w` arguments, I get back an error similar to:
```shell
insomnia-sync-experiment $inso run test --ci --src . 
[warn] No git, app data store or Insomnia V4 export file found, re-run `inso` with `--verbose` to see tracing information
[fatal] No test suites found; cannot run tests.
```

See recording:
![Kapture 2021-11-16 at 16 27 49](https://user-images.githubusercontent.com/11976836/142027179-08b6cb9b-444e-491a-9190-5905581c00d0.gif)

### Reproduction Steps

1. Clone example insomnia git sync repo, `git clone https://github.com/filfreire/insomnia-sync-experiment.git`
2. `cd insomnia-sync-experiment`
3. Run `inso run test`
4. Run `inso run test --ci`

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

This behaviour seems to date back to a PR, https://github.com/Kong/insomnia/pull/2338, that was being worked on by @develohpanda.

I notice that in the gif in the mentioned PR it also seems to be the case that `--ci` flag doesn't default to a spec or environment.

I don't get any prompts if I specify the exact spec and environment,

```shell
inso run test spc_1bd218 -e env_env_6f8ab9

# works as intended
```
 but I would risk saying it defeats the implicit purpose I had in mind as a user for the `--ci` argument.

### Insomnia Version

Inso 2.4.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.0.1

### Installation method

npm i -g insomnia-inso

### Last Known Working Insomnia version

N/A

**Comment by develohpanda** [comment]
The presence of the `--ci` flag is similar to the [`--yes`](https://github.com/lerna/lerna/tree/main/commands/publish#--yes) flag with lerna and this behavior is by design.

> `--ci` flag doesn't default to a spec or environment.

That's because there's isn't a sensible default we can assume (more on this below). With lerna, the `--yes` flag will respond with "Yes" for all confirmation prompts in CI, however with `inso run test`, if enough information is not provided, and prompts are disabled with `--ci`, there's no sensible default that we can use.

Currently, design document : git repository is 1:1, and design document : unit test suite is 1:many. This means one git repository will contain one design document, but can contain multiple test suites (all children of the design document). One design document could also contain many environments.

Let's say my repository contains one design document, 3 environments, and 3 test suites. If I run as `inso run test --ci`, what would you expect to be the defaults for `identifier` and `env` in the command `inso run test <identifier> --env <env>`?

I think the answer to the above is very tricky because automatically selecting a default could result in a test suite being run against a test/prod environment, for example. This is allowed, and if a user explicitly chooses to do so, great, but if inso defaults to a prod environment that would be concerning.

With this in mind, what would the expected behavior of `--ci` be?

---

What if we were to provide a more context aware error message if a) `--ci` flag is set and b) inso has insufficient information? Instead of the common "could not find test suite", we could say "please provide a test suite/env", for example?

**Comment by filfreire** [comment]
(Ignore the above, I closed the issue by mistake)

@develohpanda I understand what you mean. Different folks could have different interpretations/expectations of what the default could be. For instance - I was expecting it to just pick the only ones available - since in my particular case I only had 1 spec and 1 environment.

As for multiple environments - picking the uppermost (or lower) spec/env/... would be tricky.

I think a more context aware message could do the trick for this issue - if we design it in a way that doesn't leave the user guessing/indirectly helps the user:
- Either by asking the user to specify a spec and and environment (and maybe also print out the possibilities for them)
- Or by suggesting folks to run a (new) command that would list all the specs/environments (e.g. `inso list` / `inso ls`) that inso could find in a given/default target src/app dir.

This last option could allow folks to (if they wanted to) "pipe" commands in some local/CI situations, e.g.

```shell
inso list specs --src .
# returns:
uts_e29d72 Example tests
uts_a23d23 Some user flow
uts_b34d34 Some other tests
# ...

inso list env --src .
# returns:
env_env_6f8ab9 Development A
env_env_2f8bb1 Development B
env_env_3f1ba1 Staging C
# ...

# do regular bash scripts, e.g. finding specific test suite:
inso run test $(inso list specs  | grep "Some user flow" | head -n 1 | awk '{print $1}')  --env env_env_6f8ab9

# run inso for multiple environments that follow a pattern
inso list env | grep "Development" | awk '{print $1}' | xargs inso run test <...>
```

**Comment by develohpanda** [comment]
Sounds good, context aware error message would be best 👍🏽 I'm hesitant to print out the possibilities as part of that context aware error message (to avoid unintentional data leakage into console logs), but I like the second suggestion directing users to an `inso list` command.

`inso list` in turn enabling workflows using pipes seems like a home run and we can re-use a lot of the existing code used by prompts, for listing. @wdawson how does this sound from product pov?

**Comment by wdawson** [comment]
Yeah, I'm all for better, context-aware errors. It's especially confusing to me when `inso run test` works but `inso run test --ci` fails with "[fatal] No test suites found; cannot run tests." ... the command without `--ci` clearly found tests. So it would make me think that `--ci` looks in a different directory than the first command, which doesn't sound like the case. Given that `--ci` is intended to run without human input (right?) I don't think we can prompt a user, but certainly showing an error for why their setup can't run in that way would be better than the current behavior.

**Comment by develohpanda** [comment]
> Given that` --ci` is intended to run without human input (right?) ) I don't think we can prompt a user

inso is interactive by default, and disabled by `--ci`. So for example, `inso run test` doesn't "work", it just becomes interactive if inso doesn't have enough information from the user, and prompts them to select a test suite. The `--ci` flag switches off the interactive behavior, instead exiting with an error if inso doesn't have enough information.

Because inso is interactive by default, but maybe a future state is non-interactive by default, and opt-in using `--interactive` or such. This is a larger change which we probably don't need to do until necessary, and the context aware error messaging would still be needed at that time.

**Comment by filfreire** [comment]
@wdawson @develohpanda closing this one, as I believe we've discussed the issue in length.

Nevertheless, I created a follow-up internal issue for us to check what we could do regarding the possible `inso list` feature - https://linear.app/insomnia/issue/INS-1282/new-inso-cli-method-list
