### ISSUE TITLE
[Bug] Following a 301, 302 or 303 do not always use GET

### ISSUE THREAD

**Issue by hadrienk** [getinsomnia/insomnia#439]
- Insomnia Version: 5.7.11.978
- Operating System: Mac OS X

## Details

If a POST or a PUT request returns 301, 302 or 303, the method used on the request made on the Location URL should be GET. It seems it currently uses the same method than the original request.

**Comment by hadrienk** [comment]
Seems insomnia is using the binding https://github.com/JCMais/node-libcurl. This can be a problem as curl does not support this. See https://github.com/curl/curl/issues/578

**Comment by gschier** [comment]
Hi @hadrienk,

This should be working with `POST` requests in Insomnia, but I can confirm that `PUT` requests do not switch to `GET`.

I just tried it with a basic `POST` redirect and it seemed to work. I tested by `POST`ing to the following URL: `http://httpbin.org/redirect-to?url=http%3A%2F%2Fexample.com%2F`

![image](https://user-images.githubusercontent.com/587576/29389682-728e06ec-82a0-11e7-8d2b-b3b8d10f2f48.png)

**Comment by gschier** [comment]
Will add some more detail since this bug was reported again. This is a behavior of `libcurl` which seems to work for `POST` but I'm not sure how (or if it's possible) to get it working for `PUT` and possibly other methods that can have bodies.

There is a currently undocumented to-do item to move redirect logic in-house, which would allow us to define this behavior ourselves, but that may not happen for a while since it's quite a bit of work for not much return. ie it's low priority.
