### ISSUE TITLE
Error cloning AWS CodeCommit Git repository: "Could not find origin/master"

### ISSUE THREAD

**Issue by akamola** [getinsomnia/insomnia#4660]
### Expected Behavior

Cloning a Git repository from AWS CodeCommit works.

### Actual Behavior

We're using a privat Git repository on AWS CodeCommit, all right's granted for the developer account to the repository. When trying to clone an existing repository, the error occurs: "Could not find origin/master" and the master branch does clearly exist in the repository.

Also, when using "main" instead of "master" as default branch name, the error occurs: "Could not find origin/main".

### Reproduction Steps

1. Create a fresh Design Document
2. Click on the button "Setup Git Sync"
3. Enter the HTTPS Git URI from AWS CodeCommit and the AWS CodeCommit credentials
4. Wait … after a few seconds the error message "Could not find origin/master" pops up

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

We tried using an existing AWS CodeCommit Git repository, which works well outside of Insomnia. We double checked the access rights of the developer account and the access to the CodeCommit Git repository but could not get it working with Insomnia.

We tried using a brand new, empty Git repository on AWS CodeCommit which worked fine first! We could commit, push and see the Insomnia data of the Design Document in the repository. When removing the Git repository and re-adding it to the Design Document the error reoccured: "Could not find origin/main". So, it seems that it only works with an empty, untouched Git repository on AWS CodeCommit.

The stack trace from the Dev Tools:

```
13:00:58.109 › [git-event] Auth Success: https://git-codecommit.**-****-*.amazonaws.com/v1/repos/****************
13:01:01.860 › [git-event] 
13:01:01.861 › [git-event] Counting objects: 0
13:01:01.862 › [git-event] Counting objects: 2
13:01:01.863 › [git-event] Counting objects: 2
13:01:01.863 › [git-event] Counting objects: 2, done.
 13:01:01.870 › [ErrorModal] NotFoundError: Could not find origin/main.
    at Function.resolve (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/isomorphic-git/index.cjs:1840:11)
    at async _checkout (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/isomorphic-git/index.cjs:5631:11)
    at async _clone (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/isomorphic-git/index.cjs:7723:5)
    at async Object.clone (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/isomorphic-git/index.cjs:7821:12)
    at async shallowClone (bundle.js:421829:3)
    at async GitRepositorySettingsModal.onSubmitEdits [as _onSubmitEdits] (bundle.js:422122:13)
```

### Insomnia Version

2022.2.1

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.3

### Installation method

Download from website

**Comment by filfreire** [comment]
Hi @akamola, thank you for reporting this!

Indeed I was also able to reproduce this, there seems to be some problem on Insomnia when cloning an AWS CodeCommit git repository that already has commits made to it.


<img width="383" alt="Screen Shot 2022-05-13 at 12 09 54" src="https://user-images.githubusercontent.com/11976836/168271850-f9709c59-6d72-476b-8e3c-9e6e249adf11.png">


Logs:
```
12:10:41.448 › [git-event] Using basic auth credentials
12:10:41.793 › [git-event] Auth Success: https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/example-insomnia
12:10:45.483 › [git-event] 
12:10:45.484 › [git-event] Counting objects: 0
212:10:45.484 › [git-event] Counting objects: 38
12:10:45.485 › [git-event] Counting objects: 38, done.

12:10:45.702 › [git-event] Using basic auth credentials
12:10:46.046 › [git-event] Auth Success: https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/example-insomnia.git
12:10:48.681 › [git-event] 
212:10:48.683 › [git-event] Counting objects: 38
12:10:48.683 › [git-event] Counting objects: 38, done.
```

This might need some more investigation, but I suspect it might be something to do how CodeCommit handles pulling remote branches and git remotes, as like you mention, when using the repository in regular ways directly with git I'm able to pull and push just fine:

```
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), 188 bytes | 188.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
To https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/example-insomnia
   b2e29c4..872738e  master -> master
```

## Update

Adding a bit more notes: When we force the `ref` to be `master` (as opposed to defaulting to `origin/master` when calling shallowClone, e.g.
```diff
diff --git a/packages/insomnia/src/sync/git/shallow-clone.ts b/packages/insomnia/src/sync/git/shallow-clone.ts
index e9a763cd7..4cb505a1a 100644
--- a/packages/insomnia/src/sync/git/shallow-clone.ts
+++ b/packages/insomnia/src/sync/git/shallow-clone.ts
@@ -23,5 +23,6 @@ export const shallowClone = async ({ fsClient, gitRepository }: Options) => {
     singleBranch: true,
     url: gitRepository.uri,
     depth: 1,
+    ref: 'master',
   });
 };
 ```
 
 I'm able to clone the repository:
<img width="409" alt="Screen Shot 2022-05-13 at 12 54 51" src="https://user-images.githubusercontent.com/11976836/168278415-1cbcf8b1-4e13-4231-9b15-74794d235ba5.png">

 
All the other commands where that we might also use of [isomorphic-git](https://github.com/isomorphic-git/isomorphic-git) start failing because I didn't force the `ref` for those:
<img width="578" alt="Screen Shot 2022-05-13 at 12 55 31" src="https://user-images.githubusercontent.com/11976836/168278399-6db8e7a1-88d6-4307-9e2d-76e0f27fc1b9.png">

So it's likely something with how we send the `ref` by default.

**Comment by akamola** [comment]
I'm sorry, but the bug seems to still exists for AWS CodeCommit:

I still can only once setup the AWS CodeComit Git repository in Insomnia and push from there. When I try to check out this repository in a different project or document (or on a different computer) I still get the error "Could not find origin/master":

![Bildschirmfoto 2022-12-08 um 11 06 27](https://user-images.githubusercontent.com/368349/206420750-63ffd3a7-1042-4c41-a682-f3e621c592cf.png)

I've checkt this with Insomina 2022.6.0 and the lastest beta Insomnia 2022.7.0-beta.6.
It—sadly—still does not work …
