### ISSUE TITLE
WebSockets Support

### ISSUE THREAD

**Issue by MushiX** [getinsomnia/insomnia#4671]
Would it be possible to add support for WebSockets to Insomnia ?
I am building an API using WebSockets and need a good working tool to test endpoints.

The postman tool unfortunately has support for websockets in beta and it is not so convenient because it does not allow you to keep configuration changes of the connection.

**Comment by filfreire** [comment]
Hi @MushiX, thank you for raising this issue!

This is indeed a feature that the community has been asking for a long time (see the discusion on https://github.com/Kong/insomnia/discussions/4477). We likely won't be able to support Websockets in Insomnia any time soon, and @wdawson can give you more context on that. We hope we will be able to add that feature at one point, but no prediction of when.

Alternatively, and in order to try and help you, something that I've been using personally is [websocat](https://github.com/vi/websocat). It works similarly to `curl` for websockets and has helped me a lot in the past.

**Comment by wdawson** [comment]
Yep, we're tracking Websockets in the discussion linked above. Please head over there to comment or upvote. It's definitely something we're seriously considering, but hoping to get a better foundation in place for our networking stack first. Will close this issue in favor of the Discussion.
