### ISSUE TITLE
[Improvement] Add the ability to choose a specific timezone

### ISSUE THREAD

**Issue by lcollet** [getinsomnia/insomnia#472]
- Insomnia Version: 5.7.14
- Operating System: Win 7

## Details

We're using Insomnia to test our REST API's.
It would be nice to get the request's datetime (displayed into the 'Timeline' tab)  at our local timezone (actually timezone is GMT).
![screenshot327](https://user-images.githubusercontent.com/6253083/30161205-e1ae4a7e-93cf-11e7-8d0a-9bbef5ddd855.jpg)

We use this tab to monitor matching between our security logs and the user's request parameters and datetime.

Thank you.

**Comment by gschier** [comment]
Hi @lcollet. Thanks for the request!

This is the output of a header generated by the server you are contacting. Since Insomnia is a tool for debugging HTTP, I would prefer to stay away from making changes that alter the actual server response. 

Perhaps this would be a good reason to allow the plugin system to modify response output? (See #423 discussion).

**Comment by gschier** [comment]
Closing this one for now as stale.
