### ISSUE TITLE
Insomnia unable to render Okta login page

### ISSUE THREAD

**Issue by felderi** [getinsomnia/insomnia#4854]
### Expected Behavior

Expected to see the Okta login page when being re-directed to Okta to logon.

### Actual Behavior

Insomnia shows a 200 but doesn't render the page.  
<img width="1049" alt="Screen Shot 2022-06-10 at 5 58 13 AM" src="https://user-images.githubusercontent.com/15874910/173069573-511a0740-5dcb-4ac7-ad98-1bb806a3421a.png">

### Reproduction Steps

Visit an URL that re-directs to Okta to logon with Insomnia. 

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.4.0-beta.0

### What operating system are you using?

macOS

### Operating System Version

12.3.1

### Installation method

insomnia.rest

**Comment by wdawson** [comment]
Looks like this is caused by javascript on the page setting cookies and failing. Allowing that causes various issues. So this is actually working as designed. Would recommend getting a session/token through your browser and then doing what you need. If you need an Okta token, you can use the Bearer auth method for the API requests.
