### ISSUE TITLE
Import from postman collection loses Authorization header

### ISSUE THREAD

**Issue by Metallizzer** [getinsomnia/insomnia#4870]
### Expected Behavior

Postman collection item has headers
```
"header": [
    {
        "key": "Content-Type",
        "value": "application\/json"
    },
    {
        "key": "Accept",
        "value": "application\/json"
    },
    {
        "key": "Authorization",
        "value": "Bearer 20867|o01FnKNCCzfX0kErvjrgKdJV41CIy0GPFVWHwBGPQWRW6hQCPDfrbh6K6XVj0SVs"
    }
],
```
After import they are expected to be in the Header section
![image](https://user-images.githubusercontent.com/691719/174014124-8891ae6c-f193-438e-80d9-c509594e97ad.png)
So it was in version 2022.3.0

### Actual Behavior

But, they are missing
![image](https://user-images.githubusercontent.com/691719/174014322-2b54a62c-7ad0-4bbf-9e44-6bba7b93ef2e.png)

### Is there an existing issue for this?

- [x] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.4.1

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04.4

### Installation method

Github Appimage release

### Last Known Working Insomnia version

2022.3.0

**Comment by filfreire** [comment]
Hi @Metallizzer, thanks for reporting this!

There have been some improvements added into `2022.4.0` that convert `Authorization` headers into the `Auth` Insomnia tab. You should be able to see the your `Bearer <token>` on the Auth tab automatically:

![Screenshot 2022-06-16 232110](https://user-images.githubusercontent.com/11976836/174187262-cb456501-35da-4d1a-82f7-9446473b3356.png)

This shouldn't affect the `Authorization` Header itself once you send the request. If you go into the Timeline, you should be able to check it was sent.

Let us know if somehow it's still not being sent in your case, because then we might have a bug somewhere.

**Comment by Metallizzer** [comment]
Thank you.

**Comment by JSonEVA** [comment]
Sorry to jump in on this but I have a similar issue. However, in my case the Authorization header is proprietary:

```
        "header": [
          {
            "key": "Authorization",
            "value": "Token abc123",
            "type": "text"
          }
        ],
```

in this case, Insomnia doesn't add it to the headers but also doesn't provide an alternative.

Sending the request doesn't provide the header.

**Insomnia Version**: 2022.6.0

**Comment by ncoutinho** [comment]
In my case the imported auth header is a proprietary  header with an environment variable from postman that gets nuked. Funny enough the postman environment variables in the request body and urls imported across just fine

`"header": [
					{
						"key": "Authorization",
						"value": "LDAP {{ldap_credentials}}"
					},
					{
						"key": "Content-Type",
						"value": "application/json"
					}
				]`
