### ISSUE TITLE
To enable git-sync, Insomnia should request access for only one repo

### ISSUE THREAD

**Issue by BahaaZidan** [getinsomnia/insomnia#4907]
### Expected Behavior

To enable git-sync, Insomnia should request access for only one repo. Anything more than that is not necessary and not safe at all.

### Actual Behavior

Insomnia is requesting access for my entire account. Including organizations I'm a member of.

![Screen Shot 2022-06-27 at 2 52 16 PM](https://user-images.githubusercontent.com/22656046/175946063-6b53717a-49fd-4144-9ace-5cbad0a801e9.png)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.4.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.4

### Installation method

download from insomnia.rest

**Comment by filfreire** [comment]
Hello @BahaaZidan thank you for reporting this issue!

The way GitHub and Gitlab integration were designed was to enable folks to sign in once on each, and then be able to reuse the same sign in information and allow the user clone any of their repositories into Insomnia.

You do make an interesting point, particularly as user we may not want to give Kong or Insomnia access to ALL of the repos, and maybe only public ones or private. So maybe we could improve this and allow folks to configure specifically how much they want to share. We will try to discuss it internally. Tagging @wdawson and @Kong/team-insomnia

**Comment by wdawson** [comment]
Thanks for reporting @BahaaZidan

Unfortunately, GitHub doesn't allow us to request access to a specific repo. They only have the `repo` and `public_repo` [scopes](https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps). We have users that want Insomnia to access to private repos so we opted for the general `repo` scope to support that use case. 

For now, we have no plans to change the scopes or provide an option for users because at the end of the day it is still up to you to decide what actions you want to take and what data to read/write. The tokens are also stored securely on your machine and are secure in transport as well. I'll close this issue.
