### ISSUE TITLE
Windows 11 titlebar theme color

### ISSUE THREAD

**Issue by baek-sang** [getinsomnia/insomnia#4965]
### Expected Behavior

Similar as vscode.

Dark titlebar color ( Insomnia dark color theme )

### Actual Behavior

Insomnia theme color and titlebar isn't matching.

### Reproduction Steps

1. Open program.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

![titlebar](https://user-images.githubusercontent.com/69100154/178828522-2cf27ade-86af-4496-bbc4-5683cd8853f1.png)

### Insomnia Version

2022.4.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2 RTM

### Installation method

insomnia.rest

**Comment by rusprice** [comment]
There is no way for Insomnia to set the colour of the native title bar. Visual Studio Code disables the native title bar for its application and uses their own title bar so they can have it match the theme color. This is not just a Windows 11 issue, and also happens on Windows 10 and possibly MacOS and Linux.

Perhaps you can turn this into a feature request and ask that they create their own title bar rather than use the native one like Visual Studio Code so they can have it match the theme color.

For now, [change your device's theme settings](https://support.microsoft.com/en-us/windows/change-colors-in-windows-d26ef4d6-819a-581c-1581-493cfcc005fe#WindowsVersion=Windows_11).

**Comment by filfreire** [comment]
@baek-sang thanks for reporting this! This is an existing discussion: https://github.com/Kong/insomnia/discussions/3641

(Also, thank you @UntrustableRus for the comment)

For anyone else bumping into this issue: please upvote https://github.com/Kong/insomnia/discussions/3641 so the team gets an idea of how many folks would like this feature implemented.
