### ISSUE TITLE
Removal of Insomnia installation deletes everything (Windows)

### ISSUE THREAD

**Issue by flower7434** [getinsomnia/insomnia#5118]
### Expected Behavior

Data stored at a safe location of a user account.

### Actual Behavior

Data stored along with installation. Gah.

### Reproduction Steps

Install Insomnia
Work with it
Reset Windows
Data loss since config is stored with the installation

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

But why...

### Insomnia Version

Any

### What operating system are you using?

Windows

### Operating System Version

11

### Installation method

By downloading Insomnia at a low moment

### Last Known Working Insomnia version

Never

**Comment by filfreire** [comment]
Hi @FredrikDahlberg, thanks for reporting this!

As of now, this behavior is by design, due to the fact that the [application data is stored](https://docs.insomnia.rest/insomnia/faq#where-does-the-application-store-data), in Windows case, on `AppData` folders, meant to be disposed of after uninstalling Insomnia.

There is an open Feature request we are tracking to allow users to setup this data folder from insomnia itself and not as a startup environment variable, you can find it here: https://github.com/Kong/insomnia/issues/1638. If this would be implemented, it would solve your problem.

As a temporary workaround solution, consider using `INSOMNIA_DATA_PATH` environment variable to specify a path where you might want to keep your Insomnia app data, away from the default `AppData` folder which would be disposed.


Feel free to report any other issues you find!
