### ISSUE TITLE
[Question] Duplicate "Bearer" String on Auth Method Chaining

### ISSUE THREAD

**Issue by slashsBin** [getinsomnia/insomnia#517]
- Insomnia Version: 5.8.4.1085
- Operating System: MacOS 10.13

## Details

When Chaining Authentication Requests and using the Bearer Auth Method, Chained Request will contain "Bearer" string twice:

Chain Example:
1. First Request: will return `Authorization` in Response Header in format "Bearer <JWT-Token>"
2. Second Request: Uses Bearer Auth Method with Value of Previous Request's Authorization Header

The Second Request will have Bearer string twice since One will be added by Auth Method and the second one already exists in Authorization Response header.

I've tried setting Second Request's to `{% filter replace("Bearer ", "") %}{% response 'header', 'req_81f8f8cb2aa147ef96ff3f88c593b322', 'Authorization' %}{% endfilter %}` with no luck.

The only workaround I've found is that do not use built-in Auth Method(Set to No Authentication) and try setting the Header in Header Panel Manually.

**Comment by gschier** [comment]
Hmm, I tried that as well and it didn't work. However it did work with `{% filter replace('Bearer ', '') %}Bearer 12345{% endfilter %} so I'm not sure what the problem is (I'll look into it).

I'm not sure if this will work for you, but a common way to do this sort of thing is to nest environment variables. If you set an environment variable to `"variable": "{% response 'header', 'req_81f8f8cb2aa147ef96ff3f88c593b322', 'Authorization' %}"` you can use it with regular variable syntax like `{{ my_variable | replace('Bearer ', '') }}`

**Comment by slashsBin** [comment]
Tnx for the quick & helpful response, I'll try using env variables, tnx.

**Comment by moitran** [comment]
@gschier 

It works well, Thank you very much

**Comment by gschier** [comment]
You're welcome 😄
