### ISSUE TITLE
insominia connetion is failing out

### ISSUE THREAD

**Issue by prakash5751** [getinsomnia/insomnia#5196]
### Expected Behavior

Trying to post query on hapi server but connection is taking too long to respond.

### Actual Behavior

[Doc1.docx](https://github.com/Kong/insomnia/files/9599759/Doc1.docx)
Insomnia is crashing

### Reproduction Steps

 connection is taking too long

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.5.1

### What operating system are you using?

Windows

### Operating System Version

windows 11 home

### Installation method

From Insominia Website

### Last Known Working Insomnia version

2022.5.1

**Comment by filfreire** [comment]
Hi @prakash5751, thanks for reporting this. We would need a bit more information before being able to do something with this issue.

I'm able to get a response from the server you show in your screenshot:
![image](https://user-images.githubusercontent.com/11976836/191460767-c5827698-3091-4fdd-89fa-962ff8434c90.png)


I would recommend the following, in order to check if there's some issue with Insomnia itself, or a network issue/problem with the server you are trying to connect with.

- Try to issue a [curl request](https://curl.se/) of the same request. You can use Insomnia to get a curl request with the `Copy as Curl` option:

![image](https://user-images.githubusercontent.com/11976836/191459509-1b921a56-fa54-4e67-8a3f-8eab5d3611a8.png)

If you don't use curl, you could try the `Generate Code` and pick an option that is familiar to you.
