### ISSUE TITLE
cursor loses its focus in the Manage Environments window

### ISSUE THREAD

**Issue by manbeing** [getinsomnia/insomnia#5234]
### Expected Behavior

We can add/edit environment variables without interruption. 

### Actual Behavior

OS: Ubuntu 20.4.
Insomnia version:  2022.6.0
Build date: 9/26/2022

In the Manage Environments window, when typing the variable name or variable value, the cursor loses focus after typing 1-2 character. 
If you continue typing (without cursor focus), I find the characters you type will be input into the URL address box on anther window

Please fix this issue as it has prevented from invoking the functional variable value feature, eg, Response =>xxx

### Reproduction Steps

1. Click the Environment Tab (left top)
2. Click Manage Environments
3. Manage Environment window launched
4. Type a variable name (in the double quotes) or type a variable value (in the double quotes). You will find cursor loses its focus after you typing 1-2 character. (I found it is very easy to reproduce the issue when typing a variable value)
5. If you continue typing (without cursor focus), I find the characters you type will be input into the URL address box on anther window (cursor focus jumps to URL endpoint box on the parent window)

Please fix this issue as it has prevented from invoking the functional variable value feature, eg, Response =>xxx

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Issue doesn't occur if I revert the version to 2022.5.1

### Insomnia Version

2022.06.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04

### Installation method

Snap store

### Last Known Working Insomnia version

2022.5.1

**Comment by filfreire** [comment]
Hi @manbeing, thanks for reporting this!

We had found a similar bug while preparing [release 2022.6.0](https://github.com/Kong/insomnia/releases/tag/core%402022.6.0) that we fixed in [this PR](https://github.com/Kong/insomnia/pull/5184).

We've tried reproducing earlier and couldn't so far.

Are you still able to reproduce this if you do a clean install of Insomnia, or for example if you use a different installation source than snap, like the AppImage?

**Comment by manbeing** [comment]
Hi @filfreire   I was able to reproduce it with a fresh install. I currently rolled back the version to 2022.5 in order to edit the environment variables.

**Comment by driden** [comment]
Hello, I'm also experiencing the exact same behaviour on `macOS 12.6 (21G115)`.
I've reinstalled using homebrew to the following version
```
Version: Insomnia 2022.6.0
Build date: 9/26/2022
```

I'm using this for work so I can't really clean all my files, but let me know if there's something I can try out for you.

**Comment by vaidd4** [comment]
Same behaviour on Fedora 36:
```
Version: Insomnia 2022.6.0
Build date: 26/09/2022
OS: Linux x64 5.19.11-200.fc36.x86_64
Electron: 19.0.3
Node: 16.14.2
V8: 10.2.154.4-electron.0
Architecture: x64
```

Notes (while looking at DevTools): 
- The `div.CodeMirror` loses focus (and loses the class `.CodeMirror-focused`) one second after anything is written.
- If you continously write it doesn't lose focus.
- If the JSON is not valid it doesn't lose focus.
- If you only move around (with arrow keys for exemple) you don't lose focus
- **Edit**: It only happens in the main **Manage Environments** modal. Not in the **Environment Overrides** modal.
- **Edit**: If you don't have a request selected/shown in the middle (first time opening a new collection or after deleting a request) you don't lose focus. (does focus priority exist?)
- **Edit**: It only happens when you are editing the currently active sub environment.

I think there is a "debounce" function that triggers after an "input" or "change" event and wrongly makes the "code mirror" block lose its focus. (I didn't look into the source code yet)

**Comment by filfreire** [comment]
Are you folks by any chance still able to reproduce this in our [latest beta version](https://github.com/Kong/insomnia/releases/tag/core%402022.7.0-beta.1)?

**Comment by vaidd4** [comment]
@filfreire I installed the rpm version for the beta1 and got the same issue :
```
Version: Insomnia 2022.7.0-beta.1
Build date: 06/10/2022
OS: Linux x64 5.19.11-200.fc36.x86_64
Electron: 19.0.3
Node: 16.14.2
V8: 10.2.154.4-electron.0
Architecture: x64
```

**Comment by filfreire** [comment]
Hi folks, we managed to reproduce this internally as well, we'll update you here when there's a fix, hopefully we might be able to include it in one of our weekly beta releases 👍

**Comment by manbeing** [comment]
@filfreire  How can I use snap to install your weekly beta release?
Only 2022.6 major release available to me on snap.
Thanks.

**Comment by filfreire** [comment]
@manbeing unfortunately we don't publish beta releases on snapcraft, only on [github releases](https://github.com/Kong/insomnia/releases/)

However, you might be able to install latest one by enabling the Beta channel within Insomnia preferences:

![beta](https://user-images.githubusercontent.com/11976836/195577926-47d8f9ea-5be5-45d1-9a36-81fe14f3edcf.png)

**Comment by manbeing** [comment]
@filfreire 

I went to Preference window, but didn't find the section for 'Software Updates'. Is this new for 2022.06 release?
I am currently using 2022.05 release due to this losing cursor issue.

![image](https://user-images.githubusercontent.com/39745132/195610881-b458fcd9-8677-4ffa-8d13-712d5a06bb71.png)

**Comment by solita-esatikka** [comment]
I had this issue with 2022.6.0, switched to early access channel, got an update, and can no longer trigger the issue. Nice! 👍 
```
Version: Insomnia 2022.7.0-beta.4
Build date: 02/11/2022
OS: Windows_NT x64 10.0.19044
Electron: 21.2.0
Node: 16.16.0
V8: 10.6.194.18-electron.0
Architecture: x64
```

**Comment by filfreire** [comment]
Hi folks, this should be fixed in our latest beta.5 release:  https://github.com/Kong/insomnia/releases/tag/core%402022.7.0-beta.5

> For Fedora users affected by https://github.com/Kong/insomnia/issues/5088, you can use this experimental build which includes all changes included in beta.5:  https://github.com/filfreire/insomnia/releases

**Comment by josueal1** [comment]
I've been experiencing this issue so I might revert to 2022.2.1

```Version: Insomnia 2022.6.0
Build date: 09/26/2022
OS: Darwin x64 22.3.0
Electron: 19.0.3
Node: 16.14.2
V8: 10.2.154.4-electron.0
Architecture: x64```

**Comment by josueal1** [comment]
I've also been experiencing this issue with `2022.6.0` so I might revert to `2022.2.1`

```
Version: Insomnia 2022.6.0
Build date: 09/26/2022
OS: Darwin x64 22.3.0
Electron: 19.0.3
Node: 16.14.2
V8: 10.2.154.4-electron.0
Architecture: x64
```
