### ISSUE TITLE
[Feature Request] Read/Write directly to local file, instead of Import/Export

### ISSUE THREAD

**Issue by Sirikon** [getinsomnia/insomnia#530]
Insomnia is a really powerful tool for REST API testing, and the Import/Export functionality is useful when working with your own API, because you can export your environment and include it in version control. So you could make version tracking over your API *and* the Insomnia configuration for it.

The thing is: For the user, the Import/Export workflow is a bit tedious, because there are too many interactions to get the Insomnia environment config exported into your repository.

I think that a feature like being able to directly read/write an environment from/to a local file would ease a lot this process, and create a more satisfactory experience (and a more productive workflow).

Workflow example:

- Open Insomnia
- File > Open > Your file in your repo (Or drag it to Insomnia window)
- Make some edits and save automatically all the time
- Just commit your changes, the Insomnia environment file will be already updated.
- Pull new changes, Insomnia realizes that the already open environment file has changed, so it loads the new version and Insomnia is ready to go with the new version of the environment file.

**Comment by gschier** [comment]
This sounds like a neat idea, but it would require a massive change to the way Insomnia is architected. I'm not sure the amount of work required would be justified.

That said, it might help to have a command-line interface for importing/exporting. This is being discussed over here #479

**Comment by nathanchapman** [comment]
@gschier Any chance we can revive this?
Having version controlled, human-readable requests and workspaces would be incredible.
This would reduce conflicts as well as allow people to reuse files (like `.graphql` and `.json` files) between Insomnia and their integration tests

**Comment by dobrynin** [comment]
+1 to those wanting to be able to upload `.graphql` files :)

**Comment by christiannaths** [comment]
I'd _love_ to see this, IMO it would be a killer feature over every other offering out there. I want to get my whole team using Insomnia because it's so great, but syncing is still a pain. Storing Insomnia requests and config in code would be perfect:

Think of this scenario: I want to build something new using a new feature that a teammate on the backend team rolled out in the API.

- Teammate pushes her changes, including the Insomnia requests/config she used to test when building
- I pull down latest as usual, make my feature branch, etc
- I open insomnia and see the additions that my teammate made, I execute requests and see the output
- I build away, happy with the current state of the world
