### ISSUE TITLE
[Question] Plugin capabilities

### ISSUE THREAD

**Issue by krainboltgreene** [getinsomnia/insomnia#531]
My current work has me performance testing HTTP-based APIs. There are a lot of tools for this but like a lot of "REST clients" they're pretty much stuck in the dark ages. I would love to use insomnia for this, but I also understand that load testing/schema testing may not be part of Insomnia's goals. I noticed that a recent set of releases contained improvements to the plugin system, so here's what I'd love to know:

  1. Can plugins add shortcuts?
  2. Can plugins add new panes *or* replace current panes?
  3. Can plugins get access to the details shown by the "Timeline" tab?
  4. Is their API access to the "make a request" functionality?
  5. Can API's access the tree of requests pane's data? (context: iterating over the tree of requests)
  6. Can plugins create custom window(s)?
  7. Any UI generated by plugins, will they have access to the same UI components as the rest of the application? (AKA: Can I make my plugin UI look like the app UI?)

**Comment by gschier** [comment]
Sorry for the delayed response here @krainboltgreene.

You are correct that testing is not part of Insomnia's goals. It focuses on simply being the best HTTP client, which is why it's so usable.

Currently, the plugin system's ability to show UI is limited to Template Tags. More information on plugins can be found here: https://insomnia.rest/documentation/plugins/

Eventually, I would like the plugin system to be able to support all the things you mentioned but, at the moment, none of them are currently possible.

**Comment by krainboltgreene** [comment]
Awesome, thanks so much for the reply @gschier.

What can I do to help with making this possible?

**Comment by gschier** [comment]
The easiest first step is probably to help build out the plugin APIs so that there are methods for things like sending requests and listing the request tree.

Maybe have a quick look at the plugin folder in the codebase to get familiar with it?

Let me know what you think of that.

**Comment by gschier** [comment]
Closing this issue for now, as the initial question was answered.
