### ISSUE TITLE
[Question] Do you have plans to add assertions?

### ISSUE THREAD

**Issue by afalck** [getinsomnia/insomnia#539]
I just started a project that involves collaboration between two teams through a REST API.  I love your tool for manually checking the results of the REST API.

I now would like to turn my insomnia queries into functional tests by adding assertions to the JASON responses.  Things as simple as: "assert that $.managers has 42 elements"  or "assert that $.managers[0]..account_id=76299"

Do you have any plans for this?  and if so... when?

thank you,

Arturo.

PS: there are some tools that do this stuff (I've been evaluating ReadyAPI) but your tool is cleaner and easier to use... I'd love to be able to give it to my team.  

PPS: your tool is reminiscent of Paw for the mac... what's the relation?

**Comment by gschier** [comment]
Hi @afalck,

I'm glad you're enjoying the app! The goal of Insomnia is to be an HTTP client first. Integration testing is not closely-related enough for me to justify working on it where there is still so much more to do to. However, it may be possible in the future to build a testing framework using the plugin system, but it's not quite robust enough to do that yet.

There are other tools that do what you want, including [Postman](https://www.getpostman.com/). 

No relation to Paw other than I've used it before. Same as Postman. We're just multiple tools trying to solve similar problems 😄 

Going to close this issue, but feel free to leave any further comments you may have.

**Comment by divStar** [comment]
I know it has been a while since the last post and now there are plugins in Insomnia, too. I love the design and honestly I prefer this tool over e.g. SoapUI, because it is so clean.

However: I am missing assertion very much and thus - if not already present - I'd love to see if it's possible to develop a plugin, which would at least assert the response body and header (String-asserts). Are there ways to assert a response or is there a way to help with getting this feature up and running?
