### ISSUE TITLE
Function requests intermittently get lost

### ISSUE THREAD

**Issue by rippo** [getinsomnia/insomnia#5471]
### Expected Behavior

Every now and again all my functions for requests seem to get forgotten.

 I then have to manually choose the right request and reselect on the drop down.

![2022-11-29_16-33-20](https://user-images.githubusercontent.com/772549/204743636-c61b1cba-0c78-41fd-aeb1-fb6b09d2f71d.png)

### Actual Behavior

This seems to be random behaviour. That is it is across 1 or 2 collections and only happens a couple time a month. At first I thought it was because I went from a free version to a paid version and started to push my collections to GitHub.

Has anyone else seen this behaviour? How to I diagnose what might be casuing the issue

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Version: Insomnia 2022.6.0
Build date: 26/09/2022
OS: Windows_NT x64 10.0.19044
Electron: 19.0.3
Node: 16.14.2
V8: 10.2.154.4-electron.0
Architecture: x64

### Insomnia Version

2022.6.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

Download

### Last Known Working Insomnia version

Not sure = but thought it was because I went from free to paid subscription

**Comment by filfreire** [comment]
Hi @rippo thanks for reporting this issue!

- I suspect the cause of the issue is [another bug](https://github.com/Kong/insomnia/issues/4985) we have - where the moment you transfer a collection to another project (e.g. like porting over from local project to a paid subscription) the request ids change, so any references you had inside a given request to another, e.g. using request chaining, might break.

You mention this happens every once in a while. I think you should be able to fix it permanently by fixing the requests where you refer to other requests one time, and then create and push a snapshot to your personal project.


![Pasted_Image_30_11_2022__09_27](https://user-images.githubusercontent.com/11976836/204758466-eb8e1c83-4ba6-4ea0-8252-82912c78a432.png)


Let us know if this helps for now.

**Comment by rippo** [comment]
Thanks I thought I had already done this on this collection and the problem had resurfaced.
I will fix all my collections and push the snapshots.
Then will wait and see if it happens again. Thanks for response
