### ISSUE TITLE
insomnia-plugin-default-headers is deprecated on NPM

### ISSUE THREAD

**Issue by NickHackman** [getinsomnia/insomnia#5475]
### Expected Behavior

I should be able to install `insomnia-plugin-default-headers` without issue

### Actual Behavior

Since the plugin is deprecated in NPM see https://www.npmjs.com/package/insomnia-plugin-default-headers

![Screen Shot 2022-11-30 at 1 54 15 PM](https://user-images.githubusercontent.com/31719071/204895396-8c04e8b2-7790-4859-a381-0cf23737f136.png)

Yarn prevents me from installing it.

### Reproduction Steps

1. Open plugins tab in preferences
2. Install `insomnia-plugin-default-headers`
3. Failed to install

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.7.0 and 2022.6.0

### What operating system are you using?

macOS

### Operating System Version

Monterey 12.6

### Installation method

homebrew

**Comment by filfreire** [comment]
@NickHackman you should be able to use default headers without installing them explicitly.

Just setting up `DEFAULT_HEADERS` object in any environment you want should do the trick, same as before.

Try with the latest 2022.7.0 beta builds  (e.g. beta.5 or beta.6).

**Comment by NickHackman** [comment]
@filfreire Oh, that's with the latest beta build? My colleague is on stable 2022.6 and the default headers weren't applying without installation.

So the default headers plugin was deprecated since it was moved into Insomnia itself, but only on the current beta branch of Insomnia and not stable?

**Comment by NickHackman** [comment]
@filfreire Upgraded from `beta.4` to `beta.6` and disabled the plugin

![Screen Shot 2022-12-01 at 9 35 00 AM](https://user-images.githubusercontent.com/31719071/205094232-ff58f11f-6206-4623-bbeb-b0648b040ded.png)

With it disabled on `beta.6` I'm unable to use the functionality it would normally provide by installing with the NPM package.

Cloned locally to test and further inspected, not sure why this is the case, but it works when I checkout the tag associated with the `v2022.7.0-beta.6` release (`95f4147df150ab8b9c198cfd4efc4f55b080075b`). Very bewildering, wouldn't expect them to behave differently 😕 

### My Local Install

Setup for `DEFAULT_HEADERS`:

![Screen Shot 2022-12-01 at 11 03 52 AM](https://user-images.githubusercontent.com/31719071/205114813-b5c51854-2484-46bb-b53f-e222673124a5.png)

cURL request:

```shell
curl --request GET \
  --url https://www.google.com/
```

### Cloned

It has the same setup

cURL request:

```shell
curl --request GET \
  --url https://www.google.com/ \
  --header 'Authorization: Bearer <token>' \
```

They both pull from the same GitHub repository so everything is identical.

**Comment by filfreire** [comment]
@NickHackman, first, answering your [questions here](https://github.com/Kong/insomnia/issues/5475#issuecomment-1333046063):

- These plugins and [other base Insomnia plugins](https://github.com/Kong/insomnia/tree/develop/plugins) are only included on latest beta versions of 2022.7.0, which will go into final release before the year ends
- For 2022.6.0 and older versions will still need to install the deprecated versions of some of these through npmjs. We recently made them private (non published to npm) and all bundled with Insomnia.

@NickHackman when doing a clean install of `beta.6` try to remove the old `insomnia-plugin-default-headers` folder from your plugins folder. You should be able use `DEFAULT_HEADERS` after that. I suspect keeping the disabled plugin in there might be causing another side-effect.

Example with clean install:
![Screenshot 2022-12-07 at 14 22 39](https://user-images.githubusercontent.com/11976836/206204567-8010f17a-546b-4f5b-b385-a8fbebf8912a.jpg)
![Screenshot 2022-12-07 at 14 22 34](https://user-images.githubusercontent.com/11976836/206204576-cbfd4496-bcc4-4fdb-a48a-c48844c025a9.jpg)

As for the differences you noticed when cloning - I suspect it might be because of the insomnia app data folder being different for when running from development. But I'm not yet sure on this. My first suspicion is the "existing" older plugin being already installed and marked as deactivated.

**Comment by NickHackman** [comment]
@filfreire Started digging a bit more in `stable` and trying to understand why it won't let me install the `insomnia-plugin-default-headers` plugin.

This is due to an issue in parsing the output of Yarn


Output from Yarn:

![Screen Shot 2022-12-07 at 10 32 59 AM](https://user-images.githubusercontent.com/31719071/206236333-9fccaeac-a42e-4bb1-87b7-798618d0d0ad.png)

Error thrown in Insomnia

> Error: Error invoking remote method 'installPlugin': Error: Yarn error warning insomnia-plugin-default-headers@3.6.0: Package no longer supported. Use at your own risk.

Bug stems from 

https://github.com/Kong/insomnia/blob/792bf7034d03748424fed9425cc9097d9bfdd636/packages/insomnia/src/main/install-plugin.ts#L231-L249

where it only checks if a dependency is deprecated by checking normal verbiage that assumes there is a newer version of a package and maybe older verbiage on unsupported packages.

This results in the "Package no longer supported. Use at your own risk" being treated as a hard error, this breaks the stable release of Insomnia preventing installation of the `insomnia-plugin-default-headers` plugin. Resulting in this error on the UI

![Screen Shot 2022-11-30 at 1 54 15 PM](https://user-images.githubusercontent.com/31719071/204895396-8c04e8b2-7790-4859-a381-0cf23737f136.png)

Can these packages be un-deprecated until the new beta release becomes stable? To prevent breaking the installation process for those on stable?

If a solution for this is worthwhile in the future I can open a PR to fix this, but code change won't fix the issue in stable without a hotfix 😄

**Comment by filfreire** [comment]
Hi @NickHackman [release 2022.7.0](https://github.com/Kong/insomnia/releases/tag/core%402022.7.0) is out 👍
