### ISSUE TITLE
[Feature Request] Make sharing client certs optional

### ISSUE THREAD

**Issue by robzienert** [getinsomnia/insomnia#552]
- Insomnia Verison: 5.9.6
- OS: Mac

Related to the Team edition.

Our team has largely standardized developer machine setup, but keys may be different developer-to-developer. We'd still like to share some certs, but not others. It would be nice to have the option to deselect a certificate as shared so that the next time we sync, our certificates are not clobbered.

**Comment by robzienert** [comment]
FWIW, this is a major blocking issue towards us actually moving forward after the 14-day trial.

**Comment by gschier** [comment]
Hey @robzienert,

I've actually been looking for ways to improve the team functionality recently, so this is good feedback. This is also a fairly easy thing to implement so I'll see if I can squeeze it into this week's release.

Also, since this is a blocker for you, I've extended your trial by 7 days.

**Comment by gschier** [comment]
@robzienert v5.10.1 just shipped with this ability included in it!

Note, there was a data migration involved which is not compatible with the previous version. Client certificates synced from the new version will not be visible to team members who still have the old version until they update.
