### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by JoaoPedroCJ** [getinsomnia/insomnia#5601]
### Expected Behavior

run multiple instances of insomnia

### Actual Behavior

only one instance of insomnia is opened

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

before the last update I managed to keep several instances of insomia open for queries, but since the last update (where there was a major UI update), I can no longer open another instance

### Insomnia Version

2022.7.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

chocolatey package

**Comment by jackkav** [comment]
Thanks for the report @JoaoPedroCJ in the process of fixing deep linking from the browser to insomnia in windows and linux, and in order to keep things simpler for us to maintain we restricted the number of open instances to one. I'm curious what specific UX having a second open instance provided for you, perhaps there is another way we can accomodate.

**Comment by JoaoPedroCJ** [comment]
I usually use multiple instances to help integrate with different APIs, I usually download the json to the workspace, having to go back and forth between each one to see the results is quite annoying

**Comment by jackkav** [comment]
I see so you need to compare json in request body or responses. I have a couple ideas in order of difficulty,
- use a hotkey to toggle between the two requests you want to compare
- add multiple instances for all platforms with an argument like "-n"
- add split screen support within insomnia
- add a diff mechanism

I'll make a ticket (INS-2235) for the second "-n" approach since I think it sounds reasonable.
Thanks again for the thoughtful feedback @JoaoPedroCJ

**Comment by tlund101** [comment]
Thanks for making that ticket, @jackkav Do you have a timeline on when it will be worked on?  The `-n` approach works best for my usecase also, which is opening multiple collections at a time (e.g. send a POST request to one API, then sending a GET request to the downstream API to verify data was processed on the backend correctly)
