### ISSUE TITLE
[Bug] A libcurl function was given a bad argument (68 MAXREDIRS)

### ISSUE THREAD

**Issue by MartijnDevNull** [getinsomnia/insomnia#561]
- Insomnia Version: v5.9.6
- Operating System: Arch Linux (libcurl-compat 7.56.1-1)

## Details
After updating libcurl I can no longer make request without receiving this message. 

#558 might be relevant

**Comment by gschier** [comment]
This was reported by another user via email, is already fixed, and will be deployed this week.

As a temporary workaround, you can set max redirects to 0 (instead of -1) in the Insomnia preferences.

<img width="763" alt="image" src="https://user-images.githubusercontent.com/587576/32275444-87f2e5be-bf0b-11e7-9d0b-424d719dba6b.png">

**Comment by gschier** [comment]
This is fixed now in v5.10.1
