### ISSUE TITLE
gRPC request body placeholder

### ISSUE THREAD

**Issue by vispariana** [getinsomnia/insomnia#5623]
### Discussed in https://github.com/Kong/insomnia/discussions/3475

<div type='discussions-op-text'>

<sup>Originally posted by **gAmUssA** June 15, 2021</sup>
Hi team,

I would love if Insomnia created request body placeholder when testing gRPC service instead of having empty request. 
This information is available in proto file.

Thanks! </div>

Hi,
Any thoughts about this feature? it's really useful and all major competitors have already implemented this. I'd be happy to implement it, and I like to know if there are any points or blockers by the dev team. The implementation itself seems straightforward.

**Comment by jackkav** [comment]
The original discussion has 10 upvotes which we use to weight the usefulness of the work, cool if we move the discussion back there? I have no knowledge of any blockers, but you will encounter codemirror which can be interacted with the props defaultValue and ref, see environment-editor.tsx for an example of how the content can be transformed. Since we have made changes to this feature recently I'd be happy to share my thoughts and assistance if you have any more specific questions should you choose to take a look at implementation.
