### ISSUE TITLE
Performance issues on big collections

### ISSUE THREAD

**Issue by LunaticoCR** [getinsomnia/insomnia#5842]
### Expected Behavior

I would expect the performance of the app to remain acceptable even if my collection keeps growing in size, both in the number of requests as well as variables.

### Actual Behavior

As my collection grows the app gets slower and slower to a point where it has become disruptive to my work flow.

### Reproduction Steps

It's hard to give a step by step description, because my collection has grown naturally over time.

1. Install insomnia
2. Start creating requests that are organised in folders that are 2 or 3 levels deep (I currently have 842 requests)
3. Have around 60 variables in the base environment, some variables have their values defined there in the json and some others take their values from responses from other requests
4. Create around 20 sub-environments with 5 to 8 variables each
5. Most requests are interconnected, they use variables or values extracted from the responses of other requests
6. Switch from one request to another and notice how it takes a few seconds to load the variables in the request body or headers
7. Run a request and notice how the time counter in the middle of the response body takes many seconds, however when the request is complete the actual request time recorder at the top next to the https status code is in the order of milliseconds
8. Create a request with a json body that is around 200 lines long and all along the body it uses around 25 variables to populate different fields in the json, when you go into this request it takes 10-15 seconds to load all the variables, and some times the whole window goes blank and the only way to get it back it to restart the app

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

This is not a new problem introduced on a new build, it has been there for a very long time, but it has been slowly getting worse as my collection grows. I would like to understand what elements are causing the issue to see if I can do some tidying up or rearranging of things as a workaround.
I am happy to help with logs or debugging, but I can not share my collection as it has some sensitive data.

### Insomnia Version

2023.1.0

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.2.1

### Installation method

Download from insomnia/rest

### Last Known Working Insomnia version

NA

**Comment by jackkav** [comment]
Thanks for the high quality issue report this will be very helpful in coming up with a reproduction.

**Comment by dom-bjss** [comment]
I'm not overly familiar with the insomnia codebase, but I spent some time comparing core@2023.1.0-beta.5
with core@2022.6.0 (seems to be the last stable version), I have observed the following.
May or may not be useful if there's a contributor who wants to pick it up properly ;) 

- models/setting.ts ->  getOrCreate() - in the older version on my system this takes 1 or 2 millis. In the new version it takes 10x as long (20 ms). 
- this gets invoked for every variable in my base-environment. It's looking for a value in a Response, but for responses that don't exist. I'm in a local dev environment, and these are not realistically going to be populated very often. They are defined with a triggerBehaviour of 'Never' - but still it does an awful lot of work to find out that there's still no value for the variable.  In the previous version the general behaviour was the same, and the slow-down seems to be specifically in models.settings.ts. 
The insomnia-plugin-response seems to be driving this.  My guess (unsubstantiated) is that the 'Settings' code is doing stuff repeatedly that could be cached or done once. And with the whole response.getLatestForRequestId() chain, maybe it could be done once per pass of the environment rather than for every variable: the behaviour is also currently driven per environment variable, so when there are multiple variables from the same call/response it will repeat the work to find that response, I think.  
I was wondering if in the case of the 'never' triggerBehaviour whether the time consuming stuff could be bypassed or short-circuited somehow, possibly with an enhancement in functionality (like being able to provide default values in the environment and only updating them by manually triggering the specific requests, instead of the more expensive and eager dependencies style approach currently).
My environment is fairly small - about 25 variables across 2 or 3 requests, but the impact is that every request takes a minimum of 5 seconds just spinning on all this stuff, even if the request I'm doing has no need of the variables that are trying to be initialized in the environment...

**Comment by sparky-d** [comment]
I'm not overly familiar with the insomnia codebase, but I spent some time comparing core@2023.1.0-beta.5
with core@2022.6.0 (seems to be the last stable version), I have observed the following.
May or may not be useful if there's a contributor who wants to pick it up properly ;)

models/setting.ts -> getOrCreate() - in the older version on my system this takes 1 or 2 millis. In the new version it takes 10x as long (i.e. about 20 ms).  This gets invoked for every variable in my base-environment.

The insomnia-plugin-response seems to be driving this. Insomnia is looking for a value to extract from a Response, but for responses that don't exist. I'm in a local dev environment, and these are not realistically going to be populated very often. They are defined with a triggerBehaviour of 'Never' - but still it does an awful lot of work to find out that there's still no value for the variable. In the previous version the general behaviour was the same, and the slow-down seems to be specifically when models.settings.ts getOrCreate() is called.

My guess (unsubstantiated) is that the 'Settings' code is doing stuff repeatedly that could be cached or done once. And with the whole response.getLatestForRequestId() chain, maybe it could be done once per pass of the environment rather than for every variable: the behaviour is also currently driven per environment variable, so when there are multiple variables from the same call/response it will repeat the work to find that response, I think. I wondered if the use of the db code for this might be unneccessary to repeatedly call at this point too: Admittedly I don't know fully how this works, but maybe these could be stored in memory, and the db stuff only used on startup... Seem's it not much more than a map from the request-id -> response, and my case ('never' trigger) response is always empty/undefined unless I go somewhere else and actually fire the specific request in question...
So basically, I was wondering if in the case of the 'never' triggerBehaviour whether the time consuming stuff could be bypassed or short-circuited somehow. Or perhaps possibly with an enhancement in functionality (like being able to provide default values in the environment and only updating them by manually triggering the specific requests, instead of the more expensive and eager dependencies style approach currently).

My environment is fairly small - about 25 variables across 2 or 3 requests, but the impact is that every request takes a minimum of 5 seconds just spinning on all this stuff, even if the request I'm doing has no need of the variables that are trying to be initialised in the environment... It's a known thing on our project team that you can't use the latest insomnia versions - we recommend people on my team install 2022.6.0 as that is the last known version that works okay - AFAIK anyway :) 
Also worth noting, if you do decide to install an older version of Insomnia, you will probably want to disable automatic updates in the Insomnia preferences, otherwise you'll be back on latest version before long, and maybe without realising it)

**Comment by LunaticoCR** [comment]
Thank you so much for that information @sparky-d !!! I've installed 2022.6.0 and the performance improvement is massive!
Here's a direct link for whoever is interested in downloading it: https://github.com/Kong/insomnia/releases/tag/core@2022.6.0

There's a particularly big request I have that consumes lots of variables and with this version it loads it in about a second. On the latest version (and beta as well) it was taking several seconds, like 10 seconds and some times it would break the UI as the main window would just go blank and I would have to restart. Anyway, I'll be sticking to this version for new, unless the insomnia team want me to test something.

**Comment by tsptylertech** [comment]
I have more than one collection with more than 1000 requests in them and in 2023.5.2, the performance is so slow loading the collection that I can get a cup of coffee and come back, and it still chugging along trying to load it...
Once it's loaded once after Insomnia starts up, it takes about 30-40 secs to load the collections that are large...

**Comment by hoch4** [comment]
My team struggles with the same problem. The newest versions of Insomnia are not usable. It takes a few seconds for a folder to open when you click on it.

I rolled back to an old version (e.g. 2022.6). It works without usability problems.

**Comment by LunaticoCR** [comment]
Sadly, that's true @hoch4 , anything past 2022.6.0 is not usable for serious power users.
@jackkav do you know has there been any progress on this?

**Comment by jackkav** [comment]
We have begun to include collections with 1000 requests in our automated tests and are working on performance improvements. 2023.5.8 should be significantly improved, there will be more to come.

**Comment by LunaticoCR** [comment]
I just updated to version v8.3.0 and the performance issues seem to have been fixed! This is great news! Also, the app is looking soooo much better now, I like it!
My collection has grown even bigger than what it was when I first reported this, so this is very promising. I guess time will tell, I'll keep using this new version and I'll report back if I have any performance issues.
Thank you guys!
