### ISSUE TITLE
Not getting support reply via email or chat. 

### ISSUE THREAD

**Issue by edtbl76** [getinsomnia/insomnia#5933]
### Expected Behavior

Send email to support and get response within 48 hours. 
Send chat requests and get responses within a few hours. 

### Actual Behavior

No reply of any kind over 3 weeks. 

### Reproduction Steps

1. go to docs.insomnia.rest. 
2. Click help. 
3. pop up mentions "Email - no time to wait around? We usually respond within a few hours"
4. Sent message. 
5. 3 weeks go by and I still patiently wait, but decide to reach out via every other channel I can think of. 

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

not relevant

### What operating system are you using?

macOS

### Operating System Version

OS X (Specific version not relevant to my issue) 

### Installation method

insomnia.rest

### Last Known Working Insomnia version

not relevant

**Comment by filfreire** [comment]
Hi @edtbl76 sorry for your experience.

- If you need help regarding something general, or found a bug or an improvement, please report those here.

- If you have a paid Individual/Team/Enterprise subscription and require specific support, reach out to Kong's support for the time being, through https://support.konghq.com/support/s/

We've endured some unfortunate team changes in early February and are since suffering from lack of bandwidth for tackling general community issues through previous support email and chat. Your best chance for those kinds of issues is through GH issues for now. Sorry again for the problems this may have caused you!

**Comment by edtbl76** [comment]
Ok. This is helpful. I'm trying to register an account (Insomnia), however when I try to do so, the page errors out suggesting the email list already registered. I don't remember registering it, and none of the passwords I use get me through. 

How do I proceed in registering?

**Comment by filfreire** [comment]
@edtbl76 it might be an old account that is blocking you. In that case recovery is tricky due to how encryption of user data is implemented.

I would recommend for now trying so register with something a `+1` at the end of your emails' username like `<username>+1@<youremail>.com`.

We are working on a complete revamping of the accounts website for the past few months so that folks can more easily recover their accounts, or even login using Social Login (e.g. Gmail and Github) - so when that new website launches you'll be able to recover your regular account and move things over to that one.

**Comment by edtbl76** [comment]
I don't need to recover it. I just need you to delete it. 

The workaround you are suggesting requires me to create a new email address just to register.  There isn't a way to register a username that is set apart from the email address.

**Comment by edtbl76** [comment]
Any thoughts? "Use a different email" isn't an acceptable solution.

**Comment by robdesautel** [comment]
I see this issue is closed, but I am having that issue now. I have attempted to contact support@insomnia.rest and a billing issue and I got an automatic reply. I attempted to reach out in slack and still no response. I have an important issue that needs to be resolved and I can't contact anyone. Can I get some help here.

**Comment by edtbl76** [comment]
Postman worked wonderfully for me. I haven't used Insomnia since I opened
this ticket.

**Comment by robdesautel** [comment]
I use postman too. I have a coworker that uses insomnia and thought I try it. But unfortunately this isn't an issue if functionality but getting someone to talk to about getting a refund because I was charged $50 for insomnia individual account and I am using a free account. But even then I don't see any subscriptions that cost $50. So I am bit agitated about this.

**Comment by edtbl76** [comment]
OUCH. I wonder if their twitter or instagram pages are still up? You could
post it there. If they're non-responsive in 24 hours, some financial
institutions will refund the money if you dispute it.

**Comment by robdesautel** [comment]
Thanks for the tip. I tried going the kong and their enterprise sales team and I am getting avoided about this.
