### ISSUE TITLE
[Bug] switch between request tabs not possible

### ISSUE THREAD

**Issue by lukaszgoworko** [getinsomnia/insomnia#596]
- Insomnia Version: Version 5.11.5 (5.11.5.1423) (Beta Multipart Response Pre Release)
- Operating System: macOS High Sierra 10.13.1 (17B48)

## Details
- some requests created on left panel
- selecting a request
- editing body (body tab => json)
- changing bearer token (auth tab => bearer)
- selecting an other request
  - ❌ beatify json area twice
- selecting a third request
  - ❌ third "beatify json" area appearing
  - ❌ no possibility to switch between tabs in the middle panel (like body or auth)

**Comment by gschier** [comment]
Hey @lukaszgoworko. That beta build I sent you introduced this bug, but it's since been fixed by https://github.com/getinsomnia/insomnia/commit/24118a40eb5021ba12d9acef8c2ffeafbc4a0292#diff-41c9ec1e1e36722cff731752e92c75d3

I triggered a new build that includes the fix. Once the CI finishes (in 10-30 minutes) the release files will be published here: https://github.com/getinsomnia/insomnia/releases/tag/next
