### ISSUE TITLE
[Feature Request] Remember Manage Environments window selection

### ISSUE THREAD

**Issue by jhalterman** [getinsomnia/insomnia#603]
## Details

Tiny feature request, but helpful - it would be great if the Manage Environments window remembered the environment I had last selected the next time it opens (including Base Environment).

I edit my environment variables a lot and I use the Base Environment a lot. Each time I open the Manage Environments window, the first Sub Environment is selected even though usually I want to edit something in the Base Environment, so I have to switch from my keyboard to mouse to select that.

**Comment by gschier** [comment]
Hmm, that's an interesting idea. Here's what I'm thinking might work.

- If the environment editor is closed while editing the currently active environment, open to the active environment next time (even if it's not the same one)
- Otherwise, remember the last environment that was edited and re-open that one

What do you think?

P.S. Would you be interesting in contributing a PR for this? If so, I'd be happy to help.

**Comment by jhalterman** [comment]
I think those rules make sense. I won't be able to submit a PR (too many other things to do :) ), but hopefully the feature suggestion is useful enough that someone can pick it up.

**Comment by gschier** [comment]
Yep. It's a good one for a first-time contributor. 

It's also a pretty quick one so I should be able to get around to it in the coming weeks.
