### ISSUE TITLE
[Feature Request] RSA-SHA1 Signature Method for OAuth 1.0

### ISSUE THREAD

**Issue by c22** [getinsomnia/insomnia#606]
- Insomnia Version: 5.11.7
- Operating System: macOS Sierra 10.12.6

## Details

Any chance we could have RSA-SHA1 implemented as a OAuth 1.0 signature method in Insomnia? Right now we have the option of Plaintext or HMAC-SHA1.

I haven't looked into how easy or hard this would be to implement but I am happy to help if we get some go ahead from the maintainers and maybe a point in the right direction.

**Comment by gschier** [comment]
Hey @c22,

Some help on this would be awesome!

This should be a fairly beginner-friendly task since it doesn't involve touching much of the codebase. These two files might be all you need.

For UI
https://github.com/getinsomnia/insomnia/blob/develop/app/ui/components/editors/auth/o-auth-1-auth.js#L197-L205

For generating the signature
https://github.com/getinsomnia/insomnia/blob/develop/app/network/o-auth-1/get-token.js#L12-L26

Let me know if you have any questions.

**Comment by c22** [comment]
@gschier thanks for the quick response. I am not sure if it's that simple. RSA-SHA1 signing requires specification of a private key, and this is not necessarily going to be the same private key used in TLS negotiation (ie. it's not necessarily going to be the key that you have assigned to a host in your workspace).

What do you propose? A textarea for pasting the private key if RSA-SHA1 is selected from the dropdown? Some way to specify a PEM file?

**Comment by gschier** [comment]
Ya, a textarea is probably fine. If you get it working with basic UI I can make it look nice (if you don't want to spend time on that part).

The ASAP auth has a private key field if you want to take a look. Also, the OAuth 2 auth has fields that conditionally appear if you want an example of that as well.

**Comment by c22** [comment]
This is pending review in #611
