### ISSUE TITLE
[Bug] Preview could not saved on right click "Save Image"

### ISSUE THREAD

**Issue by op-mime** [getinsomnia/insomnia#635]
- Insomnia Version: v5.12.1
- Operating System: Microsoft Windows 10, Version 1703 (Build 15063.632)

## Details
If there is a response with an image, in my case a JPEG, and I do a right click on the image and select "Save Image" nothing happens. 

### Workaround
Saving the image with the preview dropdown action "Save Response Body" works fine for me.

**Comment by gschier** [comment]
So... I was able to fix this but I'm not proud of how I did it. The error was being thrown from a dependency of a dependency so I didn't think it was worth fixing it for real.

I _think_ the bug was related to the webview object missing certain properties due to being loaded from a data URI instead of a URL. I faked the necessary properties so the module didn't fail.
