### ISSUE TITLE
Ordering & Filtering still not working - Please fix it ASAP!

### ISSUE THREAD

**Issue by marchpane** [getinsomnia/insomnia#6359]
### Expected Behavior

The list of requests shall be filterable and orderable. 

### Actual Behavior

The list of requests are not filterable or orderable. 

### Reproduction Steps

Open Insomnia
Try to filter the list of requests or
try to drag and drop a folder to a different location

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I'm confused why https://github.com/Kong/insomnia/issues/6284 and https://github.com/Kong/insomnia/issues/6288 got closed with the remark to #6323 as resolved. 

This, in my opinion, makes no sense as it is not the truth.  

Can anyone of the devs shed some light on it please and why you made such statements when they are clearly not true!? 🤷🏽‍♂️

### Insomnia Version

2023.5.5

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Installation method

Updated it via in-house updater

**Comment by leaumar** [comment]
I don't know how familiar you are with bug statuses, so just in case: you're not filing this because you believe a closed bug is supposed to mean the relevant release is available for download, are you? Bugs are always closed when fixing code is merged, the actual release to users is always later by any amount of time.
