### ISSUE TITLE
[Bug] GraphQL intellisense is broken

### ISSUE THREAD

**Issue by gerrod** [getinsomnia/insomnia#638]
Build 5.12.3 of Insomnia (5.12.3) seems to have broken Intellisense again for GraphQL.

Not sure if this is the same as the [last time](https://github.com/getinsomnia/insomnia/issues/577) I saw this issue crop up, but it only breaks once you're "two-levels deep":
```
# Intellisense works!
query {
    # Intellisense works!
    users {
        # Intellisense doesn't work :'(
    },
    
    # Intellisense works!
    accessGroup {
        # Intellisense doesn't work :'(
    }
}
```
The schema fetches successfully so I don't think that's the issue, and Intellisense is working in ChromeiQL.

(Running on Windows 10 x64)

**Comment by gschier** [comment]
Dang. Yep, I see the problem. If you're curious, the issue is from the GraphQL library doing an `if (something instanceof GraphQLSchema) {...}` but it fails because there are two libraries that define `GraphQLSchema`. I fixed this last time by doing an `npm dedup` before the build but that's proving to be a very brittle solution. going to need to find a more stable fix.

<img width="517" alt="image" src="https://user-images.githubusercontent.com/587576/33352307-23a35fd0-d4a0-11e7-8e84-7d67cc2aec56.png">

**Comment by gschier** [comment]
Even after "deduping" it's still not working this time.

**Comment by gerrod** [comment]
Ahhh, dependencies, what a world of fun! 🎉 🎈

**Comment by gschier** [comment]
Yep! I think I've figured it out now though. Will try to get a fix out for this tomorrow.

**Comment by gschier** [comment]
Just pushed a beta release for this if you want to give it a shot. You can get it by switching to the beta channel via the app settings.
