### ISSUE TITLE
[Bug] Editing a field in oAuth editor copies it to next request if selected too quick

### ISSUE THREAD

**Issue by janpieterz** [getinsomnia/insomnia#639]
- Insomnia Version:  5.12.3 (noticed for a while though)
- Operating System:  Windows 10 latest

## Details

Copying and pasting something into the oAuth 2.0 editor (at least client_credential based) can move the content into the next request if clicked within short timespan. See screen capture. I'm obviously gaming it here, but this occurred often when just naturally trying to copy/paste.

![insomnia copy](https://user-images.githubusercontent.com/383634/33383811-8e4cf132-d524-11e7-9701-564890ed99b6.gif)

**Comment by gschier** [comment]
Hey @janpieterz, thanks for the bug report!

I'm having some trouble reproducing the problem. It's hard to tell what's happening in your screen capture since I can't tell when you're clicking or pressing keys. It looks like you are quickly typeing/pasting content into an input and then switching requests? 

Can you elaborate (with words) in more detail the exact steps needed to reproduce this?

**Comment by gschier** [comment]
Hmm, I think I was able to reproduce it once. Maybe it depends on the amount of data in the app or the performance of the hardware.

I think it's due to the off chance that the active request is changed before the save handler is fired. Since the save handler updates the currently active request, the wrong request gets updated if this happens out of order. Does this sound like what's happening?

**Comment by janpieterz** [comment]
Hi @gschier, YW!

More than happy to! This happens when I'm bulk editing requests. In my case I was configuring the OAuth items to be set (it didn't seem to occur when copying-pasting the body of a request).

So if you have two requests, one for `Users` and one for `Accounts`, for ease of reproducing have both on the OAuth 2 ClientCredential flow.

1. Copy a piece of text in the `Users` `ACCESS TOKEN URL` field
2. *Quickly* Click in the left on the `Accounts` request
3. Clicking back to `Users` should _not_ show the `ACCESS TOKEN URL` field having any content
4. Clicking back to `Accounts` should show the content expected at 3

**Comment by janpieterz** [comment]
`Since the save handler updates the currently active request, the wrong request gets updated if this happens out of order.`

That sounds exactly like what's happening!

**Comment by gschier** [comment]
Awesome. Fixing now! 👍 😄

**Comment by gschier** [comment]
Looks like this is a much more involved problem than initially expected. Going to have to think about a good solution for a while first..
