### ISSUE TITLE
All my data lost - "Failed to create remote project"

### ISSUE THREAD

**Issue by PerLycke** [getinsomnia/insomnia#6579]
### Expected Behavior

I had a lot of local data setup. After creating an account using Google, migration tool reports "Failed to create remote project". Everything seems lost, I have no idea how to recover my local data. I'm in the middle of some big work and this is truly screwed up as the app was auto-updated.

### Actual Behavior

"Failed to create remote project"

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.0

### What operating system are you using?

macOS

### Operating System Version

13.6

### Installation method

downloaded

### Last Known Working Insomnia version

Before 8.0

**Comment by bxjw** [comment]
yep, my scratch pad also disappeared all of my working data...

**Comment by minusfive** [comment]
Same here, + I feel I'm being strong-armed into uploading everything to your cloud. How do I get my data back?

**Comment by smnbbrv** [comment]
Same as well - how to restore the data? I mean I could not choose not to upgrade...

**Comment by mkdillard** [comment]
> Same here, + I feel I'm being strong-armed into uploading everything to your cloud. How do I get my data back?

The other issue thread (#6577) started on this has steps to do so: https://github.com/Kong/insomnia/issues/6577#issuecomment-1737957278. Turn off automatic updates and downgrade, the data is still there, just not being displayed by 8.0

**Comment by PerLycke** [comment]
We are indeed forced to upload all our data to cloud with the 8.0 update. What a truly awful behaviour.

**Comment by wodrich** [comment]
My company won't likely approve this for use, now that it's storing data in the cloud.  Lost everything I was using for testing, URLs, payloads etc.   So frustrating.

**Comment by dyerjos** [comment]
I also had to rollback to the previous version to get my data back. I don't know about other people but I use Insomnia because it's open source and keeps my data local. Take away the local aspect and I'll start using Postman. Not happy about the direction this is going

**Comment by dyerjos** [comment]
Current fix for people here is to roll back to https://github.com/Kong/insomnia/releases/tag/core%402023.5.8 and you should see your data again. Step 2, turn off automatic updates

**Comment by minusfive** [comment]
Yeah, no way our company will allow us to use this now.

**Comment by stefanks** [comment]
Lost data too, have to roll back :(

**Comment by artiebob** [comment]
Our company will not use this if data is in the cloud.  We would pay for a local cloud version or alternative but not something hosted externally.

**Comment by subnetmarco** [comment]
Hello,

Insomnia 8.0 doesn't migrate to the cloud any data unless you create an account or login. 

* You can export the data from the initial wizard (screenshot below).
* You can export with an older version of Insomnia.
* You can even re-import a collection into Scratch Pad and it will be always local.
* If you sync to the cloud, the data is fully end-to-end encrypted (E2EE).

![image](https://github.com/Kong/insomnia/assets/964813/916ab291-d69b-469c-a7ef-72beaddc6797)

**Comment by PerLycke** [comment]
Is the bold text on the line at the bottom with smaller font size compared to the rest of the text a link to save your data?

Also, if you click continue, how do you go back to this screen? Or where is the clear option to use your service locally after continuing beyond this screen? Also, if you go beyond this screen, your data is lost as there is no clear option how to recover it.

This whole update is all about forcing users to upload their data to the cloud.

Funny thing is, even if users try to go cloud your migration tools are broken. Laughable

**Comment by codinronan** [comment]
Just put out a request to my team to find a different tool for us to use.

This is why we can't have nice things.

**Comment by codsane** [comment]
I originally started using and grew to like Insomnia because it didn't force cloud features down your throat like *others* do.

It appears Insomnia is starting to become no different than the *others*.

I'll be switching immediately, so long Insomnia.

**Comment by subnetmarco** [comment]
Data can be recovered by downloading an older version of Insomnia. We are also adding an export also in the Preferences, to make it easier to do (this will ship in a minor 8.1).

Either way - nobody can look into the data when it's in the cloud - not even we can do that, because of E2EE.

A collection can also be re-imported in Scratch Pad which is always local.

**Comment by codinronan** [comment]
> Data can be recovered by downloading an older version of Insomnia.

Why can't it be recovered via the new version?

**Comment by codsane** [comment]
> > Data can be recovered by downloading an older version of Insomnia.
> 
> Why can't it be recovered via the new version?

Would appreciate an answer to this as well. This is a UX oversight so big that it's hard to see it any other way than a dark pattern to get you to sign up to the managed platform. Disappointing either way.

**Comment by subnetmarco** [comment]
It can via the onboarding wizard, but we are adding a way to export it via the Preferences (most likely in 8.1).

In the meantime, you can use an older version. You can even re-import a collection into Scratch Pad and keep it local forever.

**Comment by PerLycke** [comment]
@subnetmarco you mean clicking on the embedded button in the bottom left with such a small emphasis that it requires you to know it is a button beforehand? On the wizard that shows once and that you cannot re-visit if you clicked "continue".

If that is not hiding a feature you don't want your users to use, I don't know what is.

Emphasis wise - all you want to achieve with this update is to move users to cloud. Extremely low, nearly non existent, emphasis on enabling users to stay working locally.

**Comment by codinronan** [comment]
Yeah at the risk of piling on, a piece of productive feedback: I did not know that was a button. It looked like a message so I just clicked continue. There's no indicator it's a button, you should fix that with a "click here" or "export your data by clicking here" or something. AND a way to get back to that screen - or the function it would have exposed.

**Comment by eternalblue** [comment]
What. The. Actual. Frack.

As others mention, we have been using Insomnia because it is not forcing some cloud-based stuff down our throats. 

I understand that you need some way to monetize this, but at least have the decency of not hiding the migration part to (friendly)force everyone to migrate...

> It can via the onboarding wizard, but we are adding a way to export it via the Preferences (most likely in 8.1).

How convenient 🙄🙄🙄

**Comment by af80a** [comment]
> Yeah at the risk of piling on, a piece of productive feedback: I did not know that was a button. It looked like a message so I just clicked continue. There's no indicator it's a button, you should fix that with a "click here" or "export your data by clicking here" or something. AND a way to get back to that screen - or the function it would have exposed.

It's some common shady practice.

**Comment by subnetmarco** [comment]
I have created a [comment here](https://github.com/Kong/insomnia/issues/6577#issuecomment-1738131554) with a FAQ about the recent change that answers many questions you may have.

**Comment by cha-king** [comment]
Seems I've also lost all of my data. Unfortunately I don't think I was ever presented with any onboarding wizard, or at least I didn't notice if I was. If I now attempt to export any data from the preferences, I'm told that I have no workspaces to export.

I assume I need to downgrade in order to retrieve my data? Any pointers on how to do this? Is there any chance that reinstalling via .dmg will erase my prior data?

**Comment by codinronan** [comment]
> Seems I've also lost all of my data. Unfortunately I don't think I was ever presented with any onboarding wizard, or at least I didn't notice if I was. If I now attempt to export any data from the preferences, I'm told that I have no workspaces to export.
> 
> I assume I need to downgrade in order to retrieve my data? Any pointers on how to do this? Is there any chance that reinstalling via .dmg will erase my prior data?

Just go to the [prior release in the Releases section of the repo](https://github.com/Kong/insomnia/releases/tag/core%402023.5.8) and install it over your existing version. It worked for me, data was there. I immediately turned off automatic updates.

**Comment by padge** [comment]
This was the SECOND TIME I've upgraded Insomnia and lost all of my requests. The first time was a couple months ago and the second time was today with the latest version. Thankfully uninstalling and reverting back to 2023.5.8 brought them back. I just disabled automatic updates and plan to stay on this older version.

**Comment by harpreetsingh91** [comment]
It was a perfectly fine tool with no need for a signup. Thanks for letting all the developers know not to recommend Kong to their company. In the meantime I will just fork an older version.

**Comment by helder-garcia** [comment]
All my data is gone :/

**Comment by subnetmarco** [comment]
The data is still there. You can simply downgrade to a previous version of Insomnia. You can also keep using Insomnia locally with Scratch Pad.

**Comment by drtz** [comment]
> The data is still there. You can simply downgrade to a previous version of Insomnia. You can also keep using Insomnia locally with Scratch Pad.

Thanks for the tip, I recovered by installing 2023.5.8 from here:

https://github.com/Kong/insomnia/releases/tag/core%402023.5.8

**Comment by cooperfrench95** [comment]
> \>open insomnia
> \>asks me to update
> \>click later
> \>app won't stop spamming me with this request to update
> \>fine, I'll do it
> \>suddenly I'm supposed to sign in
> \>click go to scratch pad because why would I need to sign in? sending requests locally works just fine
> \>all my data is gone unless I sign up for this nonsense

Whose bright idea was this? I can't speak for everyone but I know personally the only reason I started using insomnia was because Postman had started doing a bunch of stuff like this. Pestering me to sign in every time I opened the app. 

Literally who asked for this? Why does every single service feel the need to harvest my email address? Add a "leave me alone" button next time.  Good lord.

**Comment by DeployIsComing** [comment]
> Same here, + I feel I'm being strong-armed into uploading everything to your cloud. How do I get my data back?

I managed to get my data back using these paths:

%APPDATA%\Roaming\Insomnia on Windows
$XDG_CONFIG_HOME/Insomnia or ~/.config/Insomnia on Linux
~/Library/Application\ Support/Insomnia on macOS


if they kept my local projects working I wouldnt mind about the login banner etc possibly I would login. But BLOCK all my projects just because Im not loggedin???? thats not how it works!!

well I have my backup gonna check now how to compile a version of a standlone Insomnia or I gonna move to other client.

**Comment by DeployIsComing** [comment]
If you guys have a compiled working version of Insomnia WITHOUT this login thing please provide me the link.

**Comment by relm** [comment]
Why doesn't the latest version just auto import your old collections in the new scratch pad? That way, users wouldn't be freaking out that their data was missing. Not to mention, the upgrade notification didn't signify that this was anything other than a usual update. There should have been some warning that there were breaking changes in this release (At least if you don't have an account or don't use the Cloud sync).

It seems like the direction is clear now, the local storage is an afterthought and future features will be designed around the cloud subscriptions. I don't have any faith my data will stay intact across upgrades anymore.

Looking into alternatives now.

**Comment by subnetmarco** [comment]
> Why doesn't the latest version just auto import your old collections in the new scratch pad? That way, users wouldn't be freaking out that their data was missing. Not to mention, the upgrade notification didn't signify that this was anything other than a usual update. There should have been some warning that there were breaking changes in this release (At least if you don't have an account or don't use the Cloud sync).

The Scratch Pad is more lightweight because it doesn't handle multiple projects or anything that is not a collection. Many users have lots of files, design specs, tests and it would not have been possible to show their data in the Scratch Pad.

To clarify: no data is migrated anywhere without creating an account or logging in.

We did create a wizard with illustrations to talk about this upcoming change:

![form](https://github.com/Kong/insomnia/assets/964813/0ea5c9ae-029d-4f03-ad68-0c73d6e956db)

Tomorrow or Friday the latest we will make it more clear, and also we will make it better to export the data right away. This will ship in Insomnia 8.1. Today you can also install a previous version of Insomnia and still see your data, or export it.

> It seems like the direction is clear now, the local storage is an afterthought and future features will be designed around the cloud subscriptions. I don't have any faith my data will stay intact across upgrades anymore.

We will land in the Scratch Pad all API debugging features (ie: if we support a new transport) but collaboration features and more will require an account, because it is fundamentally needed to do the things that we want to do (we cannot implement collaboration - which many users want - if all data is siloed).

Finally, one more thing: with Git Sync, your data is not going to the cloud but stays in the Git repository that you have configured.

**Comment by jdgarcia** [comment]
> The Scratch Pad is more lightweight because it doesn't handle multiple projects or anything that is not a collection. Many users have lots of files, design specs, tests and it would not have been possible to show their data in the Scratch Pad.

You should still auto-import anything that didn't require cloud collaboration. Anything that used to work without an account should still continue to work in Scratch Pad.

**Comment by 0x346e3730** [comment]
I had the unpleasant surprise to loose all of my workspace after upgrading to 8.0, with no prior warning or whatsoever. Insomnia is the second API client I'm blacklisting after Postman and I will use Hoppscotch from now on. Not thank you.

**Comment by gabel** [comment]
I don't get it why Insomnia is trying to fail the same way as Postman did? Within a larger corp we are moving away from Postman now and most where willing to use Insomnia. Even a paid version without cloud synchronization would've been possible IF you would have offered such solution. But doing the same mistake as Postman? Weird decision making here.

**Comment by nickbg321** [comment]
Not auto importing the user's previous data and not making this obvious via some warning message is an incredibly poor way to handle things.

I used to be a long time Postman user and I ditched it in favor of Insomnia for the exact same thing Insomnia is now doing. Guess it's time to look for a new REST client, again.

**Comment by dennisMeeQ** [comment]
I am sad. Why did you kill a perfectly good tool with the need for cloud sync? Time to look for alternatives, I guess :( Any suggestions?

**Comment by schmurfy** [comment]
the default behaviour should be transparent, all our data should be there by default in the scratchpad after upgrade. If you wanted us to use something else that's a good way to do it.

**Comment by af80a** [comment]
> The Scratch Pad is more lightweight because it doesn't handle multiple projects or anything that is not a collection. Many users have lots of files, design specs, tests and it would not have been possible to show their data in the Scratch Pad.


Wouldn't it have been easy to leave Scratchpad as Insomnia was until this point and add the new features in a different "home" component?

**Comment by Rzpeg** [comment]
I don't want to store data on cloud. I want to be able to use the stuff you have in free tier, that I used before 8.0, without needing a login button. I don't understand why I need to login to write a unit test or use plugins!

Paid features are fine, but if you leave stuff on free tier, make it usable offline

**Comment by eat-pant** [comment]
Hello! Friendly local neighborhood InfoSec here!

For us EU users who have had our test data unexpectedly synced to 'the cloud', it has now been transmitted to the US and, regardless of encryption in place, may now be a reportable GDPR breach! (depending on what information was contained and the regulatory compliance that your business is subject to) 

Note: this may be a breach inside the US as well for cases involving HIPAA or other compliance where legal control is needed of data that is off-premises!

Make sure to reach out to your local support teams as needed for help :)

**Comment by Mudbill** [comment]
This is incredibly disappointing. I'm sorry to say, but it's hard to tell if this update is malicious or just pure ignorance. Someone either didn't think this through or thought about it a great deal and went ahead with it anyway. Either way it is a good sign to steer clear of Insomnia if this mentality is at the helm.

**Comment by Nek-** [comment]
God this was intense losing everything for some minutes... Rollback works... thanks @dyerjos you saved my day 😅 .

To insomnia team, thanks for the product, but really this kind of loss for such product is not acceptable at all, please shutdown auto-update remotely (no idea how, by removing the release?) as soon as you can...

Side note: I accepted any cloud stuff you added, still lost everything, in case you wonder.

**Comment by subnetmarco** [comment]
Duplicate of https://github.com/Kong/insomnia/issues/6577

**Comment by phil-nelson-bt** [comment]
Once you've hit continue, and then choose to use the scratch pad, there doesn't seem to be a way to get back to the wizard to do the export/import dance you described. As for using the cloud and "it's encrypted end to end", without any way to know specifically what that means, how secrets are kept for that encryption, what your policies are, how they are audited, basically the all requirements of a password manager, there is no way we'd be able to consider this solution and have environments setup with all the sensitive data it takes to interact with them. You must know this. 

I'll try the roll back and disabling up auto updates and check back here in a week or two

**Comment by subnetmarco** [comment]
> Once you've hit continue, and then choose to use the scratch pad, there doesn't seem to be a way to get back to the wizard to do the export/import dance you described. As for using the cloud and "it's encrypted end to end", without any way to know specifically what that means, how secrets are kept for that encryption, what your policies are, how they are audited, basically the all requirements of a password manager, there is no way we'd be able to consider this solution and have environments setup with all the sensitive data it takes to interact with them. You must know this. 
> 
> 
> 
> I'll try the roll back and disabling up auto updates and check back here in a week or two

With 8.1 and are adding the export  button front and center. It will ship later today, tomorrow the latest.

**Comment by luke37b** [comment]
"if it ain't broke, don't fix it"

**Comment by javibookline** [comment]
thanks for making life difficult for all of us

**Comment by subnetmarco** [comment]
I'd like to ask a few questions, so I understand better some assumptions on my part that may be wrong:

1. How important is E2EE encryption to you all? We went the extra step to implement E2EE pretty much everywhere we could (it was a huge effort) but I seem to understand that it doesn't matter that much. With E2EE essentially nobody can access the data, not even we can do it, but it seems like it's not making anybody at ease still. 
2. Let's say that we present a 3rd party independent auditing report from a reputable source that validates that your data - even when stored in the cloud - is fully encrypted, would that even ease things out? Again, this data is inaccessible without the correct passphrase that only the user knows.
3. The local storage capability was very complex and - knowing we have E2EE - we wanted to greatly simplify the complexity of the application while at the same time supporting our customers that require more and more collaboration features. Let's assume that we ship an offering for "Local Vault" where:
    * You can keep your collections, design specs and overall data local only, encrypted on a project by project basis.
    * Collaboration is disabled by default, but you could still optionally enable it in the cloud (with E2EE) in case you wanted to do that in the future, to not preclude users that _do_ want to collaborate from being able to do so.
    * We would properly staff for the long-term continuity of this capability and make it officially supported as part of our offering for a monthly/annual subscription fee.
    * Would this be something that you would use?
4. Finally, when it comes to API data, typically there are URLs with their parameters and responses, then there are credentials and secrets stored in cookies and/or environment files:
    * Would storing locally environments, cookies and authentications **only** be sufficient for your use-case, or does it have to include also the "interface" of the collection routes (the URLs, the empty params, etc)?
    
cc @wodrich @minusfive @artiebob @gabel and others.

**Comment by Mudbill** [comment]
I appreciate the attempt to correct things. However, while encryption is important and should be a given for any sync service, it's not enough to guarantee safety for every situation. If the encryption is really strong but a password is weak, it can be cracked. Regardless it could be leaked. That's an unnecessary risk for many.

The sync part **must** be **opt-in** in my opinion. Only that can satisfy both those who want the convenience of sync and the reduced risk of local.

**Comment by DeployIsComing** [comment]
Sending my data to someone's computer, in reality, a cloud server is it! It can be encrypted or whatever, but still, I'm relying on someone's computer. There's no free lunch. Who is going to pay for that? Server? Storage? Energy? If you are not paying, it is because you are the product, or insomnia is thinking to get some data to profit, or insomnia is planning to charge soon and you are in their hands. Nobody is that kind to give free server access for free.

**Comment by nabilfreeman** [comment]
We don't want cloud and we don't want user accounts

**Comment by davehouser1** [comment]
I did a back up before I upgraded.
I then went through the wizard like everyone else did and missed the "export" section. So after all that the scratch pad has none of my data.  
I tried going to where import was before Preferences > Data, but "import" is greyed out, wtf?
However if you go to the top left and select "Scratch Pad" > "Import" you can import the data.

Biggest problem with this, **where the hell is Unit Testing**? I had 100's of tests that I auto ran. They are all gone, and I cant seem to find a way to view tests in the scratch pad. Is this feature dead? 

Is this what the Kong team has been working on for months? This is so many steps backwards. 
@subnetmarco,  your solution to just "downgrade" is not a good solution at all. 
That means I can never upgrade again? Do I have to constantly check if new updates will include the features my old export needs? 

But I guess this is what's happening now in software. Its not cheep or easy to support software. Giving out a product for free just to get word of mouth is a ending trend. I will never trust a company that says "we don't have access to your data" when the application forces you to create online accounts and sync data. More so my company (and many others) don't support this, its 0 trust sir, does not matter if you say you don't have access to our data, we will not support this.

Unfortunately I have to downgrade and use this older version because I have yet to see a worthy, free alternative that is not Postman. And right now our company does not allow Postman, wont be surprised if Insomina will be dropped too. 

**EDIT:** Unit tests are still there, you have to login to use them though [see this discussion.](https://github.com/Kong/insomnia/discussions/6677#discussioncomment-7334098)

**Comment by nabilfreeman** [comment]
@davehouser1 check out Insomnium https://github.com/ArchGPT/insomnium.

I set it up today with a full export out of Insomnia and it brought over all my projects, collections and environment variables.

Hopefully tests will be in there too (I don't use that feature so can't be sure)

If you can exit the scratchpad and get back to the wizard, I did somehow manage it, you can do an export from there.

**Comment by phil-nelson-bt** [comment]
First off, all of us complaining about something that is released for free and for which the source is available, triggers a lot of bad memories from open source projects I've been involved with, none of which have anywhere near the reach of Insomnia. Trying to find a way that at least some people can support the developers so they aren't burned out volunteers makes it more likely the thing will be around. In this case it is probably employees, but how to use the time still is an important question. 

@subnetmarco to answer some of your questions:
- if we were to accept a cloud based solution, E2EE encryption with a good audit history, would be more acceptable. Not sure if that means we'd purchase a subscription, but more likely
- on a side note, people who really think that their local workstation is more secure than a company that with an audited design and controls that is trying to protect your data, clearly haven't followed the history of hacking and today's ransomware attacks. 
- locally encrypted secrets would be great, possibly a feature worth paying for. using keychain's locally doesn't seem that hard either
- keeping urls, parameters, body shapes, responses private, yeah that stuff would be gold for a hacker looking for vulnerabilities and design weaknesses. Perhaps keeping it local is enough, not encrypted.

**Comment by eat-pant** [comment]
> 1. How important is E2EE encryption to you all?
> 2. Let's say that we present a 3rd party independent auditing report from a reputable source that validates that your data - even when stored in the cloud - is fully encrypted, would that even ease things out?
> 3. The local storage capability was very complex and - knowing we have E2EE - we wanted to greatly simplify the complexity of the application while at the same time supporting our customers that require more and more collaboration features. Let's assume that we ship an offering for "Local Vault" where:

>    * Would this be something that you would use?
> 4. * Would storing locally environments, cookies and authentications **only** be sufficient for your use-case, or does it have to include also the "interface" of the collection routes (the URLs, the empty params, etc)?
> 
> cc @wodrich @minusfive @artiebob @gabel and others.

Good questions! @subnetmarco 

At least for us, cloud-syncing (E2EE or not) simply represents an added layer of risk and complexity with limited impact on conduct of 99% of daily work, when the majority of testing taking place is from the test application towards a localhost VM on the same machine, or a test environment from within the same building/network with no external connectivity needed. 

I can't speak for everyone, but E2EE could certainly be a *nice to have* in some cases, but really represents only a fraction of many concerns/strategies in order to operate in a legally compliant way, especially from a data handling and security risk perspective. Industries like Banking, Healthcare, Industrial Sector, IOT Home Systems and many others have very **very** strict regulations in order to be allowed to conduct business, which comes with a large list of security controls, monitoring, data handling, traceability, auditing, training and infrastructure management that must be adhered to, regardless if the developer/tester feels it is secure or not.

**Comment by subnetmarco** [comment]
@eat-pant Have you seen the new 8.3 release? It allows you to store data locally again, without the Cloud Sync. So now you can choose between Local, Cloud or Git at your discretion.

**Comment by DeployIsComing** [comment]
> @eat-pant Have you seen the new 8.3 release? It allows you to store data locally again, without the Cloud Sync. So now you can choose between Local, Cloud or Git at your discretion.

Come on... are you joking with us? I downloaded this 8.3v I tried to import the very same file of my old Insomnia and I got this message: 

Error while importing to Insomnia:
Cannot import multiple files to ScratchPad. Please try to import your files one by one.

I just informed one file!

**Comment by subnetmarco** [comment]
@iradofurioso 

* Scratch Pad is only for one collection.
* All the other capabilities are available after creating an account. And with an account, you can choose between Local Vault, Cloud Sync and Git Sync.

You can still import one collection into Scratch Pad - but when I talk about product capabilities, I am referring to the full product capabilities available **after** logging in.

**Comment by DeployIsComing** [comment]
> @iradofurioso
> 
> * Scratch Pad is only for one collection.
> * All the other capabilities are available after creating an account. And with an account, you can choose between Local Vault, Cloud Sync and Git Sync.
> 
> You can still import one collection into Scratch Pad - but when I talk about product capabilities, I am referring to the full product capabilities available **after** logging in.

🤡



well I wont create an account, you guys still playing with the ones who used the tool for a long time and have a lot of projects and now you are forcing to create an account. Last try I gonna uninstall and move to another tool, hopefully theres a lot on the web.

**Comment by subnetmarco** [comment]
That's perfectly reasonable, you can use one of the many export data buttons if you wish to access your data and re-import it somewhere else.

**Comment by gabel** [comment]
Just to have an answer here and to make it clear, it is not about E2EE encryption. There are always environments where air gapped and/or non-account use-cases are valid.

**Comment by satokenta940** [comment]
After encountering issues with Insomnia, our company is now evaluating a switch back to **[Postman](https://apidog.com/blog/postman-vs-insomnia-for-api-testing/)** or **[Apidog](https://apidog.com/)**

**Comment by subnetmarco** [comment]
@satokenta940 this is not a billboard.
