### ISSUE TITLE
Upgrading to Insomnia 8 has deleted or hidden all of my queries and configuration

### ISSUE THREAD

**Issue by GeeDat** [getinsomnia/insomnia#6585]
### Expected Behavior

Updating Insonmia version should not remove existing queries or config

### Actual Behavior

Updating Insomnia to version 8 removes all queries and config.

I allowed Insomnia to update automatically as usual. The update to version 8 has removed all of my query history and configuration. I first tried using scratchpad and then created an account, which said it was synchronising, but still no sign of anything. This represents many many hours of work and if I have to recreate these, I may as well swtich to another application which I can trust with my data. 

### Reproduction Steps

Accept the update dialogue in Insmonia 7
Follow the on screen steps
All queries and config have disappeared

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.0.0

### What operating system are you using?

macOS

### Operating System Version

Mac OS Monterey

### Installation method

Already installed. This was an in app update. 

### Last Known Working Insomnia version

7

**Comment by luciano-fiandesio** [comment]
Same problem here, completely unacceptable. Fortunately, I had a recent export of my queries, but I'm dropping Insomnia NOW.

**Comment by garybaines** [comment]
Same here.  I downgraded back to the prior version (I just installed it over the top - Mac M2), then turned off automatic update, and can now see all my old queries again.

**Comment by luciano-fiandesio** [comment]
@garybaines how did you downgrade?

**Comment by merc1er** [comment]
> garybaines how did you downgrade?

You can download the desired release from the releases page: https://github.com/Kong/insomnia/releases

**Comment by roughiain** [comment]
How the F$#% did this get past QA

**Comment by finkmanAtSap** [comment]
This is the nail in the coffin for me after seeing the release popup with all the new cloud capabilities of v8. Apparently Insomnia wants to follow the path of Postman, making $$$ via licensing while turning it into a slow, feature-bloated mess. In my opinion, it is sacrificing its unique selling point: being a light-weight, free to use and blazingly fast alternative to Postman because there is no HTTP communication hidden behind every mouse click.

**Comment by apalfonso-fln** [comment]
How to kill an app 101.

**Comment by jonashcroft** [comment]
To anyone like me who lost their data during the 8.0.0 upgrade, it looks like the data does still exist and is exportable to a JSON object.

Settings > Data > Export

<img width="431" alt="Screenshot 2023-09-28 at 10 21 31" src="https://github.com/Kong/insomnia/assets/19237116/2ccb4dcd-1b79-4af5-967a-0e9808a0bd3e">

<img width="488" alt="Screenshot 2023-09-28 at 10 23 06" src="https://github.com/Kong/insomnia/assets/19237116/25d584f1-6034-4e66-a5d1-701778ca8f2f">

**Comment by finkmanAtSap** [comment]
Does not work for me, unfortunately:

![image](https://github.com/Kong/insomnia/assets/123368068/ac046ce1-d0a8-4390-98d6-8845a59aa8cb)

**Comment by renickbuettner** [comment]
Same here. It restored everything after signing in into their new cloud service.

Why the hell to I need so use a cloud service now? I got Insomnia because it had no cloud...

**Comment by jpweijers** [comment]
I get that they want to make money but I really don't want a second postman. I'll be downgrading to the last version before version 8.0.0 and turning off auto-updates

**Comment by pcvvelzen** [comment]
https://learning.postman.com/docs/getting-started/importing-and-exporting/importing-from-insomnia/

**Comment by ewertonls** [comment]
same issue here, also i don't want to sign up or login to use a http requests collection. i used insomnia because there was no required cloud or accounts

**Comment by vic-bukhantsov** [comment]
Same here,

rollbacked to the previous release.

**Comment by mateusneresrb** [comment]
Complicated, I was using postman and migrated so I wouldn't have to log in and save to the cloud, and now they're forcing me to.

**Comment by rajatgiri-ec** [comment]
Rolling back to the [2023.5.8](https://github.com/Kong/insomnia/releases/tag/core%402023.5.8) worked for me.

Don't forget to disable automatic software updates from preferences.

**Comment by octavd** [comment]
Indeed this version 8.0 seems MAJOR as deemed by the developers. It's a MAJOR thing loosing everything after an upgrade.

**Comment by aarbi** [comment]
I won't hate on insomnia, we all know that those issues might happen with major releases.
For now, I downgraded to [2023.5.8](https://github.com/Kong/insomnia/releases/tag/core%402023.5.8) as suggested above.
I will wait for a future release where all the workspaces and projects are smoothly moved to v8

**Comment by bredwrd** [comment]
Downgrading to [2023.5.8](https://github.com/Kong/insomnia/releases/tag/core%402023.5.8) has restored my requests. Signing into a cloud platform is not an option for me since my requests may contain sensitive data that I certainly don't want (or need) to be hosted on a cloud platform.

Fortunately, downgrading is an easy solution, compared to the [last time](https://github.com/Kong/insomnia/issues/5559#issuecomment-1362946901) an Insomnia auto-update lost all of my requests, when I had to manually tinker with database files and re-create my folder structure from scratch. Progress!

**Comment by Dobbychen** [comment]
I've also downgraded to [2023.5.8](https://github.com/Kong/insomnia/releases/tag/core%402023.5.8). When upgrading to a major version with one click from auto-update, insomnia introduces a sudden change of major UX and loss of user data, didn't see this coming at all.

**Comment by meshpaul** [comment]
This Version missing  a way to share exported collections

**Comment by meshpaul** [comment]
I had a previously shared the exported version of Insomnia collections pre Version 8 when trying to import data I get the following error

<img width="1710" alt="image" src="https://github.com/Kong/insomnia/assets/2071771/b9f35612-f57b-4524-b141-bf07d0a6290f">

**Comment by gmac** [comment]
Downgrading has not restored my data. Annoying. Wish I'd turned off auto-updates a long time ago.

**Comment by selcuktemizsoy** [comment]
same problem here, I lost all my data and can not retrieve my requests. I also don't want to sync my data with insomnia cloud but there is only one option to use insomnia and it is logging in and syncing your data which is not acceptable. 

Edit: removing updated version and installing this version restored my workspaces. https://github.com/Kong/insomnia/releases/tag/core%402023.5.8

**Comment by Apophenia** [comment]
Downgrading to [2023.5.8](https://github.com/Kong/insomnia/releases/tag/core%402023.5.8) has restored my requests as well. This is an unthinkable change to me; I imagine the reason why many _employers_ were chill with Insomnia was because it doesn't push developers into syncing sensitive data.

**Comment by userBarbosa** [comment]
Same problem here, i had so many collections that i don't have any backup. dayum, i'm fcked.

Edit: even after downgrading to [2023.5.8](https://github.com/Kong/insomnia/releases/tag/core%402023.5.8) i didn't get my requests back. I also tried to restore via .config dir but all files were updated to 0 bytes:
![image](https://github.com/Kong/insomnia/assets/87672055/e0ef76d3-b459-4baf-91c6-1e8c87aa5527)

Thank you Kong :smiley: :+1:

**Comment by csmithmtb** [comment]
Same problem. I understand the need to make money to pay for the development of the product but there are organizations that don't allow API test requests to be stored in the cloud (or at least a cloud that hasn't gone thru a lengthy, thorough review process).

**Comment by dan-frohlich** [comment]
Rarely have I been so sad to have executed an application upgrade.
Losing all my saved requests was one thing but this "cloud sync" roadblock/modal pop-up I face on startup is a killer. 

As a developer at an organization that cares about exfiltration, this is a serious issue. The default behavior on this new "cloud sync" pop-up appearing in v8 is to encourage exfiltration of internal architecture.

Hard pass.

**Comment by ClaasGnerlich** [comment]
I've never had any problems with Insomia. Now I am also affected by the data loss/hide. And all because of the intrusive update popper. Jumping to the previous version helped me see all the data again and continue working normally.

Very unfortunate. I will now stay on version 7 and wish Kong all the best for the future.

**Comment by austinwofford** [comment]
After downgrading to version 8, I'll be upgrading to version 7 until I can find a replacement. I've been using Insomnia since 2016 and have convinced countless coworkers to switch from Postman. It looks like Hacker News has a nice thread of replacements that people like.

**Comment by JeanPoffo** [comment]
This new update brought everything we liked that WASN'T in the app. Cloud, need to login, changing color palette, corrupting old collections. A real shame.

**Comment by gbrlmtrz** [comment]
What a way to ruin a perfectly working app. ~~also, downgrading doesn't seem to restore data on Ubuntu so there is that.~~

If you need to downgrade on ubuntu, make sure you downgrade the same version that is, if you were using a snap you need to the snap release, and if you were using the .deb package you need that one.

**Comment by CoolGoose** [comment]
How to do a disastrous release. This makes 0 sense to not even be allowed to see my previous local data without popping up the whole account setup down my throat.

**Comment by gbrlmtrz** [comment]
> Rolling back to the [2023.5.8](https://github.com/Kong/insomnia/releases/tag/core%402023.5.8) worked for me.
> 
> Don't forget to disable automatic software updates from preferences.

Where is the disable automatic updates option? i don't see it on the linux version.

**Comment by stmcox** [comment]
Scroll down in Preferences,
![image](https://github.com/Kong/insomnia/assets/46358245/6656cd30-0648-442f-9cb8-80a99259e62b)

**Comment by fenneclabs** [comment]
Thanks for the advice to downgrade, I recovered my requests and made an export of it.

Any advices for another application that does not require a cloud account to work?

**Comment by choas** [comment]
As it's still open source don't forget to fork it and then checkout the core@2023.5.8 tags to build your own version.
This allows you to change "Made with" into "F***ed up with 💜 by Kong"

**Comment by skhaz** [comment]
I also lost all my data, and I used Insomnia precisely because it wasn't related to the cloud.

**Comment by gbrlmtrz** [comment]
> Scroll down in Preferences, ![image](https://user-images.githubusercontent.com/46358245/271335454-6656cd30-0648-442f-9cb8-80a99259e62b.png)

Thanks for the reply, the option doesn't seem to be there for Ubuntu, what I did was to make the installed snap bin file read only... and hopefully that will work.

**Comment by tuwid** [comment]
I get it that I'm not paying for this and I have no say but man, it HAD TO HAPPEN NOW that I had to deliver my stuff... 
Instead of focusing on my deliverables have to investigate why all of a sudden all my stuff is gone and why I have to use a cloud netflix subscription model  😆 
Thanks to the folks giving advice here. I'm downgrading and turning off updates. Most likely will ditch this and move to something that resembles what insomnia used to be..
I wish the insomnia team all the best in their pursuit of greed/happiness  

Edit: clarifying thought process

**Comment by sdkuck** [comment]
Revert to 2023.5.7 and find a good fork.

**Comment by subnetmarco** [comment]
We have shipped 8.1, here is a video on how to use data in the cloud or locally:

[Watch video](https://www.loom.com/share/de7af6f9e06b4452a799a033604f9270?sid=df0baa8f-8916-4560-a8aa-6fe9ba21b0ec)

**Comment by e3roll** [comment]
If you can't see your queries and want to use Insomnia offline, this is the solution:


1. On login screen, click "Export data and more"
3. Save to a local folder
4. Click "Use the local Scratch Pad" -> Scratch Pads opens.
5. Click "Scratch Pad" at the left pane
6. Click "Import"
7. Open `wrk_{id}.json` file

**Comment by naokichau** [comment]
same here guys, loss all requests, like 40+ of them 🥲 another one become postman

UPDATE: managed to recover them 🙏 in 8.1.0, still please don't become postman 🙏

**Comment by CQD** [comment]
Configs in base environment is not getting exported, at least not for me.

Downgrade works,  base environment is also there. But the update dialog pop up right after I unchecked auto update check box, so I have to do it a second time.

-----

Some other thoughts:

I believe "not synced" should be an easy option. End-to-end encryption is good to have, but I still don't want to send my (and my client's) dev server address and all private endpoints to anywhere in any form.

There's no such option in 8.x starting screen, so it looks like I could not get un-synced without being synced in the first place. This makes me nervous.

I also believe it would be very nice if you could warn people that multi-projects / collections will cease to work without paying **BEFORE** the update.

**Comment by subnetmarco** [comment]
> Configs in base environment is not getting exported, at least not for me.

We will check this, everything should be exported, if that's not the case this is a bug.

**Comment by nickhobbs94** [comment]
+1 anybody got a fork of Insomnia or another project that's wholly offline?

**Comment by ewertonls** [comment]
> +1 anybody got a fork of Insomnia or another project that's wholly offline?

You can use the 2023.5.8 version,  it'll work fine.
There's hoppscotch, the desktop app is under development so there's only the web version for now. But it won't force an online account and you can selfhost the app as well, so you can keep stuff private.

**Comment by bukajsytlos** [comment]
2023.4.0 for me since this "unacceptable" change https://github.com/Kong/insomnia/issues/6301 still not being fixed

**Comment by engmackenzie** [comment]
I also lost all my data after the update. I tried downgrading back to 2023.5.8 that didn't restore the data.

**Comment by engmackenzie** [comment]
> I also lost all my data after the update. I tried downgrading back to 2023.5.8 that didn't restore the data.

The only collection I have is an empty Scratch Pad collection.

**Comment by mcheale-parkit** [comment]
> I believe "not synced" should be an easy option. End-to-end encryption is good to have, but I still don't want to send my (and my client's) dev server address and all private endpoints to anywhere in any form.
> 
> There's no such option in 8.x starting screen, so it looks like I could not get un-synced without being synced in the first place. This makes me nervous.

All this ☝️

**Comment by roberto-filho** [comment]
Also lost all my data... the new version somehow overwrote the files from the previous version. Exact same issue as @userBarbosa

Only way I could recover it was restoring a month old backup from an older version from the `backups/2023.4.0` folder.
Took me a while to figure all of it out... but finally got an acceptable solution.

Insomnia is really not the fast and simple-to-use API client anymore.
And if you want to continue to use the offline scratch pad (which I think is a pretty cool name), you have to endure this annoying bright banner saying "to get the most out of Insomnia bla bla".

And to be very honest... I don't get the competitive advantage over Postman is

**Comment by nemanjaglumac** [comment]
Homebrew still has the old version. Get it while it's still there.

```
❯ brew info insomnia
==> insomnia: 2023.5.8 (auto_updates)
https://insomnia.rest/
/opt/homebrew/Caskroom/insomnia/2023.5.8 (122B)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/i/insomnia.rb
==> Name
Insomnia
==> Description
HTTP and GraphQL Client
==> Artifacts
Insomnia.app (App)
==> Analytics
install: 3,862 (30 days), 8,995 (90 days), 16,518 (365 days)
```

This did it for me (the old data is still intact):
```sh
brew uninstall insomnia --cask
brew install insomnia --cask
```

**Comment by sergioisidoro** [comment]
I was also affected by this. Downgrading to 2023.5.8 did help, and I don't think I'll ever be updating (already disabled auto updates)

I am (was?) using insomnia because I absolutely hated Postman for pushing me to create accounts and sync stuff with their cloud. If Insomnia is going in that direction, I will very likely try to find an alternative. The point of competition is not doing everything your competitors are doing - it should be precisely the opposite. You should ask why are people sticking around you and not your competitors before making these updates.

**Comment by VasylMedvid77** [comment]
The same here.
Downgrading helped to restore access to my collection. Disabled autoupdate so will live until found alternative.
But my heart is broken - I loved Insomnia so much for many years and tell other people about it as awesome alternative to greedy and bloated Postman.

@subnetmarco `"It was said that you would destroy the Sith, not join them!"`

**Comment by antm** [comment]
I just lost an hour of work dealing with this upgrade. **I don't want to sync my data to the cloud.**  And I definitely don't want to import, export, memorize which wrk_* file goes with which project, etc.

**Comment by geoff-parsons** [comment]
I had previously downgraded to version 7 to get around this and unchecked "Automatically download and install updates" but it appears to have re-downloaded 8 and installed it anyway. Is there a way to block Insomnia from updating or is this going to be a weekly occurrence?

**Comment by geoff-parsons** [comment]
> I am (was?) using insomnia because I absolutely hated Postman for pushing me to create accounts and sync stuff with their cloud.

@sergioisidoro This is **exactly** why I had moved to Insomnia. Looks like the pointy hairs always come up with this boneheaded idea eventually to ruin their product.

**Comment by arantesxyz** [comment]
Same problem here, I had thousands of endpoints, the whole workspace used for testing and integration on my company and now everything is gone.

Insomnia was great, why force people to create an account? Oh yeah, we all know, to collect data.

**Comment by sijoonlee** [comment]
very disappointed, it seems this is intended

**Comment by wolflu05** [comment]
Is there any official statement about this disappointing move from Kong for a lot of their users? I switched to insomnia too just a few days ago and lost everything from postman, so I quickly build every request I needed from scratch in insomnia, spend a lot of time and now the auto updater does its job and everything is gone. I hope we'll find an alternative so we can remove both account forcing programs as soon as possible from our computers.

**Comment by psaxde** [comment]
this also gets a huge thumbs down from me, switching to something else now 🔨

**Comment by mkimont** [comment]
Yes yes, leave the post how angry and upset you are.
Nobody cares.
Also nobody cares that you have to been force to send all your data to Insomnia, often sensitive data, just to try-and-fail-restore attempt.
And yeah try to find disallow upgrade which is not there too.
Bravo for you devs. 
Few would say: I'm gone, but you are no so important for us. Do  you ? If yes, show me.

Same issue here, no data, I won't try to restore it by sending it to Insomnia cloud - are you insane ?

This artisan dev who advice me to use it deserve to ....

**Comment by jwalinrami** [comment]
> exportable

Thank you !! I was able to export and reimport the same json file and now I have all my queries and am able to run it, witout Loggin in on new version.

**Comment by K3vChan** [comment]
Reverted, stopped updates, and forked this repo. For those who need the downgrade link - https://github.com/Kong/insomnia/releases/tag/core%402023.5.8

Most of us if not all of us are devs. Why do we need to sync our sensitive requests to the cloud? Literally an example of postman, smartbeart, etc who try to capitalize on something so simple as making a ui for a http request guys - I literally use curl everyday as an alternative. If we want api design there is the openAPI tools for that. 

Lastly, if the company did want to capitalize on this I would make it as unobtrusive as possible with some thing like plugins, vs code copilot comes to mind as something that I actually paid for. Nuking your entire app with a login and wiping all requests is not a great way to greet your daily users. This issue right here is not a great start to my morning.

**Comment by cameronorr** [comment]
I was furious about this as well until one of my coworkers pointed out that the queries are still there, but they're just held under this "New Document" page... Horrible naming convention in my opinion - has nothing to do with the list of queries, but this was a lifesaver.
Hope this helps 😄 

<img width="1440" alt="Screenshot 2023-10-02 at 3 47 00 PM" src="https://github.com/Kong/insomnia/assets/50644803/39ce0342-4f68-43fa-a8ca-53e01a86e6f5">
<img width="299" alt="Screenshot 2023-10-02 at 3 47 50 PM" src="https://github.com/Kong/insomnia/assets/50644803/b970d577-26ab-4b39-898e-bcbc00cd3865">

**Comment by Synatiic** [comment]
Unfortunately, they are following the greed for money like Microsoft, Unity or Postman.

Shame to see another beautiful open source project fall to capitalism. Cloud functions or not, as long as you don't have to use them. Neutering the local non-cloud version to the point that it is no longer usable. Sad. Coercion does not lead to acceptance, rather the opposite. 

There are too many good alternatives that I won't go along with this. Thank you for the good project so far. 💜

**Comment by parm-p** [comment]
harass your users and kill any chance to make them buy your product. Congrats.

**Comment by fractalf** [comment]
This is just so bad... and the rollout is really bad, I mean "deleting/hiding" all the stuff from the prev version? Come on... Also the dark mode is bad..
![image](https://github.com/Kong/insomnia/assets/5707457/499f29a5-9d3c-43c4-817c-fc8cff5769d6)
..and everything else mentioned in this thread...

Jumping ship, time to look for another client. .. I thought it was already way to bloated..

**Comment by jhalterman** [comment]
Just opened Insomnia for the first time in a while - it auto updated and deleted all my requests. After creating a cloud account, the data is still gone. The export method described above doesn't recover them, the backup folder has a bunch of zero byte files, and downgrading doesn't recover them either.

**Comment by fractalf** [comment]
For those looking for an alternative, this was posted on hackernews

https://github.com/usebruno/bruno

Perfect, lightweight, simple, no crap

https://news.ycombinator.com/item?id=37680126#37688239

**Comment by subnetmarco** [comment]
There is no actionable item on this issue, so I am recapping below the options available at this time. For specific issues with more details on how to reproduce the problem, of course GH issues can always be opened with more detail. For the specific issue opened by @GeeDat I am offering a Zoom session with one of our engineers to solve the problem.

Here's the recap:

1. For users that want their data stored locally, we recognized this being a mistake and this capability is coming back in 8.3 within 10 days, hopefully next week (more here: https://github.com/Kong/insomnia/discussions/6626). You will be then able to have local projects that are never synced in the cloud to avoid breaking any compliance requirement in your organization.
2. For users that don't mind using the E2EE cloud sync but still have problems with the migration (@GeeDat _may_ fall into this category), please send an email to `support@insomnia.rest` and we will hop on a Zoom call with you to understand what is the problem. We have done this already with 10s of similar situations, and we were able to recover the data locally in 100% of the cases, and complete the migration.
3. For users that don't want to create an account but have one collection, you can: export your data using one of the many "Export data" buttons in the application. Re-import one collection into Scratch Pad (which is usable locally and with no account). Here's a video: https://www.loom.com/share/de7af6f9e06b4452a799a033604f9270
4. For users that have more than one collection, don't want to use Scratch Pad, and don't want to create an account, you can downgrade to a previous version of Insomnia and run perpetually there. Here are the releases: https://github.com/Kong/insomnia/releases
5. For users that want the latest and greatest, but don't want an account, I am afraid that is creates a situation where it prevents Insomnia from being sustainable (as discussed in https://github.com/Kong/insomnia/discussions/6626) because it prevents us to cover the costs. We are running Insomnia at a loss (and have been since forever), and this is not sustainable in the long term.

We just [shipped v8.2](https://insomnia.rest/changelog#8.2.0) that improves certain flows and makes the Scratch Pad banner dismissible, this version also fixes the dark blue color that is very hard to read. In a few days with v8.3 local storage for projects is coming again (free, 100% local, for all file types), and then you will be able to choose if you want to use Insomnia with Local Vault storage or with Cloud Sync on a per-project basis.

**Comment by jhalterman** [comment]
@subnetmarco Can you share steps to restore data that disappeared as part of this update, or is it indeed gone?

**Comment by subnetmarco** [comment]
@jhalterman If you go to Scratch Pad and click on "Export Data", do you see data in the exported folder?

**Comment by Topinaqui** [comment]
https://www.usebruno.com/

**Comment by elovin** [comment]
FYI for all who just want a 100% local version.

There is an active for of insomnia:
https://github.com/ArchGPT/insomnium

**Comment by nathan-mill** [comment]
How "completed" can this really be if all my data disappeared today?

**Comment by subnetmarco** [comment]
@FixerLT Stop spamming the board.

**Comment by subnetmarco** [comment]
As an update to https://github.com/Kong/insomnia/issues/6585#issuecomment-1747469510, Insomnia 8.3 has already been released last week and it is available today, bringing back support for local projects. We called this capability "Local Vault" and it's free to use.

With Insomnia 8.3+ and above, you will be able to choose where to store your projects (and all their collections, design specs and files) among:

* **Local**: for local storage, never synched to the cloud.
* **Cloud**: for cloud collaboration, end to end encrypted and stored into the cloud.
* **Git**: for choosing a 3rd party Git repository, never synched to the cloud.

<img width="363" alt="275704676-4f31c57a-71b4-4289-a7f8-363bbfaf33a6" src="https://github.com/Kong/insomnia/assets/964813/74c1efbd-f6cc-489a-a212-a3cbb2a2e6f3">

If you continue using Insomnia, you continue supporting the project and allow us to sustainably invest in it in the years to come. Unfortunately, unsustainable projects don't have a future, and that's **not** what we want for Insomnia.

As a result of these changes we were able to bring Insomnia back on track already in just 2-3 weeks, and I will be doubling the Insomnia team in the next 12 months to cater to all other issues and feature requests that we were not able to address in the past, like pre-request scripting, multi-tab views, and more.

Among the improvements, we will also be decoupling authentications, environments and tests in their own resources so that they can be re-used across collections and tests. And also add the ability to implement API mocking, which will ship before the end of the year:

<img width="339" alt="Screenshot 2023-10-23 at 9 41 17 AM" src="https://github.com/Kong/insomnia/assets/964813/cafe4aa8-9d8c-4725-8bc0-eb4e6096f8ba">

Stay tuned, and I apologize for the disruption. For legitimate feedback (like accessibility of Insomnia in air-gapped environments) please feel free to continue the discussion and open relevant issues because I am very much intended to implement a way to resolve those issues, in line with the long-term direction of the product.
