### ISSUE TITLE
Version 8 is just a trash

### ISSUE THREAD

**Issue by bog-h** [getinsomnia/insomnia#6594]
### Expected Behavior

I don't want to log in but the new version is forcing me to do so, even so I can't.

- My project is lost and there is nothing in "Scratch pad", just empty
- OK u win, I logged in via GitHub and the software doesn't react anyhow, so I cannot really login
-  Downloaded previous version, no option to not update, it updates itself automatically

RIP insomnia u was a good software.

### Actual Behavior

trash

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

trash

### Insomnia Version

8.0.0 trash

### What operating system are you using?

macOS

### Operating System Version

Sonoma

### Installation method

trash

**Comment by subnetmarco** [comment]
> and the software doesn't react anyhow, so I cannot really login

What's happening exactly? Are you redirected to the website, but then never redirected back to the application? Or the application is frozen?

**Comment by somegenericdev** [comment]
What's funny to me is that their code is MIT licensed. It's a matter of days at most until someone forks Insomnia and they lose all the userbase they built over the years.
You can find the company's CTO damage controlling in every forum discussion about this bullshit over the internet. He probably realizes he fucked up beyond repair and there is no way back.

**Comment by Wesley-Viana91** [comment]
I'm guiding my colleagues to downgrade to [this version](https://github.com/Kong/insomnia/releases/download/core%402023.5.8/Insomnia.Core-2023.5.8.dmg) (this is the mac version, others are also available in github releases)
And disable auto update from settings.

By downgrading you'll recover all your requests.

![image](https://github.com/Kong/insomnia/assets/93197986/7847a24f-c6b9-4158-bbd5-3ea24f755a96)

It's really bad user experience to loose all your saved requests if you're not into logging in and syncing with cloud.
The entire company dropped using Postman in favor of Insomnia because it's against company to sync data with third cloud.

**Comment by BonesyWonesy** [comment]
Wow yea. I downgraded and won't be upgrading. What a terrible choice.

**Comment by vic-bukhantsov** [comment]
@somegenericdev, thanks for the idea: having a private repo snapshot before 8.0.0 now is essential

**Comment by SergioSuarezGil** [comment]
+1 

bad update, i will downgrade the app

cant login in the app using my last password with sso... but i can login in the website using my google account
incredible

**Comment by jjdanek** [comment]
I moved from Postman to Insomnia solely because Postman started prompting me to sign in and sync everything. I do not want to. It then presented a persistent banner indicated that I wasn't signed in. Couldn't hide that banner or tell it to never ask me to sign in.

Now Insomnia is doing the exact same thing. So... where to go next? Does anyone have a good macOS HTTP API client that won't bother me with such unnecessary nonsense?

**Comment by yuliangjin1985** [comment]
We better just back up the collections regularly ourselves.

**Comment by xarses** [comment]
RIP Insomnia, I was recommending you. Now pushing an update that drastically reworks how everyone interacts with your software is an excellent way to piss off your users. 10x for not even bothering to give us a heads up or pushing a final version to the old UI to turn off automated updates.

You clearly want users, but apparently you didn't lean anything from the recent Unity revolt

**Comment by subnetmarco** [comment]
Here is a video that shows how to use Scratch Pad locally with Insomnia: https://www.loom.com/share/de7af6f9e06b4452a799a033604f9270?sid=df0baa8f-8916-4560-a8aa-6fe9ba21b0ec

**Comment by EdoardoLopez** [comment]
@subnetmarco allow restore password, what happen if I forgot my last password?, the verification code at login is ok, but allow recover password to be able to use the application please.

**Comment by petterroea** [comment]
https://en.wikipedia.org/wiki/Enshittification

**Comment by subnetmarco** [comment]
@EdoardoLopez Your passphrase is the old password of your account, which is being used for E2EE. If you lost your passphrase, the only solution is to create a new account (ideally with an email alias) like "email+insomnia@yourdomain.com".

**Comment by EdoardoLopez** [comment]
wow that is very sad, then i can't use the application anymore :c

**Comment by heygambo** [comment]
> wow that is very sad, then i can't use the application anymore :c

you can still use the previous version:
https://github.com/Kong/insomnia/releases/tag/core%402023.5.8

**Comment by heygambo** [comment]
> wow that is very sad, then i can't use the application anymore :c

@EdoardoLopez you can still use the previous version:
https://github.com/Kong/insomnia/releases/tag/core%402023.5.8
