### ISSUE TITLE
Lost all my stuff after the upgrade to 8.0.0

### ISSUE THREAD

**Issue by pbalduino** [getinsomnia/insomnia#6606]
### Expected Behavior

I used to have a well organized set of requests for different APIs and environments and it's all gone after the 8.0.0 updating.

### Actual Behavior

All my set of requests were lost.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.0.0

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.6

### Installation method

Download from site

### Last Known Working Insomnia version

2023.5.8

**Comment by kbariotis** [comment]
lost all of my stuff after asking me to register. insanely bad user experience.

**Comment by kbariotis** [comment]
straight to trash

**Comment by jonathanray** [comment]
I downloaded and ran the previous version 2023.5.8 and still have all data (collections, environments, etc). I exported the data into JSON file, then imported the JSON file into in Sandbox in 8.1.0. The import appeared to be successful, but no collections or environments were populated in the UI.

**Comment by NaderDroid** [comment]
Same here, I love Insomnia but i am lost now, ugliest CX ever, any mitigation please?

**Comment by lila1-work** [comment]
It would have been nice to inform us what would happen on the upgrade - this completely blindsided me.  I had just spent an age moving over from Postman because I'm not allow to use Cloud accounts, so not seeing my requests made me panic a bit!
I've done an export and now found the import tool, and most of my requests are now back.  It was not an obvious process, my base environment is gone and so are some of my header values.

**Comment by MatheusR42** [comment]
Same here! Very bad experience

**Comment by Vanderhoof** [comment]
It only shows your stuff if you switch on sync, thus forcing you to create an account. That's awful, why would you do that?

**Comment by ppamorim** [comment]
I am reverting this update, it's terrible.

**Comment by jogat** [comment]
'It's Not a Bug, It's a Feature.'

**Comment by margolisj** [comment]
Really poorly done rollout. Guess it is time to move on.

**Comment by GitLukeW** [comment]
I ran into the same issue here. I'm also in an endless login loop. It takes me to the web to login, I login and the desktop app says I need to login. Whats the best option for rolling back to the previous version?

**Comment by andrzey** [comment]
I lost all of my work after upgrading to version 8. Guess I'll find something else to use.

**Comment by atetz** [comment]
Is there a way to get all collections back without making an account? The import feature imports all requests from a single collection into a 'scratchpad' collection.

**Comment by patjakubik** [comment]
Simply download the old version (https://github.com/Kong/insomnia/releases/download/core%402023.4.0/Insomnia.Core-2023.4.0.dmg), drag it to the Applications folder and replace it. Once you open it you will see all your requests. Also, make sure to disable auto-update in settings.

I'm personally switching to RapidAPI though.

**Comment by shahabhm** [comment]
at the "Welcome to Insomnia" page, select the 'Export data and more' option. then click Export all data and select a path for the extraction. after that, click on 'Use the local Scratch Pad'. click on 'Scratch Pad' drop-down menu on the top left of the application and select 'Import'. drag and drop the extracted Json file into the opened window and you should have the app working with your old data, without downgrading or creating an account.

**Comment by Vanderhoof** [comment]
@shahabhm thanks for the instruction. Now for the insomnia devs, how the process should look like:
Step 1: you click "No, I want to use Insomnia locally"
Step 2: there's no step 2, you shouldn't need to export or import any of the data which you already have stored

**Comment by atetz** [comment]
@shahabhm I know that you can import your collections into the scratchpad. But this functionality merges all request of a exported collection into the scratchpad collection. 

When I press export in the new version, Insomnia creates multiple files (per collection). 

I have a collection per personal project so that my requests of that project are categorised. In Insomnia terms I have 1 project and 12 collections in that project. In the previous version I could easily switch contexts per collection. I don't want a 'super' collection called scratchpad where I dump all my requests in. When I export my project in the older version and want to import it in the new version I read that a collection is seen as a 'workspace'. Nothing visually happens on the import of my project export file. Only on the singular files of the collection. But again, this is not what I want. 

When I downgrade Insomnia I can see that the import function has indeed made a copy of my project with all collections (or workspaces?) including a Scratchpad collection. 

Am I missing something here? 
edit: added some clarification

**Comment by ozio** [comment]
"Не было печали, апдейтов накачали"

**Comment by jonian** [comment]
There is a fork without the account/tracking features https://github.com/ArchGPT/insomnium.
Also an AUR package https://aur.archlinux.org/packages/insomnium-bin.

Copy your `Insomnia` config folder to `Insomnium` and you will get back your data. 
Worked well for me.

**Comment by matijse** [comment]
Since you cannot use multiple collections without an account, I decided to revert to the previous version. 

For Linux users using snap:

1. Download `Insomnia.Core-2023.5.8.snap` from the releases page
2. `snap install path/to/Insomnia.Core-2023.5.8.snap` reverts to the old version
3. `snap refresh --hold=forever insomnia` prevents it from auto updating

All data was still there.

**Comment by mrgadotti** [comment]
It is time to move on. It's a shame do this with this awesome application.

**Comment by MarkOSullivan94** [comment]
> Simply download the old version (https://github.com/Kong/insomnia/releases/download/core%402023.4.0/Insomnia.Core-2023.4.0.dmg), drag it to the Applications folder and replace it. Once you open it you will see all your requests. Also, make sure to disable auto-update in settings.
> 
> I'm personally switching to RapidAPI though.

Cannot thank you enough for this link, urgently needed a version which had my old requests and panicked when I realized everything was gone in the new version

**Comment by arcreative** [comment]
> Simply download the old version (https://github.com/Kong/insomnia/releases/download/core%402023.4.0/Insomnia.Core-2023.4.0.dmg), drag it to the Applications folder and replace it. Once you open it you will see all your requests. Also, make sure to disable auto-update in settings.
> 
> I'm personally switching to RapidAPI though.

This didn't work for me, now I have yet another UI I don't recognize with two projects with no requests in them. Holy shit this just ruined my day and coming weeks.

**Comment by as4** [comment]
I've just downloaded Insomnia Code 2023.5.8 dmg and replaced the app. Now I see all my stuff again. Also disabled automatic updates.

**Comment by rganczarek** [comment]
Happened to me too :angry:

**Comment by sw360cab** [comment]
Just to express my disappointement for the method used not for the `business` decision itself.

**Comment by kirvis250** [comment]
Same. Not using insomnia ever again.

**Comment by designbyadrian** [comment]
I had to migrate my data and successfully did so. When loggin in on another machine, using the same credentials, my projects are there, but no collections or environments. What's the point of loggin in if my data isn't synced?

**Comment by subnetmarco** [comment]
@designbyadrian how can we follow up with you on this issue? Can you send an email to `support@insomnia.rest` ?

**Comment by tobias-kuendig** [comment]
[Bruno](https://www.usebruno.com/) is a great alternative. It even imports your Insomnia collections.

**Comment by designbyadrian** [comment]
> @designbyadrian how can we follow up with you on this issue? Can you send an email to `support@insomnia.rest` ?

I'm sorry, I uninstalled Insomnia and not interested in dealing with it anymore. Have deleted my account and hope you're still not storing anything of mine.

**Comment by digitalroll** [comment]
Here's what you need to do:

1. Create an account using your email address.
2. Start synchronizing your local storage with the online storage by clicking the button at the bottom of the window.
3. Everything is ready! 

Unfortunately, none of this is obvious.

**Comment by henadzit** [comment]
Deleting the application, this is ridiculous.

**Comment by akinjide** [comment]
I do not understand why I have to create an account before using the free version. At least, give 7 days notice before enforcing account creation.. Moreover, I cannot access my collections even in scratchpad and exported JSON collection is a mess.

**Comment by akinjide** [comment]
I do not understand why I have to create an account before using the free version. At least, give 7 days notice before enforcing account creation. Moreover, I cannot access my collections in scratchpad and exported JSON collection is a mess.

**Comment by binarygiant** [comment]
Going back to Postman or the HTTP request tool in VSCode - the whole point using Insomnia for me was that it was clean and easy, unlike Postman.  With 8.0, I lost a lot of carefully cultivated collections and environment settings.  I'm not even going to try to restore it with all the ridiculous workarounds.

Having said that, I understand the desire to expand, make profit, monetize, so kudos to Kong for trying, but also wow, what a terribly executed rollout - I'm guessing for every individual post here, there are 10 or more other users who are abandoning the tool. It would have been really desirable to have the option to keep the "classic" interface for free or a nominal fee, even with an account.

**Comment by nits1991** [comment]
Same issue. I was using Insomnia for quite some time now but this was really bad. Need to switch to something else.

**Comment by Waschnick** [comment]
This sucks so much. I love Insomnia, but now I'm never touching this garbage again. It's like the same story with Unity - are companies becoming more stupid and only think about short term profit and not about a sustainable product? It's the same for two of my colleagues, one used Insomnia for many projects. How can you rollout such a shitty update? I could live with being force to have an account, but this is total bullshit. Ridiculous.

**Comment by suchislife801** [comment]
## Last Working Version! Sort Order Fix!
# [2023.4.0](https://github.com/Kong/insomnia/releases/tag/core@2023.4.0)
### ANY version ABOVE 2023.4.0 will absolutely WRECK your sort orders.

**Comment by suchislife801** [comment]
## Last Working Version! Sort Order Fix!
### Also, everything that used to work, works on this version.
# [2023.4.0](https://github.com/Kong/insomnia/releases/tag/core@2023.4.0)
### ANY version ABOVE 2023.4.0 will absolutely WRECK your sort orders.

**Comment by suchislife801** [comment]
# Yeah, OR...
## Last Working Version! Sort Order Fix!
### Also, everything that used to work, works on this version.
# [2023.4.0](https://github.com/Kong/insomnia/releases/tag/core@2023.4.0)
### ANY version ABOVE 2023.4.0 will absolutely WRECK your sort orders.

**Comment by mateosantosdev** [comment]
This is one of the best example about "How to get a massive user exodus". 

The recent Unity movement was difficult to overcome, but hey Insomnia team, you are doing great!

**Comment by adamismeta** [comment]
Just ran into this same issue. Downgrading to previous versions did not work for me, but here's what did:

- On the "Welcome to Insomnia" welcome/login screen click on "Export data and more" in the bottom right corner. This should include all of your old workspace data.
- Once that is downloaded, sign into insomnia and then click the Import button/tile. Import your previously downloaded data and you should hopefully be good to go.

**Comment by kamildzi** [comment]
> There is a fork without the account/tracking features https://github.com/ArchGPT/insomnium. Also an AUR package https://aur.archlinux.org/packages/insomnium-bin.
> 
> Copy your `Insomnia` config folder to `Insomnium` and you will get back your data. Worked well for me.

Thanks! Insomnium looks promising. And they say it's going to be a long term project. 

If anyone's wondering how to copy the config folder (on Linux) here are the commands that you need: 
```bash
cd ~/.config/
cp -arp Insomnia Insomnium
```
... and voila - all done. Your data is back. :)

**Comment by coderanger** [comment]
+1 for this being entirely unacceptable. Kong should be ashamed of how far they have fallen.

**Comment by AlbertGromek** [comment]
trash, going back to postman

**Comment by alexeydubinin** [comment]
Switching to Insomnium

**Comment by misakoooo** [comment]
`[Apidog ](https://apidog.com/download/)`is a new but powerful alternative, I have switched to it.

**Comment by unitedworx** [comment]
I have lost all my stuff as well :( I have tried using an older version as above without any success. I ideas how I can get everything back?

**Comment by kevin-lee** [comment]
> patryk-smc

@patryk-smc Because of this data loss issue, I'm also considering switching to RapidAPI.
Do you know if there's a way to import Insomnia data to RapidAPI? I saw it supports Postman data import but couldn't find Insomnia data support.

**Comment by kevin-lee** [comment]
> Simply download the old version (https://github.com/Kong/insomnia/releases/download/core%402023.4.0/Insomnia.Core-2023.4.0.dmg), drag it to the Applications folder and replace it. Once you open it you will see all your requests. Also, make sure to disable auto-update in settings.
> 
> I'm personally switching to RapidAPI though.

@patryk-smc Because of this data loss issue, I'm also considering switching to RapidAPI.
Do you know if there's a way to import Insomnia data to RapidAPI? I saw it supports Postman data import but couldn't find Insomnia data support.

**Comment by LucaRed** [comment]
Switched to [ArchGPT/insomnium](https://github.com/ArchGPT/insomnium), I confirm it solves everything.

No cloud sync and no online features are a big plus.

**Comment by subnetmarco** [comment]
We have an update with Insomnia 8.3, where you can now store things **100% locally** again with Local Vault, in addition to Cloud Sync and Git Sync.

More information at https://github.com/Kong/insomnia/discussions/6626#discussioncomment-7299800

Also, please stop spamming this board. Thanks.

**Comment by peauc** [comment]
Deleting users comment is not a good look after such a release...

**Comment by subnetmarco** [comment]
@peauc spam is not tolerated, and will be dealt as such. If you want to open a comment in the merits of the project, no problem with that.

**Comment by roberto-red** [comment]
I've just checked your [Code of Conduct](https://github.com/Kong/insomnia/blob/3a8561f8d1b5a7ba24fa03a56b4d7972c327bd5e/CODE_OF_CONDUCT.md) and it doesn't mention anything like "always comment in the merits of the project," and nothing about not talking or linking to alternative solutions (what I interpret you're declaring "[spam](https://en.wikipedia.org/wiki/Spamming)" here). It does say, though:

> - **Be respectful.** Not all of us will agree all the time, but disagreement is no excuse for poor behavior and poor manners. We might all experience some frustration now and then, but we cannot allow that frustration to turn into a personal attack. It's important to remember that a community where people feel uncomfortable or threatened is not a productive one. Members of the Insomnia community should be respectful when dealing with other members as well as with people outside the Insomnia community.
> - **Be careful in the words that you choose.** We are a community of professionals, and we conduct ourselves professionally. Be kind to others. Do not insult or put down other participants. Harassment and other exclusionary behavior isn't acceptable.

While I do get that this situation was unfortunate and understand the reasons behind (good job at explaining them, thank you), the work of some people was affected for three Insomnia releases, and that's surely some frustration. Your solution is good and has merit, but they have their own interest and opinions on the project forward.

IMHO limiting the expression of users in such a way make it appear like you don't learn from mistakes or from the pros of other similar projects (which I don't think is the case here, by the way). I think that's what @peauc wanted to point.

Hope this is not considered spam, though. I won't intervene further to not cause more noise. Keep up the good work.

**Comment by mathieu-lemay** [comment]
> We have an update with Insomnia 8.3, where you can now store things **100% locally** again with Local Vault, in addition to Cloud Sync and Git Sync.

It's still super limited, only one collection, no migration of previous data and I can't import the the data I exported from previous versions.

**Comment by subnetmarco** [comment]
@mathieu-lemay Scratch Pad is only one collection (always local). Free subscriptions (and above) can store locally on more than one subscription.

**Comment by kevin-lee** [comment]
@subnetmarco It may not be so bad that people talk about issues and vent their frustrations here. What's much worse is that people get angry as their comments have been deleted, so they go elsewhere to spread their complaints more.

I've recently tried multiple other tools because of this issue, but Insomnia is still a better choice. So, I think deleting those comments was unnecessary and may have a negative impact.

**Comment by subnetmarco** [comment]
@roberto-red Spam is [disallowed by GitHub](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies#4-spam-and-inauthentic-activity-on-github), which is the product where this conversation is happening. You probably already know that spamming is not decent behavior in general.

I will be happy to engage in polite conversation, I am very communicative in general, and you and everyone else can feel free to post legitimate complaints/feedback/suggestions on any topic. I am sure you will notice that we have done a good job at that, you are absolutely welcome to express your views.

But spam is not accepted, simple as that.

**Comment by subnetmarco** [comment]
@kevin-lee It's great that you feel this way, but I wouldn't condone spamming a project even if that benefitted Insomnia. That's not the point. You won't see me or my team going around and spamming other projects, either.

I want to run a good open source repository: building features, addressing legitimate concerns and feedback for as much as possible and I don't want to engage with spammy content on this repository. I also don't want to silently condone it, and further encourage it. That it even violates the terms of service is also besides the point.

Let's get back to work, and focus on constructive conversations.

**Comment by kevin-lee** [comment]
@subnetmarco I don't know what those comments were, as they were deleted. Although I mentioned another tool, you didn't delete my comment, so I guess those comments weren't just talking about other tools. Since I don't know what the deleted comments were saying, I should not say anything further and hope you made the right decision for the community.

By the way, thanks for your work on Insomnia.

**Comment by nodakjones** [comment]
@subnetmarco 

> We have an update with Insomnia 8.3, where you can now store things **100% locally** again with Local Vault, in addition to Cloud Sync and Git Sync.
> 
> More information at [#6626 (comment)](https://github.com/Kong/insomnia/discussions/6626#discussioncomment-7299800)
> 
> Also, please stop spamming this board. Thanks.

I appreciate this update, but it has been a very frustrating delay to have lost my collections.  I'm sure you can appreciate the frustration and I'm not sure it is spam to be expressing this concern.  At a minimum shouldn't this update auto-import existing data to the local scratch pad?

**Comment by LucaRed** [comment]
I'm the one whose comments have been deleted and I don't agree my comment was spam.

For anybody interested, I just mentioned that using a fork of this package (that has more than 1400 stars on GitHub) solved the problem of not having local collections anymore.

Isn't forking one of the pillars of GitHub and open-source in general?

**Comment by designbyadrian** [comment]
The fork was called "Insomnium", by the way. It's just like when Insomnia was good, fully offline, and supports more than one collection.

**Comment by AlexDev404** [comment]
@subnetmarco
Please, can you add a feature to use the software without signing in. It is not fair for you to bar users from using your software just in order to create an account. It is not fair for you to not announce that we are now forced to create an account on your servers just in order for us to access our data. It's not fair for you to control our freedom of speech by completely ignoring and deleting our comments, even if it may be filled with angry words, begging and crying to you to allow us to get back our data (#6594). It's [not fair](https://github.com/Kong/insomnia/issues/6594#issuecomment-1745550248) for you to put us through all this confusion and trouble just trying to figure out how to get back our data, and [revert](https://github.com/Kong/insomnia/issues/6594#issuecomment-1739882016) the trouble you have caused all of us in the process. 

Because, what you have done is inconsiderate, because, by doing what you have done, you've affected all of us in the process. You've split the user community in two, 

_"Starting in 8.0.0, users will be locked out of all of their collections / requests unless they make an account (and enter payment information even if they are already part of a team). No warning is provided to the user and although they provide the option to export your content in 8.1.0's onboarding, users have been reporting content getting lost in export. ( https://github.com/flathub/rest.insomnia.Insomnia/issues/65 )"_

as now, users (probably, even me, myself) are now moving ( https://github.com/Kong/insomnia/issues/6594#issuecomment-1739687214 ) onto [the fork](https://github.com/Kong/insomnia/discussions/6626#discussioncomment-7184511) of your project, [Insomium](https://github.com/ArchGPT/insomnium), or discussing [alternatives](https://news.ycombinator.com/item?id=37708582), or even [freezing](https://github.com/flathub/rest.insomnia.Insomnia/issues/65) the version, as you have not listened to us or any of our pleading, just asking you to allow us back in to just allow us to continue using your software as we used to, as many of us depend on it. [You've made](https://github.com/Kong/insomnia/issues/6594#issuecomment-1740077830) us [all upset](https://github.com/Kong/insomnia/issues/5167#issue-1369114482).

![image](https://github.com/Kong/insomnia/assets/34188635/633e13bd-cc6f-4974-8dee-f6e6b41d5924)
![image](https://github.com/Kong/insomnia/assets/34188635/2387ab42-7c65-43d1-9f82-d00eb2c6ab52)
![image](https://github.com/Kong/insomnia/assets/34188635/d2270316-7c3f-4dab-a6d3-a8fd93da904c)


Users should have freedom of choice in doing so, especially people like us who have continually used your software for so long. And, even so, users who want to sign up, [cannot, because they're not allowed to do so](https://github.com/Kong/insomnia/issues/6624), and you've failed to [address even that](https://github.com/Kong/insomnia/issues/6624#issuecomment-1761415412) properly.

![image](https://github.com/Kong/insomnia/assets/34188635/b812febd-f5de-4732-9712-f0349467e682)


I'm not at all surprised, though. As, from early as the recent 2023 updates in January, you were pushing the Insomnia accounts. But, even though you don't have many users. This is not the way. Forcing people to do something they don't want to do is not attractive, not nice, not fair and not justifiable. Forcing people is the only way out of what you're aiming for.

So, I'd suggest, before anything gets worse than it already is for you all, that you'd instead allow users to continue their experience **OFFLINE AS IT SHOULD BE**, and taking an upsell approach to what you're doing instead of what you're doing now.

Thanks.

**Comment by subnetmarco** [comment]
Locking this thread as it's going off topic, if you experience migration issues please open an issue to discuss the **specific** problem you are experiencing.
