### ISSUE TITLE
[Bug] Unable to copy urls from json response

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [getinsomnia/insomnia#662]
- Insomnia Version: v5.12.4
- Operating System: Ubuntu 17.10

## Details

Hi there!

When working with a HATEOAS services, the backend sends a lot of urls to be consumed by the requester application. Usually these URLs are then used in others APIs to do other stuffs. The easy way to do that would be to copy the returned URL returned in the response JSON, and paste that URL in the new API request.

The problem here is that Insomnia doesn't allow to copy URL in the JSON response, as you can see here:

![image](https://user-images.githubusercontent.com/12160864/34075428-e1ce82b2-e2ad-11e7-9bad-859e98fa6d9d.png)

Could this be a bug?

Best regards,
Rafael Pacheco.

Edit: I just found that the `Copy` menu only enables if the json text is selected. But since these are URLs, they are hard to select, and a direct `right click` should allow to copy the url.

**Comment by rafaelrenanpacheco** [comment]
Oh no :open_mouth:

**Comment by rafaelrenanpacheco** [comment]
Here is some activity.

**Comment by gschier** [comment]
Bump

**Comment by ian-h-chamberlain** [comment]
I know this is an old issue, but I am facing what I think is the same on macOS. Right-clicking or ctrl-clicking seems to just open the URL in the browser, instead of allowing me to copy it.

It's possibly to highlight the URL and copy it, but it's easy to accidentally select too much or too little, and I think it would be a big improvement to automatically select the contents of the string for copying in this case.

Example reproduction can be found with the GitHub API: `$.url` when `GET`ing https://api.github.com/repos/Kong/insomnia/pulls/4551

Since this has been closed, should I open a new issue to track this again?

Edit: I found some more recent discussion here: https://github.com/Kong/insomnia/discussions/3660

It seems like it doesn't _exactly_ address the issue, but is related at least.
