### ISSUE TITLE
Employer REQUIREMENT: Cloud syncs are forbidden. Insomnia just removed that ability.

### ISSUE THREAD

**Issue by ttelford** [getinsomnia/insomnia#6624]
### Expected Behavior

Expected behavior:  The previous behavior of full OFFLINE, Non-Cloud-Synced functionality with Insomnia, as before.

My employer has a *hard requirement* that NOTHING I use can sync to the cloud. Full stop. No exceptions.

- That reason is why I chose Insomnia, _and paid for it_.
    - It allowed me to continue to work and *not* sync to the cloud.
- Now that core functionality has been removed, and I can't continue to use it.
    - It's only a matter of time until corporate virus scanners flag insomnia as malware.
    - Good job, guys!

### Actual Behavior

Actual Behavior:

First:  Thank you so much for not just using my already-existing credentials and not syncing immediately. 

* You would have gotten me fired.
* I canceled everything before Insomnia started syncing, because... I like my job, and eating.

All of my previous organization, API's and projects have vanished. I can export them, but not use them.

Only a single and blank scratchpad has replaced the full organization and functionality which existed before. I paid for that specific set of features (many, and diverse projects and organization of them -- that do not sync to anything, anywhere) in the earlier releases, and now it's been removed.

Unacceptable.

### Reproduction Steps

1. Insomnia auto-upgrades
2. Watch the intro with increasing **horror**
3. Disable all network devices on the machine IMMEDIATELY
4. Breathe a sigh of relief when I see I have to login again to enable cloud sync
    * (Which is forbidden, and an audited, fireable offense)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I'm extremely disappointed. The entire reason I've been using Insomnia is because it used to allow full organization without synchronization to the cloud, which is a _hard requirement_ at my employer. This is not optional.

Version: Insomnia 8.1.0
Build date: 9/28/2023
OS: Darwin x64 22.6.0
Electron: 25.8.1
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.29-electron.0
Architecture: x64

### Insomnia Version

Insomnia 8.1.0

### What operating system are you using?

macOS

### Operating System Version

13.5.2 (22G91)

### Installation method

Download from insomnia.rest

### Last Known Working Insomnia version

Whatever it was before 8.0.

**Comment by subnetmarco** [comment]
We are introducing a "Local Vault" capability to choose where to store the projects, cloud or local-only. It will take until mid-October to properly provide this offering. Just a little bit of patience until then.

**Comment by KrayzeeKev** [comment]
@subnetmarco  Will it support multiple collections? Will you be able to use it without logging in?

**Comment by subnetmarco** [comment]
Yes multiple local collections - I will make a more formal announcement soon, to explain how it will work.

We would still require a login as we are making this part of the Individual plan but we can grandfather-in existing users.

**Comment by zyrif** [comment]
@subnetmarco I'm a long time Postman user who was looking to move to Insomnia due to their recent cloud-only workspace restriction. I also have a requirement of keeping my projects local-only. I evaluated and chose Insomnia before the v8 update. However, as I was starting the process of migrating away from Postman to Insomnia, I came across this. 

Gotta say, not really a great timing. It's great that local vault is coming, but IMO it should've been included as part of the v8 update in the first place as local-only projects is a critical requirement, at least for some of us.

**Comment by micronull** [comment]
Use fork the insomnium

**Comment by subnetmarco** [comment]
Here is the discussion: https://github.com/Kong/insomnia/discussions/6626

**Comment by KrayzeeKev** [comment]
One question on "existing users". Are you saying that new users need to pay for Local Vault? Or is the individual plan the free plan? (Mostly just reporting back to management so we have all info). 
For the purposes of this discussion, I, and all my colleagues, would NOT be classified as existing users if "having an account" is the determining factor.

That said - kudos to you guys - You've done everything with good intentions and then done something very few organisations would and pivoted to suit a broader user-base.

**Comment by subnetmarco** [comment]
@KrayzeeKev It will be free when local.

**Comment by ywidiastuti** [comment]
@subnetmarco will the free version which includes "local vault" enables the use of Design Decument and Test?

**Comment by subnetmarco** [comment]
@ywidiastuti yes

**Comment by ywidiastuti** [comment]
@subnetmarco will the free version also able to use the git sync?

**Comment by subnetmarco** [comment]
@ywidiastuti Git sync moved under the Team plan.

**Comment by Chi-Yu** [comment]
> We are introducing a "Local Vault" capability to choose where to store the projects, cloud or local-only. It will take until mid-October to properly provide this offering. Just a little bit of patience until then.

You deliberately broke existing installations by removing the ability to read locally stored data in an attempt to trap users in your cloud so you can make more profits in the long run. That's a predatory business practice and you know it.

The fact that you are now back paddling and promising to restore the functionality later doesn't serve to restore trust in your product. On the contrary. It makes your motivations as software creators very clear and proves that you and your products cannot be relied upon.

**Comment by k3mist** [comment]
this update is not cool at all.

you're forcing existing users to share private api information with no recourse? **_absolutely absurd in a corporate environment!_**

and there is no way for those users to revert back because you only provide the minimum number of available versions on snap.

time to fork i suppose as you have broken all trust with myself and my team.

**Comment by KrayzeeKev** [comment]
Every release is on github: https://github.com/Kong/insomnia/releases/tag/core%402023.5.8

And v8.3 will have the ability to work locally again, although you will have to login. Which does mean some corporate risk because you ARE logged into the cloud and could accidentally create something in there. eg we're not allowed to run DropBox, even for personal files because we MIGHT put corporate files in there. Similar argument may get you.

I agree with you about the hostile nature of these changes in the corporate environment. We're in a really tough place right now but we're just sticking with 2023.5.8 for the moment. We'll have to get an assessment from Security for the concept of 8.3.

**Comment by jamfor352** [comment]
@subnetmarco What made you think a forced auto-upgrade before the local vault was ready was acceptable to push on your users who may be using this with employers?

**Comment by filfreire** [comment]
Hey folks, closing this one. After 8.3.0 release it will be possible to have local only projects ("vaults") again for logged in users.
For more info refer to https://github.com/Kong/insomnia/discussions/6626

Feel free to report other issues, feedback and suggestions you come across.

**Comment by bademux** [comment]
looks like issue can be fixed with https://milkman.dev/

**Comment by subnetmarco** [comment]
@bademux no spam.

This issue has been resolved two weeks after this conversation started, Insomnia does not require cloud sync and data can be stored locally as it has always been. You can change how projects are being stored in their settings:

![Screenshot 2024-01-11 at 10 50 15 AM](https://github.com/Kong/insomnia/assets/964813/0a3d534c-915a-4753-b93e-d9ee04613632)
