### ISSUE TITLE
[Help] unable to import Postman dump into Insomnia

### ISSUE THREAD

**Issue by gokulraja** [getinsomnia/insomnia#663]
Unable to import the dump file generated from postman into insomnia

- Insomnia Version:  5.12.4
- Operating System: 5.5.0

Generated the dump file from
 **Postman** >> Settings >> Data >> Download
Tried importing using the insomnia import option 
**Insomnia** >> Preferences >> Data >> Import from File

received the error message "**No Importers found for file**"

Below is the gist to the json schema from the json dump generated
https://gist.github.com/gokulraja/8f5628805ff110a81b184b3acf135a29

A sample of the initial json is added as a comment to the gist

**Comment by gschier** [comment]
Ah yes, right now Insomnia only supports Postman collection v2 format. To export in this format, you must use the Export Collection menu from the collection dropdown in the sidebar.

<img width="606" alt="image" src="https://user-images.githubusercontent.com/587576/34110033-ba25fffc-e405-11e7-9f54-aec4cd086f39.png">

<img width="486" alt="image" src="https://user-images.githubusercontent.com/587576/34110026-b31aa014-e405-11e7-9249-7727018e6f11.png">

**Comment by gokulraja** [comment]
Thank You !!

**Comment by gschier** [comment]
😄

**Comment by ahoker34** [comment]
Oh Dude..Hi Five!!

**Comment by ss25sand** [comment]
Hi there! Postman is [deprecating Scratchpad soon](https://blog.postman.com/announcing-new-lightweight-postman-api-client/) which will make it impossible to [work in offline mode](https://community.postman.com/t/postman-version-10-no-more-offline-mode-renders-postman-useless-for-many-developers/48812/2). This is a great opportunity for Insomnia to capitalize on since many companies don't want to sync their private endpoints & secrets to Postman's cloud. For this reason, is there any effort to support importing the Postman collection v2.1 format soon?

**Comment by mianandong** [comment]
Hi team, for now, follow @gschier'step, still meet the same issue. Not sure if it's because the latest version of postman made some changes, after all, it's been years.

**Comment by rajapadm** [comment]
Hi team, My postman was updated and collections are lost. I am able to export data from scratchpad version. But json dump export is of collection version 1. Is there a way we can convert v1 to v2.1 or workaround to v1? 
Thanks in advance!
