### ISSUE TITLE
[Bug] Cookies not sent when setting the Host-header

### ISSUE THREAD

**Issue by wederbrand** [getinsomnia/insomnia#676]
- Insomnia Version:5.11.7
- Operating System: linux/mint(ubunut)

## Details

I have a weird behavior when working with cookies and setting the header **Host.**
I have both the host and the port as environment variables (different for local and prod)

I first do a login request getting the correct cookies stored in the jar. The cookies are stored using the actual host the request was sent to as domain.

When doing a subsequent call the cookies are not sent (seen on the timeline). 

However, if I choose to "Copy as Curl" or "Generate Code" the cookies are always added. 

It seems that Insomnia is honoring the **Host** header when getting cookies from the jar (and it shouldn't) only when doing requests inside Insomnia, and not when getting a command as "Copy as Curl"

**Comment by gschier** [comment]
The cookie selection during a request is done by `libcurl`, making it seem like the bug is actually in the Copy as Curl feature (custom code). 

To me, it makes sense that cookies are chosen using the Host header given it's importance in the HTTP specification. Do you have any evidence that it should work the other way around?

A agree that there is definitely a bug here, as both cookie selection algorithms should operate the same way.

**Comment by wederbrand** [comment]
I don't know what is "correct" but IMHO if you send one request to one host with another in the **Host**-headers subsequent calls using the same original host and same header should send the cookies the first call saved. 

So, either save them with along with the Host-header (probably wrong) or ignore the header when selecting cookies. 


Perhaps it's a back end problem?

Using standard curl it seems the cookies are for the name fround in the header

curl -L -v --header "Host: www.google.com" 'http://www.google.se/'

**Comment by gschier** [comment]
It could be a server issue if the server is explicitly setting the host field of the cookie. 

Hmm, I tried your Curl example, except with `google.hr` instead of `google.com` to prevent it from redirecting (I'm currently in Croatia), and see this error message about the `Set-Cookie` header in the response Timeline view:

```
Rejected cookie: Cookie not in this host's domain. Cookie:google.hr Request:www.google.se
```

Are you not seeing this message too?

**Comment by wederbrand** [comment]
I get no cookies rejected. If I flip it around
`curl -L -v --header "Host: www.google.hr" 'http://www.google.com/'`
I get fewer redirects but still a cookie valid for the domain I specify in the Host header. 

Perhaps this is some magic done by google. Perhaps it's even correct to send that domain.

I guess the only thing left in this "bug" is that there is two different behaviors, but it will not solve my problem of cookies not being sent when I'm adding the Host header.

**Comment by gschier** [comment]
The reason I chose the `.hr` domain is so I wouldn't get redirects. Was there a redirect in the initial request you tested with? (The one that prompted you to submit this bug)

If you could provide a public URL for me to test with that's not location-aware (so we get the same results), that would be much easier to discuss.

---

As a side note on redirects, it looks like curl forwards the `Host` header to every chain in the redirect. I'm not sure if this is correct HTTP behavior but I can definitely see it also causing problems with cookies.
