### ISSUE TITLE
[Improvement] Add request url in history preview list

### ISSUE THREAD

**Issue by andela-anandaa** [getinsomnia/insomnia#677]
In the history preview list (see screenshot below), it would be great to add the request URL (on hover, now that there's no enough real-estate).

<img width="368" alt="screen shot 2017-12-22 at 2 56 03 pm" src="https://user-images.githubusercontent.com/13568167/34297346-a8945fec-e728-11e7-88da-db9857ea5eb8.png">

I always have to click on a number of items before getting the actual request from history.

Let me know if I need to provide any more information.

-na

**Comment by gschier** [comment]
Nice suggestion. That should be fairly easy to implement. Any chance you want to submit a PR for this?

**Comment by iansu** [comment]
I've been wanting to start contributing to Insomnia so I'd be happy to do this.

**Comment by iansu** [comment]
I took a look at this and there's an issue with adding a tooltip to the row itself: when you hover over one of the tags the tooltip from the tag and from the row overlap. There also isn't a lot of empty space in the row to hover over. I can think of a couple of ways around this:

1. Add the request URL to one of the existing tooltips. For example, if you hovered over the status the tooltop could show the status message and then the request URL.
2. Add another tag for the request URL. Maybe the tag could contain the first part of the URL (eg. `/api/v1`) and hovering over that would show the full request URL.

**Comment by ProfNandaa** [comment]
@iansu:
- having the full URL will be more helpful since you might want to distinguish say requests made to `http://test.example.com/api/users/` vs. `http://example.com/api/users`, you don't want both showing as `/api/users`.
- I agree we've very little real estate, how about at this small section that starts the `DropdownItem` component? https://github.com/getinsomnia/insomnia/blob/549ce23ce8cf202d787ca4df5efc5f25e03311ed/packages/insomnia-app/app/ui/components/dropdowns/response-history-dropdown.js#L56 

![screen shot 2018-01-03 at 3 15 45 am](https://user-images.githubusercontent.com/261265/34505331-a671f3bc-f035-11e7-9ba6-df21bc9ca1ca.png)

this one that toggles between the `thumb-tack` icon and empty?

**Comment by iansu** [comment]
The pinned row is another issue because that row doesn't seem to be hoverable at all. Plus the row hover still has the problem where hovering over one of the tags displays both the row tooltip and the tag tooltip.

**Comment by gschier** [comment]
Do you think that time and size are necessary to show in that list? One solution might be to remove the time and size tag and replace them with a new "URL" tag like @iansu was suggesting.

**Comment by iansu** [comment]
That's a good point. I don't know that time and size are super useful in this context. The URL seems a lot more relevant. If we remove time and size the URL tag could show a pretty good chunk of the URL and then the rest would be available by hovering over it.

**Comment by Plasma** [comment]
I'm looking for this history feature, where is it in the app? I can't seem to find it (was about to submit a feature request). Thank you.

**Comment by gschier** [comment]
@Plasma top-right of the response pane

**Comment by Plasma** [comment]
Thank you! I tried looking for it in the menus and everywhere but didn't see it.
