### ISSUE TITLE
Insomnia auto updated and deleted all my request collections. This is unacceptable

### ISSUE THREAD

**Issue by Pasakinskas** [getinsomnia/insomnia#6871]
### Expected Behavior

After pushing an update, insomnia at the very least provides a way to export past request as curl

### Actual Behavior

allows me to login with several different options while login was not required before accessing "use the local scratch pad" opens an empty project. 

### Reproduction Steps

Update insomnia to latest version.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I have no clue how could this leave critical bug to production. I will not be using insomnia any more.

### Insomnia Version

8.X

### What operating system are you using?

macOS

### Operating System Version

macOS 13.3.1 

### Installation method

homebrew

### Last Known Working Insomnia version

7.X

**Comment by filfreire** [comment]
Hey @Pasakinskas sorry for the troubling experience. Your collections are still there, but since 8.x you'll have to login, even if you want to keep the collections only locally. Alternatively, if you don't want to login, you canexport them from the initial login menu and then import them into scratchpad. 

You can find previous discussions the community has had and also other feedback in other issues and discussions.

See for example https://github.com/Kong/insomnia/discussions/6626#discussioncomment-7299800 for context.
