### ISSUE TITLE
I Hate the new Insomnia. I hate that I need to register to access my Request Collection. WTF????

### ISSUE THREAD

**Issue by exotexot** [getinsomnia/insomnia#6877]
### Expected Behavior

I deliberately took the time to share my feelings about the new developments with insomnia. I really bothers me that much that I'm expressing my feelings here..

I always loved Insomnia. Great tool. But now it is pretty garbage. I appreciate the active development, but this register wall, forces me to sign up to access my request collection. THIS IS BLACKMAILING. I hate you for this. 

### Actual Behavior

....

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

latest

### What operating system are you using?

macOS

### Operating System Version

macOS 

### Installation method

I don't know

**Comment by filfreire** [comment]
@exotexot sorry for the bad experience. I understand your feelings.

Your collections are still there, but since 8.x you'll have to login, and I understand how this can be frustrating. 

If you don't want to login, you can still export your collections from the initial login menu and then import them into scratchpad, which won't require you to login ever.

See for https://github.com/Kong/insomnia/discussions/6626#discussioncomment-7299800 for context.

**Comment by Jones-S** [comment]
Same feelings here. Login, Export and never use again!
It was a nice product until there was the update without information and then the forced login. Very bad UX!
Goodbye.

**Comment by exotexot** [comment]
Okay. Since the latest update 8.6.1, I cannot address my local backend ...
I didn't even update voluntarily. In the meantime it asked my to Login again...

**And I took the time to dig out this thread again, and again mention, that I hate insomnia.**

If anyone has another proposal, other than Postman, then please share it here.
