### ISSUE TITLE
Lost all my work

### ISSUE THREAD

**Issue by michaelflorentin** [getinsomnia/insomnia#6913]
### Expected Behavior

I expected to retain all my work I have put into writing requests.

### Actual Behavior

All my work is lost.

### Reproduction Steps

1. Open Insomnia.
2. Be met with a unskippable login screen.
3. Struggle with creating an account/logging in for half an hour.
4. Finally logged in.
5. All my work is nowhere to be found.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.4.5

### What operating system are you using?

macOS

### Operating System Version

14.1.1

### Installation method

Download app

**Comment by pixelpaulaus** [comment]
same issue, lost everything.  this app use to be so good before this account creation requirements.
Time to start looking for something else.

**Comment by tberger-plugsurfing** [comment]
Same here, all my data is gone. Wtf!

**Comment by suchislife801** [comment]
Welcome back to your data. Now quick! Save your requests! I know how it feels!

### [Insomnia 2023.4.0](https://github.com/Kong/insomnia/releases/tag/core%402023.4.0)

**Comment by suchislife801** [comment]
Welcome back to your data. Below is the very last version that didn't absolutely ruin your request collections.

### [Insomnia 2023.4.0](https://github.com/Kong/insomnia/releases/tag/core%402023.4.0)

**Comment by suchislife801** [comment]
Welcome back to your data. Below is the very last version that didn't absolutely ruin your request collections.

**Make sure to disable Auto-Update in Settings.**

### [Insomnia 2023.4.0](https://github.com/Kong/insomnia/releases/tag/core%402023.4.0)

**Comment by subnetmarco** [comment]
You may have untracked projects in your workspace. If you go to Preferences -> Data do you see your projects in this section? If so, you can move them to your personal organization.

<img width="937" alt="Screenshot 2023-12-13 at 9 17 37 PM" src="https://github.com/Kong/insomnia/assets/964813/46498b6e-2258-4d06-8786-5aebca83fc17">

**Comment by vfonic** [comment]
Thank you, @subnetmarco. I've found my data under "Untracked projects". I want to export the data and import it into an earlier version of Insomnia. I don't want to create an account. I cannot do anything with the data, because all of the options are grayed-out, because I don't have an account nor organization. Why is my data being held hostage?

Thank you, @suchislife801 for the link!

**Comment by subnetmarco** [comment]
If you logout from the application, in the login screen we show an "Export data" button to export your data without having to create an account.

**Comment by vfonic** [comment]
I couldn't find how to logout since I'm not logged in, but I found data export at the top of the Data tab (also seen on your screenshot above).

Seems like I didn't even need to export anything. I just downloaded earlier release, disabled the automatic updates, and the app opened with all the settings/configuration I had from before.

Thanks!

**Comment by subnetmarco** [comment]
That will do it.
