### ISSUE TITLE
Stuck in Welcome loop

### ISSUE THREAD

**Issue by maxbry** [getinsomnia/insomnia#6918]
### Expected Behavior

I need to login again for whatever reason. I click `Continue with Github` because I used my Github account. In my browser, I'm asked for a password, I enter a password but it says it is wrong. I click back, click `Continue with Github` and get automatically logged in, I can see the Dashboard.
In the dasboard, I see `Open`. When I click it, the Insomnia application opens but it shows the Welcome screen again. Alternatively, it would be nice to be able to generate the token somewhere in the dashboard so I can use it to log in, I have no idea where that token should be coming from otherwise

### Actual Behavior

When I click `Open` in the dashboard and Insomnia opens, I expect to be logged in because in my browser I am logged in.

### Reproduction Steps

See exptected behaviour.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.4.5

### What operating system are you using?

macOS

### Operating System Version

macOS 13

### Installation method

don't remember

**Comment by zhengjitf** [comment]
It’s more likely an optimization, for not great at experience.

`Open` button just directs to an organization, via `insomnia://app/open/organization?organizationId=$id`, without any authorization logic (It will be great and intuitive if apply authorization meantime). 

The authorization callback link looks like `insomnia://app/auth/finish?box=xx`.

**Comment by gatzjames** [comment]
Hey @maxbry thanks for the feedback since you forgot your encryption passphrase you can't access the data in the app.
We just updated this flow to include a "Reset passphrase" link for that specific case.
This should help you recover access to your account and local data in the app.

<img width="486" alt="image" src="https://github.com/Kong/insomnia/assets/12115431/d0524a02-a2c3-448c-8ce7-27858fa0d189">

I'll close the issue since this is now addressed in the website and looking forward for any feedback!
