### ISSUE TITLE
Why do I need to login all out of a sudden?!

### ISSUE THREAD

**Issue by vfonic** [getinsomnia/insomnia#6923]
### Expected Behavior

1. Open the app.
2. Use the app like before

### Actual Behavior

1. Open the app
2. Random screens and messages appear
3. Login or register (???)
4. All my existing profiles are lost?!

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.4.5

### What operating system are you using?

macOS

### Operating System Version

.........

### Installation method

..........

**Comment by subnetmarco** [comment]
As Insomnia is growing we are incentivizing signups in order to convert more users to a premium plans and bring the product on a sustainable course (it was not on one before).

With that said, you can still use Insomnia for free on the Free plan, and having an account doesn't mean that your data moves to the cloud. You can still store things locally, but if you do decide to store them in the cloud then we have also shipped unlimited collaboration on one project on the Free plan (quite unique in the industry, as everybody else charges for it).

Therefore you will see your projects after logging in.You can also export your projects anytime before logging in. You can use the Scratch Pad without an account, but it is limited to one collection. If you decide to create an account, you can decide the locality of your projects still (cloud, local and Git is also an option in one of the premium plans).

**Comment by vfonic** [comment]
I understand that you want to make money. However, the app I installed a year ago and the one that I got automatically upgraded to, are two very different applications.

1. I lost all of the configurations that I had
2. Instead of GraphiQL-like UI, I'm welcomed to some disfunctional new UI called Scratch Pad
3. I'm asked to create an account for an open-source project that I was happily using, without an account - the only need for an account was an auth token for GraphQL queries if one was needed.

Imagine you upgrade `curl` and now it's asking you to login using Google. Imagine the same for `wget`, VS Code, your favorite git client, React, npm, node,...

This is not how you convert more users to Premium plan. Sure, some might convert, but you lost trust of the community.

Best of luck with your business!

**Comment by vfonic** [comment]
For anyone else who comes here, here's the link to the earlier version of Insomnia, without all the...new and useful...functionalities that no one asked for.

**Make sure to disable Auto-Update in Settings.**

[Insomnia 2023.4.0](https://github.com/Kong/insomnia/releases/tag/core%402023.4.0)

**Comment by msuddaby** [comment]
Came across this application after looking for Postman alternatives once they removed all features for non-registered users and found that this is basically just Postman 2.0.

Here's some alternatives I've found in my search:
https://github.com/flawiddsouza/Restfox
https://docs.hoppscotch.io/

**Comment by subnetmarco** [comment]
Don't spam @msuddaby

**Comment by msuddaby** [comment]
Genuinely curious, how is offering open source and non-sponsored solutions to functionality that was removed from this app considered spam?

**Comment by subnetmarco** [comment]
Because this repository is meant to address topics related to the Insomnia project.

If you want to mention alternatives and switch the conversation away from Insomnia, write non-actionable comments, you are welcome to write all about it in your own blog, start a Reddit or HN conversation, or any other venue. But please don't treat this repository as your personal billboard. We are working here.
