### ISSUE TITLE
[BUG] OAuth2 GraphQL failed to find request

### ISSUE THREAD

**Issue by DiederikvandenB** [getinsomnia/insomnia#699]
- Insomnia Version: 5.12.4
- Operating System: Mac OS 10.13

## Details

Hi! Thanks for making this amazing app. Really makes my life easier :). I am however encountering a nasty error. We have a [Laravel GraphQL](https://github.com/rebing/graphql-laravel) setup which protects routes through Laravel OAuth2 Passport. Everything works fine, except for the fact that every now and then the schema cannot be fetched. The specific error is:

```Failed to find request: req_78910ff12d2ce1616b304c338d4ed4df.graphql``` 

Other apps like GraphiQL all work fine. Furthermore, running the GraphQL query is also successful. Just fetching the schema in Insomnia doesn't work. The only way to get the schema working again is by deleting the request and readding it, which is quite cumbersome.

I haven't had enough time to properly test it, but if we disable OAuth2 it seems like everything is working correctly. I also checked the dev console and no errors are reported there.

Any ideas?

**Comment by TCFox** [comment]
Can confirm, I'm having the same issue. This only affects GraphQL schema fetching when used in conjunction with an OAuth 2 scheme, when the access token is copied into a "Bearer Token" auth scheme, schema fetching behaves as expected.

**Comment by gschier** [comment]
Should be an easy fix hopefully. I'll try and get it working for the next release.

**Comment by DiederikvandenB** [comment]
Thanks for your efforts, @gschier. It seems however that the issue has not been fixed yet. @TCFox, could you maybe confirm that with the most recent release you are still getting the same error?

**Comment by gschier** [comment]
Did you try on version 5.14.3?

**Comment by DiederikvandenB** [comment]
Yes, see screenshot:
<img width="1049" alt="screen shot 2018-01-30 at 09 53 19" src="https://user-images.githubusercontent.com/6132723/35556770-7527ae54-05a3-11e8-84a2-b407026379ba.png">

**Comment by DiederikvandenB** [comment]
I know this is a different error to the one I initially reported, but I am seeing that one too on different requests.

**Comment by tm1000** [comment]
Seeing this as well. Schema fetching caches data such as scope and tokens and credentials

**Comment by DiederikvandenB** [comment]
Yeah, the error is unfortunately still present in the most recent version.

**Comment by gschier** [comment]
@tm1000 can you provide more info on what exactly you are seeing? There is no caching logic in Insomnia's codebase.

**Comment by tm1000** [comment]
@gschier hi there.

So here's what I am seeing. I am constantly switching the oauth type from "implicit" to "client credentials". I am also changing the scope (adding and removing scopes).

This is all find when I hit the "send" button. The tokens are updated.

However when I go to fetch the schema Insomnia uses the old scope and old tokens. I can confirm this by deleting all valid tokens in my databases and then going back into Insomnia and fetching a new token. Again the query works (send) but when I go to fetch the schema Insomnia uses the old token.. or if I switch from Authorization Code to client credentials it keeps trying to use the refresh token.

I was literally yelling at my computer for over an hour until I figured out what was going on (in my implementation of GraphQL some parts of the query are hidden with scopes).

Closing/restarting Insomnia doesn't fix the issue. The only way I can completely fix the issue is by deleting the "request" and starting over.

**Comment by tm1000** [comment]
@gschier was the above helpful?

**Comment by tm1000** [comment]
I noticed this blurb in the newest release "GraphQL introspection requests are no longer synced or exported"

**Comment by tm1000** [comment]
Ref #835

**Comment by gschier** [comment]
@tm1000 sorry, somehow I missed your earlier comments. I'm glad that it's working now! Thanks for letting me know 😄 👍
