### ISSUE TITLE
[Bug] unexpected end of comment

### ISSUE THREAD

**Issue by 5n00p4eg** [getinsomnia/insomnia#702]
- Insomnia Version: 5.12.4 (5.12.4.1752)
- Operating System: macOS High Sierra 10.13.2 (17C88)

Im trying to make POST request with file. I'm using multipart/form-data mode and file field type.
Everything on thes to screenshots.

Second appears when I push Send button.

<img width="597" alt="1" src="https://user-images.githubusercontent.com/838451/34817038-6d51c586-f6bf-11e7-9755-dce3a71a7fd2.png">
<img width="783" alt="2" src="https://user-images.githubusercontent.com/838451/34817039-6d6ec172-f6bf-11e7-84d4-f9a0cf2da17a.png">

**Comment by gschier** [comment]
Can you paste the raw text value of that input field  here?

**Comment by 5n00p4eg** [comment]
I don't know how to see raw value but when I switch to text mode and enable nunjuks power user mode I see this value: 
`{% file '/Users/user/Downloads/1.png' %}`

Somehow my field start working when I deleted original one and create new one.
You can try use file function in text field(I did this before) and then change field type to file.

**Comment by gschier** [comment]
Sorry, I should have provided some instructions. You can get the raw value by selecting everything in the field and copying it. Power user mode also works, though :)

That error message you saw happens when a field contains `#}`. `{# ... #}` is how you write a comment in the underlying template engine (Nunjucks) so I assume that `#}` got into the field somehow and went away when you deleted it.

Going to close this one for now but definitely let me know if it happens again.
