### ISSUE TITLE
[Bug] App hangs after collapsing large JSON in response

### ISSUE THREAD

**Issue by francislavoie** [getinsomnia/insomnia#714]
- Insomnia Version: 5.12.4
- Operating System: Linux, Elementary OS (Ubuntu-based)

## Details

I have reasonably big JSON responses (800kb). When I try to collapse one of the keys (~40,000 lines), the app becomes completely unresponsive and eventually gives me a popup asking if I want to reload.

**Comment by gschier** [comment]
How well do other text editors handle collapsing the same amount of data? Not sure there's much we can do about this since that behavior is delegated to Codemirror. I wish there was some way to intercept that slow behavior and cancel it after a given interval.

I remember searching a while ago about Codemirror performance issues and their response was basically "It's as good as it gets". 

This is one of the reasons I started working on https://github.com/getinsomnia/insomnia/pull/494
If there are a lot of children it won't show them until requested, making it snappy to browse responses of over 100MB.

**Comment by francislavoie** [comment]
Well, the same works fine on Postman, so there's that.

**Comment by gschier** [comment]
Hmm, they are using [Ace](https://ace.c9.io/) which maybe handles that case better? I have heard that Insomnia handles large files better than Postman though, so maybe there are trade-offs.

If you link to an example JSON blob I can test it out on my end to see if there is anything obvious that can be done.

**Comment by francislavoie** [comment]
Sure, I'll have to obfuscate the data though, so I'll have to get back to you on that.

**Comment by gschier** [comment]
Nevermind actually! I found an old script I made to generate random JSON blobs and was able to reproduce it.

**Comment by gschier** [comment]
It's weird because it's only slow the first time it's collapsed (if it doesn't crash). After that, collapse/expand of the same object is instant.

**Comment by francislavoie** [comment]
Great, thanks :smile:
