### ISSUE TITLE
[Feature Request] Variables in Refresh Token field for OAuth2

### ISSUE THREAD

**Issue by paulreimer** [getinsomnia/insomnia#715]
- Insomnia Version: v5.12.4
- Operating System: macOS High Sierra 10.13.2

## Details

Currently, cannot use variable completion in the REFRESH TOKEN field in an OAuth 2 authentication method. I would like to be able to store a refresh token in a private sub-environment, since my refresh token is different in each environment. Perhaps I'm doing things wrong, or what I'm suggesting is insecure in a way I haven't thought of yet?

This app is so amazing and works perfectly otherwise.

**Comment by paulreimer** [comment]
Also, I would like to be able to refer to the access_token (output) field, as a variable elsewhere.

**Comment by gschier** [comment]
The refresh token and access token are filled automatically when Insomnia performs the authentication. It would be better to instead store the authorization URL, client ID, etc per environment and let Insomnia do the rest.

**Comment by paulreimer** [comment]
Hmmm, well I do have that too, but unfortunately I am trying to use Firebase user auth (which is using OpenID Connect), and in this case needs `?auth={access_token}`.

In fact I'd prefer not to send the `Bearer: ` header at all, but if I override it with the query param above, it doesn't seem to matter. But, I need to update my query param every hour (manually, by copy/paste) from the OAuth 2 `access_token` field.

https://firebase.google.com/docs/database/rest/auth#firebase_id_tokens

**Comment by gschier** [comment]
Just added a way to get the current access token from the request dynamically. Will that solve your problem?

<img width="534" alt="image" src="https://user-images.githubusercontent.com/587576/35029054-a057cab8-fb8b-11e7-81fd-a86840218aa6.png">

**Comment by paulreimer** [comment]
That's awesome! That definitely solves one part of it.

This might be something that is different with OpenID Connect (vs OAuth2), or maybe with the way I am re-using firebase refresh tokens, but I obtained my refresh_token from a firebase webapp session in a browser -- it is indefinitely long-lived and generated elsewhere. Then (same as OAuth2 access token step) that refresh_token gets supplied to `access_token_url` to receive an `access_token` (the mandatory field in OIDC is called `id_token`, but Google provides an `access_token` with the same value in the response as well, this is what Insomnia is picking up.)
https://developers.google.com/identity/toolkit/securetoken

I suppose OpenID Connect might be worth a separate Authentication entry (different from OAuth2) at some point, it is different enough and Google is pretty generous with optional fields about making it look like OAuth2, but other providers might be more strict and Insomnia wouldn't work then.

https://openid.net/specs/openid-connect-core-1_0.html

**Comment by gschier** [comment]
Thanks for that info. It's quite interesting.

It looks like they're not telling you the full story. The OAuth 2.0 `authorization_code` grant type consists of two phases:

1. The login phase, where a login form is presented to the user and a `code` is returned via a redirect after submitting the form
2. The token phase, where the `code` is exchanged for an `access_token` and `refresh_token`, which can then be used to make authenticated requests

Right now, the first phase is happening in your web browser and you're pulling the code out of it manually. So, in that sense it's only half of OpenID.

I'm not really sure what the best solution for this would be, as my knowledge of the Google authorization frameworks is limited. However, I just merged a PR today that adds support for the OIDC `id_token` response type. Not sure if that applies to this at all. https://github.com/getinsomnia/insomnia/pull/681

I _did_ also take a look at supporting environment variables in the refresh and access token fields within Insomnia, but it turned out that it would take more time than I have right now.
