### ISSUE TITLE
[Feature Request] UI Improvements for key input on OAuth 1.0

### ISSUE THREAD

**Issue by c22** [getinsomnia/insomnia#717]
- Insomnia Version: dd51487
- Operating System: All

## Details

As mentioned in #606 it would be nice if the RSA key input textarea only showed up after RSA-SHA1 is selected from the dropdown box, this makes it more consistent with other authenticators.

I don't think this is a high priority but I am mainly creating this issue as I might attempt to add it in myself at some point.

**Comment by gschier** [comment]
I actually already did this yesterday after merging the PR.

I also moved the key input to a modal dialog because the `CodeEditor` component was causing some weird horizontal scrolling issues in the form.

<img width="676" alt="image" src="https://user-images.githubusercontent.com/587576/35027161-bdb0d62c-fb81-11e7-9df3-92d6c15c1854.png">

**Comment by c22** [comment]
Oh awesome, nice work 😄
