### ISSUE TITLE
Regression: wildcard values don't work for the host of certificates

### ISSUE THREAD

**Issue by alice-wondered** [getinsomnia/insomnia#7181]
### Expected Behavior

Wildcard values such as `*.mydomain.com` should work for host matching certificates for mTLS

### Actual Behavior

Wildcard values don't match properly and each subdomain must be added individually. 

Seems to be a regression of https://github.com/Kong/insomnia/issues/243

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.6.1

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.4

### Installation method

insomnia.rest

**Comment by hvitoi** [comment]
This regression may have been introduced by #6274. Test cases that validate the wildcard matching have been removed.

**Comment by hvitoi** [comment]
There is no much context on the PR description of why this feature has been removed as part of the electron bump

**Comment by hvitoi** [comment]
I'm debugging this issue and this regression is being cause by [this line](https://github.com/jackkav/insomnia/blob/a5d843171a841b9117e2e4b1503a362fca6bcfd0/packages/insomnia/src/network/url-matches-cert-host.ts#L13). 
On building an `URL object` it is additionally encoding the hostname characters so that `https://*.myhost.com/` is turned into `https://%2A.myhost.com` and the latter won't match with the actual url being requested and thus won't attach the certificate into the request
