### ISSUE TITLE
[Improvement] AWS Multifactor Auth Support

### ISSUE THREAD

**Issue by gondalez** [getinsomnia/insomnia#719]
Thank you @focusaurus and @gschier  for your work in #347, I use it every day :)

At the bottom of #347 you mention supporting AWS multifactor auth via the `AWS_SESSION_TOKEN`. 
If this were to be implemented I would use it every other day!

My use case:
I want to get `/cat/_indices` and run some aws elasticsearch queries. I do this using a read only AWS_ACCESS_KEY / AWS_SECRET_ACCESS_KEY. 

When I want to manipulate backups or change some settings I need write access. I generate a temporary AWS_ACCESS_KEY, AWS_SECRET_ACCESS_KEY and AWS_SESSION_TOKEN to do this.

I would love to see a third optional field that lets me put in the AWS_SESSION_TOKEN for times such as these!

**Comment by gschier** [comment]
I don't really know much about how that would work but maybe @focusaurus has an idea? I'd be happy to help if someone wanted to take this on.

**Comment by focusaurus** [comment]
Yeah I'll take a look tomorrow. Sorry I saw this thread just haven't gotten around it. I believe if the end user can get a valid trio of credentials from the aws command line tool and paste them into Insomnia, they'll work for 24 hours.

**Comment by focusaurus** [comment]
OK so I have the back end changes made in a feature branch on my fork. They are very straightforward just 3 fields instead of 2. I think for the UI trying to use the KeyValueEditor is clunky. What we really have is 3 values and I think the most logical UI would just be a stack of 3 inputs:

- AWS_ACCESS_KEY_ID (text, required)
- AWS_SECRET_ACCESS_KEY (password, required)
- AWS_SESSION_TOKEN (password, optional)

They can have a single enable/disable checkbox.

@gschier What do you think? If you think that UI makes sense it might be faster for you to just wire it up as I'm pretty unfamiliar with the widget library available here. Or if you want me to do it and you can point me to the basic set of components I should look to combine like `<InputStack><TextRow/><TextRow/><TextRow/></InputStack>` (just making up those names for example)?

**Comment by focusaurus** [comment]
OK so here's what is done or close to done and what else I think we should do:

- [x] Support the 3 fields in the network/request code
- [x] Test it works against AWS with 2-field SFA
- [x] Test it works against AWS with 3-field MFA
- [x] Ugly/hacky UI with 3 fields and basic `input` tags
----
**HELP WANTED** on the following:

- [ ] Fix the UI in terms of layout, styling, using the optimal JSX tags/components
  - input width, placement of the checkbox, styling for when disabled (see `key-value-editor__row-wrapper--disabled`)
- [ ] Get the nunjucks stuff working

Code is in the [feature/aws-auth-mfa](https://github.com/focusaurus/insomnia/tree/feature/aws-auth-mfa) branch on my fork.

<img width="224" alt="screen shot 2018-01-28 at 10 47 40 am" src="https://user-images.githubusercontent.com/482377/35485168-b6a956e8-0418-11e8-93bc-cbe57432e874.png">

**Comment by gschier** [comment]
On it! I'll try to get this done today.

**Comment by gschier** [comment]
How's this? 

<img width="414" alt="image" src="https://user-images.githubusercontent.com/587576/35490705-7c572424-04dc-11e8-95f8-ba0fbf013c06.png">

**Comment by focusaurus** [comment]
That looks good. Nit: I think if most labels are just capitalized you could Access Key ID title case the labels.

**Comment by focusaurus** [comment]
Also we might want some help text explaining:

- First 2 always required, last one only fill out if you are doing MFA

**Comment by focusaurus** [comment]
Oh and where did you put the enable/disable checkbox?

**Comment by gschier** [comment]
> That looks good. Nit: I think if most labels are just capitalized you could Access Key ID title case the labels.
I just used the same labels that the rest of the app uses. They're all-caps everywhere.

I wasn't sure whether to keep the checkbox or not because only some of the auth types have it. But, I've decided to make it consistent and add it to all the ones that don't as well.

<img width="580" alt="image" src="https://user-images.githubusercontent.com/587576/35491966-df21af40-04e4-11e8-93be-19a319a836f0.png">
