### ISSUE TITLE
[Feature Request] Disable history recording in settings

### ISSUE THREAD

**Issue by msalvadores** [getinsomnia/insomnia#722]
I love the tool. Awesome work. I'd like to have the possibility to disable history recording across the entire tool. This useful when working and testing APIs that return private data.

Thanks

**Comment by gschier** [comment]
Is the issue that they are being stored to the filesystem or that they are visible to other users who may see your screen?

**Comment by msalvadores** [comment]
@gschier mostly the fact that they are stored in the filesystem.

**Comment by gschier** [comment]
I like the idea of having that as a feature but it would require a fairly major architectural change to make it possible. I would, however, consider working on this if there is enough demand.

**Comment by mxmlnglt** [comment]
@gschier @msalvadores 
I find it rather strange this issue has been closed, because actually the removal of the history (or "kind of" history) is working for the environments: e.g. make several changes to some of your environments => you can see extra lines added to the `insomnia.Environment.db` file, but when closing Insomnia, those lines are removed (only the last one is kept).
Wouldn't it be possible to do the same on the other databases?

**Comment by gschier** [comment]
Hi @mxmlnglt,

What you are referring to is not actually related to Insomnia, but is a result of how the local database works. 

Insomnia uses [NeDB](https://github.com/louischatriot/nedb) to store data locally. It is an append-only database, meaning all inserts, updates, and deletes are appended to the DB file (essentially as commands) on the filesystem. This is because appending to a file is atomic, whereas updating a file may lead to corruption. 

When Insomnia starts up, this DB file is "compacted," which entails iterating through all the appended operations in the DB file, resolving them, and re-saving the file. 

What the original post was describing, I think, was specifically around not holding onto response objects because they may contain sensitive information. Recently, the ability to delete all responses for a workspace was implemented which, although is not automatic, can be used to bulk-delete responses when the user choses to do so.
