### ISSUE TITLE
Response preview adds whitespace to URL

### ISSUE THREAD

**Issue by Tolsto** [getinsomnia/insomnia#7240]
### Expected Behavior

The preview should not add a whitespace in the middle of the URL.

### Actual Behavior

<img width="493" alt="image" src="https://github.com/Kong/insomnia/assets/20240901/d05d3f9d-fe06-4cf2-bb61-c493d1950284">
<img width="492" alt="image" src="https://github.com/Kong/insomnia/assets/20240901/0a87ed08-81d9-430b-90e9-e05ffc7c7222">

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.0.0-beta.3

### What operating system are you using?

macOS

### Operating System Version

14.4.1 (23E224)

### Installation method

dmg

**Comment by git-commit-amen** [comment]
Able to reproduce this bug. Specifically, seems to happen when **both** of the following conditions are met:

- Response contains a JSON key value enclosed in single quotes rather than double quotes
- Value that is enclosed in the aforementioned single quotes contains a colon

Not sure why this happens.

Worth noting, single quotes for JSON keys and values is technically invalid syntax (although some popular JSON formatters are lenient on this). This is still a valid bug though of course.

**Comment by Tolsto** [comment]
Hm, didn't even notice the single quotes. That's actually the default serialization of AWS Lambda, at least when running locally with SAM CLI.

**Comment by jackkav** [comment]
Appears to be caused by this line. In the prettify function taken from json-lint. https://github.com/Kong/insomnia/blob/7abe25c3f2e807355a66415b6cfd68f425c35f06/packages/insomnia/src/utils/prettify/json.ts#L165

1. pull a newer copy of this code from json-lint
2. add a test and fix it inline
3. use `prettier` or some other formatter than can accept single quoted objects

**Comment by subnetmarco** [comment]
> That's actually the default serialization of AWS Lambda

Single quotes is not a valid JSON value, this is a problem with AWS.
