### ISSUE TITLE
[Feature Request] Hotkey/Option to focus preview-tab/window

### ISSUE THREAD

**Issue by inovek** [getinsomnia/insomnia#737]
After a request was made, most users will examine the response in the preview-tab/window.

Currently you've to focus the preview-tab/window with an mouse-click before the keyboard-presses getting recognized.

**I would suggest:**
- Auto-Focus after request Option for the preview-tab/window in the options.
- Keyboard accessibility to the preview-tab/window without a additional mouse-click into it.

**Comment by gschier** [comment]
I've been wanted to add shortcuts to focus the panes for a while but haven't yet gotten around to it. 

I would prefer not to make auto-focus the default because I think that would be distracting for a lot of use-cases (I often keep my cursor in the query/header/url input boxes to quickly change and make requests). It seems like a hotkey to focus the response pane would suffice for most users but I would be open to making auto-focus a preference if there is greater demand for it.
