### ISSUE TITLE
[Feature Request] Add a template viewer

### ISSUE THREAD

**Issue by joushx** [getinsomnia/insomnia#750]
By adding a viewer that renders a template using the response, complex JSON dicts can be displayed easily in a user defined way. I already created [an implementation](https://github.com/joushx/insomnia/commit/257ac582e4e4191c30bec74837304ed4b02113a0) that works so far and uses nunjucks:

![Screenshot](https://user-images.githubusercontent.com/832178/36061275-8733c28c-0e58-11e8-8629-a819145cc9f1.png)

Please let me know if you have doubts about this feature of if there is something I should change before creating a pull request.

**Comment by gschier** [comment]
Nice work @joushx!

I love the idea of this but since it only applies to JSON responses, and seems like a fairly niche use-case, I think it might be better suited as a plugin.

Unfortunately, the plugin system does not currently support a way of creating custom response viewers, but I'd be willing to do the work required to make that possible. 

Please let me know your thoughts on this 😄

**Comment by gschier** [comment]
Yes, this isn't possible yet, but I'll try and make it possible soon.

**Comment by gschier** [comment]
Adding Protobuf and Kaitai support are actually slightly different problems. The template viewer is a way to view an already-supported content-type in a different way, whereas Protobuf and kaitai are their own content-types altogether. 

I'd actually be open to supporting Protobuf natively (since it's so popular (I think?)) and Kaitai as well, as long as the feature-set required to support them is not overwhelmingly complex.

**Comment by joushx** [comment]
Sorry, I overlooked the notification last February. I really like the draft so far, because it makes the plugin development very flexible. Nice work.
