### ISSUE TITLE
[Feature Request] Switch between actions/body types without losing data

### ISSUE THREAD

**Issue by mlambley** [getinsomnia/insomnia#752]
I'd like to be able to switch between PATCH/POST/GET etc. requests within a single url without hassle.

My workflow is:

1) I submit a PATCH request, I select JSON body and enter the data.
2) I switch to GET, but it says 400 Bad Request because there's a body present. 
3) I change the body type to No Body and it warns me that it's about to delete my existing body data. 
4) I cancel out of the Switch Body Type dialog, copy my json data somewhere else to not lose it.
5) Switch body type to No Body, change to GET, perform GET action.
6) Switch back to PATCH, select JSON, find my notepad window with the json data and paste it in.

What I'd like my workflow to be is:

1) I submit a PATCH request, I select JSON body and enter the data.
2) I switch to GET. The system recognises that you cannot submit a body with a GET, so it greys out the Body tab and does not attempt to submit my json data.
3) I switch back to POST/PATCH/something with a body. The body tab ungreys and becomes functional again, with my previous json data still there.

Or at the very least:

1) I submit a PATCH request, I select JSON body and enter the data.
2) I switch to GET, but it says 400 Bad Request because there's a body present. 
3) I change it to No Body, and the system does so without warning me because it does not delete my body data.
4) Switch back to PATCH, select JSON. My json data is still there from before.

Please consider whether or not either of my suggested workflows can/should be implemented. Thank you.

Edit: I've just noticed that it is possible to send a body with any request, so perhaps my first option won't work. But my second option - switching to No Body doesn't erase the body but just hides it instead - could still fix this problem.

**Comment by gschier** [comment]
Hmm, this is an interesting one. Technically, sending a payload with a `GET` request is valid (although frowned upon) so you first suggestion won't work. However, your second suggestion seems like a good idea, but may not be as easy to implement as simply keeping the value around.

I'll explain what it would take to implement this in case anyone wants to contribute a PR for this:

- Add new field to `RequestMeta` to store the old request body
- Update new field when changing request body to "No Body"
- Attempt to restore body when changing request body from "No Body" to something else

The reason I don't think the old body should be stored directly on the `Request` model is because it is reserved for properties directly related to sending the request. Since this improvement is strictly a user experience feature, storing it on `RequestMeta` is a better choice.
