### ISSUE TITLE
[Question] Combine base 64 encode and file tags

### ISSUE THREAD

**Issue by JonasDoebertin** [getinsomnia/insomnia#756]
- Insomnia Version: 5.14.6.1855
- Operating System: macOS 10.11.6

## Details

Is there a way of combining the `{% base64 'encode', 'myvalue' %}` and `{% file 'myfile' %}` tags/functions to insert a base64 representation of a selected file?

**Comment by gschier** [comment]
If the file is not binary you could set an environment variable to the value of the file, then reference that variable in another variable.

```json
{
	"b64": "{% base64 'encode', myFile %}",
	"myFile": "{% file '/foo.txt' %}"
}
```

However, if you need binary file support you could create a [plugin](https://support.insomnia.rest/article/26-plugins) for that. The `file` plugin is a good place to start: https://github.com/getinsomnia/insomnia/blob/develop/plugins/insomnia-plugin-file/index.js

**Comment by Pizzacus** [comment]
So this is a bit old but I found the right solution

Since Insomnia uses Nunjucks for templating, **you can do this**

```
{% set data %}{% file '/path/to/your/dog/pics' %}{% endset %}{% base64 'encode', data %}
```

This just sets a variable so then the base64 tag can use it

-----

The following syntax **doesn't work**, but it could have been possible...

```
{{ base64('encode', file('/path/path/path')) }}
```
... if Insomnia used Nunjucks functions instead of tags (because functions are way easier to combine and actually serve this purpose, but Insomnia uses tags instead which are normally meant to be used to create new syntax and structures)
