### ISSUE TITLE
Using file token in MultiPart requests

### ISSUE THREAD

**Issue by Mardoxx** [getinsomnia/insomnia#761]
- Insomnia Version: 5.14.7
- Operating System: w10
## Details

Currently you can't select a file due to# 757 - At least on windows -. However modifying the config so it takes it, I realise that perhaps this functionality is broken?

If you create a MultiPart form request, add a field with a file token as the value, choose a file and submit it, it does not send the file properly.

Not sure if this is intended. I'd imagine it's just sending it as the string representation of the file contents, instead of sending it as a file. The latter would be more intuitive I think. Might be a breaking change if someone is expecting to send the file contents as a string value though... Hmm!

**Comment by gschier** [comment]
Currently, all tags import their values as strings. It would be pretty difficult to change this behavior at this point.

To use files in multipart, you should switch the form value to file instead

![image](https://user-images.githubusercontent.com/587576/36259956-e9e0a760-129a-11e8-8f1d-235b9e28c28c.png)

I'm going to mark this one as WONTFIX because the method in the screenshot above should be used instead.

**Comment by Mardoxx** [comment]
Ahh great, I thought as much! 😄

**Comment by gschier** [comment]
💯
