### ISSUE TITLE
Can't see my URL bar at all when a request is selected

### ISSUE THREAD

**Issue by ryanoillataguerre** [getinsomnia/insomnia#7769]
### Expected Behavior

I'd expect there to be a URL bar to use in each request, above the request/response panels. There is not!

### Actual Behavior

<img width="1512" alt="Screenshot 2024-07-27 at 10 21 03 AM" src="https://github.com/user-attachments/assets/2c89a186-d7d7-4e6d-8951-a25f0eb1e1fb">

### Reproduction Steps

- Download a fresh copy of Insomnia (M1 Macbook)
- Log in
- Open a collection (or create one)
- Create a request
- There is no url bar.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.3.2

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma Version 14.5

### Installation method

.dmg from website

**Comment by gatzjames** [comment]
Hi @ryanoillataguerre it looks like the request panel is minimized. If you try to grab the resize handle from the top/left based on if your layout is horizontal/vertical you can expand it back.
I've also made an update to not close those panels completely when resizing so that it doesn't create confusion like this.
Let me know if this worked for you

**Comment by ryanoillataguerre** [comment]
@gatzjames Whoa haha that's wild, would never have guessed. Thanks a bunch though! Good stuff
