### ISSUE TITLE
[Help] Using Environment Variables with templateTags API

### ISSUE THREAD

**Issue by pnewell** [getinsomnia/insomnia#779]
I am trying to create a basic plugin that combines a environment variable and a header tag and I can't figure out how to pull the environment variable.

**default-headers.js**
```
module.exports.requestHooks =[{
  run (context) {
    return context.request.getEnvironmentVariable('secret');
  }
}];
```

**index.js**
```
module.exports.templateTags = [{
  name: 'signature',
  displayName: 'Signature',
  description: 'generate signature',
  args: [],
  run (context) {
    const test = require('./src/default-headers');
    return test();
  }
}];
```
I keep getting the following error no matter what I try:

`TypeError: Cannot read property 'request' of undefined`

**Comment by gschier** [comment]
Are you sure the code in `default-headers.js` that you posted is correct? It looks like you are trying to call it as a function from `index.js` but `module.exports` is not a function in your sample code.

Are you trying to include the [`default-headers.js`](https://github.com/getinsomnia/insomnia/blob/73e96ba679d015d17ae51e5ffdfeefa567c1956b/plugins/insomnia-plugin-default-headers/src/default-headers.js) file from the insomnia repo? If so, this will not work because the `context` variable it is expecting is different from the `context` variable that's passed to template tags.

Let me see if I understand this correctly. You want to grab a value from the environment, generate a signature, and set a header on the request?

A template tag won't actually work for this because you cannot access or modify the request (eg. headers) from within a template tag. To do this, you'll have to do it entirely in a request hook. Here is some sample code I put together:

```js
module.exports.requestHooks = [
  context => {
    const secret = context.request.getEnvironmentVariable('secret');

    // Generate signature here
    const signature = '...';

    context.request.setHeader('Signature', signature);
  }
];
```

Let me know if that helps.

**Comment by pnewell** [comment]
@gschier Thanks so much for the response! I apologize for the incorrect naming, but I actually just used the default-headers.js as a starting place.

What I am actually trying to do is grab a. couple of the environmental variables (key, secret, format) and one of the header parameters (json), string them together, and md5 hash them for our sig authentication system. This would need to be passed as a header parameter which is why I was trying to create a template tag option.

Not sure if the example code you sent was with that in mind? I'll try and work a little more on it with your code snippet, but any additional tips would be very much appreciated!

Thanks again,
Paul

**Comment by gschier** [comment]
Happy to help! 

I _think_ my snippet should work for you.

You may have to modify this a bit, but this snippet will take the three values from the env that you need, and the header that includes the JSON you need, create an md5 hash with them, and set the result as a header on the request.

```js
const crypto = require('crypto');

module.exports.requestHooks = [
  context => {
    // Get key, secret, format from environment
    const key = context.request.getEnvironmentVariable('key');
    const secret = context.request.getEnvironmentVariable('secret');
    const format = context.request.getEnvironmentVariable('format');

    // Get json value from request header
    const json = context.request.getHeader('json');

    // Generate MD5 sum
    const hash = crypto.createHash('md5')
      .update(key + secret + format + json)
      .digest('hex')

    // Set header on current request
    context.request.setHeader('signature', hash);
  }
```

_Note that, since this is a request hook, it will execute on every request made within the app. If you need it to apply to only certain requests, you'll need to include an `if` statement to filter requests based on some attribute (URL, query param, header, etc). Please ignore this paragraph if it doesn't make sense :)_

**Comment by pnewell** [comment]
@gschier Makes sense! I think I got something very similar working, but I have a few quick follow-up questions:

1. This is likely due to my misunderstanding, but I just wanted to check to make sure their is no way to import the result from requestHooks into a templateTags method?
2. When using requestHooks alone, how can I tell if it is working or not? Is there any place to preview this in the UI or is it hidden / sends automatically?
3. If it is hidden, what is the best method for error handling while I get it set up? I can't seem to find anything in dev tools (I was able to locate it for templateTags though)

Thanks!

**Comment by gschier** [comment]
1. Correct. This is because there is currently no way to access the request headers from within a template tag (they are not yet aware if a request is being sent). Template tags have a different plugin API than hooks at the moment. I hope to try and merge these in the future.
2. Since you are setting a header, you can check the Timeline tab to see if the correct header was sent. You can also `console.log()` inside your plugin and view the logs in View -> Toggle DevTools -> Console.
3. I think answer 2 covered this. You can also `throw` errors within plugins and they will display in the response pane of the UI.

If you aren't seeing any logs in the console, I have three guesses as to why.

- you are not executing the request. Hooks are only run when requests are sent.
- an error is being thrown before your console log, which will show in the response pane.
- you forgot to refresh the plugin after making changes (ctrl+shift+R or cmd+shift+R)

Let me know if that helps.

**Comment by pnewell** [comment]
@gschier Success! Well, at least the sig creation was successful!

I have one last requirement that I have a bad feeling about. For POST calls this is fine I thin, but for GET call I need to pass the sig as a query parameter, so the final URL should look like this:

https://api.example.com/test?api_key=ABCD1234&format=json&json=%7B%22id%22%3A%22test%40example.com%22%7D&sig=8hf3498hiuh3ufh98h

I took a look through the relevant functions and didn't see one that looked related to link parameters, but let me know if there is some other way around this. Either way I'll post my finished code on here for anyone else who might need it!
