### ISSUE TITLE
[Feature Request] Use bootstrap style tooltips for template tags

### ISSUE THREAD

**Issue by benatkin** [getinsomnia/insomnia#821]
I'm looking to implement this myself, but as per the PR guide I want to check first.

<img width="638" alt="screen shot 2018-03-17 at 11 13 13 am" src="https://user-images.githubusercontent.com/4126/37557002-7b565834-29d4-11e8-8b46-25aae6be8317.png">

I think the template tags would benefit from having a tooltip that:

- displays right away
- allows for formatting (could show what environment it is from)
- can be copied
- can be edited (this would take some thinking to come up with a way of doing it)

The norm for bootstrap tooltips is to show right away. I think it would be nice to switch to these for template tags to make requests more readable, and probably some other areas where Operating System-style tooltips are used.

**Comment by gschier** [comment]
Hey @benatkin. Tooltips there would be awesome.

The codebase currently has a tooltip React component but it's not being used because the elements within the code editors don't currently use React. So, I think the solution here would be to transition the current code to render a React component instead.

Let me know if you are still interested in doing this or have any questions.

**Comment by EItanya** [comment]
hey, @gschier I am an avid user of Insomnia, and I am looking to get involved. I would be willing to take this on, do you think this would be a good starting place?

**Comment by gschier** [comment]
Sure! Looks like @benatkin has given you the thumbs up to take it on.

It requires getting to know the codebase a bit but shouldn't be a great starting point
