### ISSUE TITLE
No proxy filter list not working

### ISSUE THREAD

**Issue by cjvice99** [getinsomnia/insomnia#8215]
### Expected Behavior

Applying a comma separated list of addresses within the no proxy list in the preferences screen leads to the proxy settings not being used even when provided in the preferences screen and system variables

### Actual Behavior

The no proxy list is ignored and the provided proxy settings are used for all addresses.

### Reproduction Steps

1. Add proxy details to the network proxy preferences tab
2. Add an address to the no proxy list within the tab
3. Call an endpoint at that address
4. Note the proxy still being in use

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Which sync method do you use?

- [ ] Git sync.
- [X] Insomnia Cloud sync.
- [ ] Local only

### Insomnia Version

V10.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

Download from insomnia.rest

### Last Known Working Insomnia version

v10.1.0

**Comment by solorisx** [comment]
Experiencing the same issue with 10.2.0, whitelist worked with 10.1.1

**Comment by yaoweiprc** [comment]
I can not reproduce this issue with V10.2. Can you give me more detailed info to reproduce it? Do you use any Pre-request or After-response scripts in request? @cjvice99 @solorisx

**Comment by solorisx** [comment]
Hi @yaoweiprc, we do not use any pre- / after-request scripts. However, after testing it again - it appears that now the proxy whitelist only works if it includes the subdomain.

Suppose we have requests to dev.example.com, test.example.com, prod.example.com - having example.com in the proxy whitelist is no longer sufficient (neither is *.example.com), we would need to add all subdomains (which is very cumbersome because there are many).

**Comment by yaoweiprc** [comment]
@solorisx Thanks for your feedback, I'll look into it.

**Comment by yaoweiprc** [comment]
@cjvice99 @solorisx This behavior inconsistency seems to be caused by an update in the underlying dependency, node-libcurl. If you want the top-level domain in the "no proxy" configuration to apply to all its subdomains, please prefix it with a dot. For example, `.example.com` will apply to example.com itself and all its subdomains.

**Comment by yaoweiprc** [comment]
Added some annotation to illustrate this field.
https://github.com/Kong/insomnia/pull/8280
