### ISSUE TITLE
[Feature Request] View rendered template or sent request body

### ISSUE THREAD

**Issue by JordanSlaman** [getinsomnia/insomnia#917]
## Details

I make use of the templating feature heavily, but afaik there is no way for me to see the computed version of the request before/after I send it.

Would be useful to have a tab to see the computed (post template rendered) version when double checking syntax or debugging.

The main benefit however is that I would be able to quickly copy&paste or screenshot what I sent and what was responded by the server for dealing with support tickets on either side - as an API user or Developer.

As-is I need to re-create the computed version when demonstrating in text what a correct or broken api call looks like.

A tab on the top of the left pane that is added when there is a template tag detected would be great, or alternatively on the right pane let me see the request body that I sent.

Either/Both would be a great help to my workflow.

Thanks for the great tool.

**Comment by JordanSlaman** [comment]
Don't do that...

**Comment by gschier** [comment]
Hmm, I thought there was an older issue for this already but apparently not.

Curl provides a debug hook (currently used for the Timeline view) that includes both request and response data. It would be possible to hook into this to build a more complete debug viewer. However, it's a bit trickier to preview a response without sending, since a lot of stuff is still delegated to Curl (eg. generating auth headers and handling redirects).

One thing I've thought of is that it might be possible to set up a local proxy to intercept the request data instead of sending it, allowing it to be captured by the app as a "preview". I haven't done any work on that yet though to see if it's actually possible.

Anyway. I'm going to _accept_ this one so Stale bot doesn't close it.

**Comment by JordanSlaman** [comment]
Thanks for the response!

[Would this help?](https://curl.haxx.se/docs/manpage.html#--trace-ascii)
In the right pane if I could view the request I actually sent alongside the response that would do the trick.

Could also be good for debugging template formatting errors, if my server is whining about a field being the wrong type or something I can see the request I sent next to the template and might notice a bad tag.

**Comment by JordanSlaman** [comment]
It seems like this already kind of exists in the timeline view and I'm just a dumbass.

**Comment by gschier** [comment]
Yes, that's the same hook that powers the timeline at the moment. The timeline just doesn't show the full request body if it's larger than a few bytes.
