### ISSUE TITLE
[Installation] Update.exe detected by anti-virus software

### ISSUE THREAD

**Issue by Leandros** [getinsomnia/insomnia#963]
- Insomnia Version: 5.16.6
- Operating System: Windows 10 1709

## Details

This popped up, kinda randomly. I'm guessing due to the background updater doing it's job. 
You might wanna get either in contact with Avast or try to found out which behavior got detected, and fix it.

![capture](https://user-images.githubusercontent.com/396475/40927313-bb30ec5c-681e-11e8-89ea-13632c97876e.PNG)

(Sorry, the dialog is in German).

**Comment by gschier** [comment]
This has been a recurring issue since the beginning of Insomnia. Please mark it as "safe" in your antivirus. 

It seems like antivirus whitelists only apply to specific versions Update.exe and are cleared whenever it is changed. My guess is that a recent update to Electron used a new version of `Update.exe` which the antivirus hasn't seen yet.

**Comment by Leandros** [comment]
Alright, if you're aware, can this be closed?

**Comment by gschier** [comment]
Ya, I think so. I mean, it's not really a solution but I don't think there's anything we can do to prevent this from happening again 😢 

If you, or anyone else knows more about this than I do, please let me know 👍
